### PR TITLE
Snowflake COLUMN is not a reserved word

### LINKED ISSUE #2375: Snowflake issue parsing statement with COLUMN as an identifier
Trying to create a boolean in this way: 
` coalesce(a.column like '%"attribute":{"name":"something"%', false) as is_column`

## Expected Behaviour
The expected behavior would be for sqlfluff to lint my model and show me any lint errors that might exist.

## Observed Behaviour
sqlfluff returns a value error like:
`ValueError: unmatched '{' in format spec`

## Steps to Reproduce
Add a '{' characterwhile trying to match a pattern in a column.

## Dialect
Snowflake

## Version

sqlfluff, version 0.9.1
Python 3.7.4
dbt installed version: 0.21.0

## Configuration
```
[sqlfluff]
verbose = 0
nocolor = False
dialect = snowflake
templater = dbt
exclude_rules = L009, L011, L021, L029, L031, L033, L034, L041, L042, L044, L047, L050, L054
# link to the rule docs https://docs.sqlfluff.com/en/stable/rules.html
recurse = 0
output_line_length = 110
runaway_limit = 10
ignore_templated_areas = True
encoding = autodetect
# Comma separated list of file extensions to lint.

# NB: This config will only apply in the root folder.
sql_file_exts = .sql,.sql.j2,.dml,.ddl

[sqlfluff:indentation]
indented_joins = False
indented_using_on = false
template_blocks_indent = True

[sqlfluff:templater]
unwrap_wrapped_queries = True

[sqlfluff:templater:dbt]
apply_dbt_builtins = True

# Some rules can be configured directly from the config common to other rules.
[sqlfluff:rules]
tab_space_size = 4
max_line_length = 110
indent_unit = tab
comma_style = trailing
allow_scalar = False
single_table_references = consistent
unquoted_identifiers_policy = all

# Some rules have their own specific config.
[sqlfluff:rules:L007]  # Keywords
operator_new_lines = after

[sqlfluff:rules:L010]  # Keywords
capitalisation_policy = lower

[sqlfluff:rules:L012]  # Aliasing
aliasing = explicit

[sqlfluff:rules:L014]  # Unquoted identifiers
extended_capitalisation_policy = lower

[sqlfluff:rules:L016]
ignore_comment_lines = False

[sqlfluff:rules:L026]
force_enable = False

[sqlfluff:rules:L028]
force_enable = True

[sqlfluff:rules:L029]  # Keyword identifiers
unquoted_identifiers_policy = aliases

[sqlfluff:rules:L030]  # Function names
capitalisation_policy = lower

[sqlfluff:rules:L038]
select_clause_trailing_comma = forbid

[sqlfluff:rules:L040]  # Null & Boolean Literals
capitalisation_policy = lower
```

### PR DESCRIPTION
**Pull request by tunetheweb**
### Brief summary of the change made

Fixes #2375

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by tunetheweb** [comment]
Think we need a test case for this @jpy-git ? I admit it could regress but don't feel it's worth while adding a test case for every word.

**Review by jpy-git — APPROVED** [review]
@tunetheweb Nice, I checked and COLUMN has been in unreserved for ANSI for ~2 years so I'm comfortable that making this change shouldn't introduce new issues 👍 LGTM 🚀 ✨

**Comment by jpy-git** [comment]
> Think we need a test case for this @jpy-git ? I admit it could regress but don't feel it's worth while adding a test case for every word.

@tunetheweb I think we're fine here, we're just matching ANSI precedent and we'd see if any other test cases fail.

Would you also be able to open a similar PR for making `TABLE` unreserved in Postgres to close #2306 as well please? It's the same motivation so we should be fine 😄

**Comment by tunetheweb** [comment]
> Would you also be able to open a similar PR for making `TABLE` unreserved in Postgres to close #2306 as well please? It's the same motivation so we should be fine 😄

https://github.com/sqlfluff/sqlfluff/pull/2377

**Pull request merged**
