### PR TITLE
Enable setting a target of a dbt profile

### PR DESCRIPTION
**Pull request by yu-iskw**
### Brief summary of the change made

We are not able to specify a target of a dbt profile.

### Are there any other side effects of this change that we should be aware of?
I don't think we should be aware of anything.

### Pull Request checklist
- [ ] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by jpy-git** [comment]
@yu-iskw you need to run black to format your code. 

Would recommend installing the pre-commit hook as described [here](https://github.com/sqlfluff/sqlfluff/blob/main/CONTRIBUTING.md#pre-commit-config) as it takes care of the checks for you 😄

**Comment by jpy-git** [comment]
@NiallRees will let you take a look at this one in case there's any overlap with the work you're doing in #2230  😄

**Comment by tunetheweb** [comment]
Also does this "fix #2235"? If so can we add that in the initial comment so it's auto closed when this is merged?

**Comment by hugohjerten** [comment]
Looking forward to this!! 😄 🙌

**Comment by NiallRees** [comment]
Hi @yu-iskw! Would love to get this merged - it looks as though there are some conflicts in templater.py. Once addressed I'll QA this and then get it merged!

**Comment by yu-iskw** [comment]
@NiallRees I have resolved the conflicts by rebasing on the `main` branch. Please take a look at it again.

**Review by barrywhart — APPROVED** [review]
Looks good!

In the future, it would be cool if you could avoid force pushing to your branch after the initial review. It makes it harder for reviewers to tell what changed, when. On this project, we are 👍 to use `git merge` as needed (rather than `git rebase`).

**Review by barrywhart — CHANGES_REQUESTED** [review]
You still need to run `black` on your code. I'm seeing this output in the failed linting check:
```
./plugins/sqlfluff-templater-dbt/test/templater_test.py:49:14: BLK100 Black would make changes.
```

**Review by jpy-git — APPROVED** [review]
Re-approving after fixing black formatting

**Comment by jpy-git** [comment]
@barrywhart feel free to merge this in if you're happy with it 👍

**Pull request merged**
