### PR TITLE
Fix Athena Partitioned By format for iceberg tables

### LINKED ISSUE #5398: Athena create table for iceberg with partitoned by fails
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

The SQL lint for a create table with AThena and iceberg fails

According to the documentation a create table for iceberg is as following:

https://docs.aws.amazon.com/athena/latest/ug/querying-iceberg-creating-tables.html

`CREATE TABLE iceberg_table (id bigint, data string, category string)
  PARTITIONED BY (category))
  LOCATION 's3://DOC-EXAMPLE-BUCKET/your-folder/'
  TBLPROPERTIES ( 'table_type' = 'ICEBERG' )`
  
 When running lint this fails as the PARTIONED BY isn't recognized by the parser.
 
 `L:  3 | P:   1 |  PRS | Line 26, Position 1: Found unparsable section:
                        | "PARTITIONED BY (category)\nLOCATION 's..."`

### Expected Behaviour

Parsing it correctly

### Observed Behaviour

 `L:  3 | P:   1 |  PRS | Line 26, Position 1: Found unparsable section:
                        | "PARTITIONED BY (category)\nLOCATION 's..."

### How to reproduce

Use the example and run sqlfluff lint --dialect athena test.sql

### Dialect

Athena

### Version

sqlfluff, version 2.3.5

### Configuration

[sqlfluff]
max_line_length = 100
templater = python

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by jverhoeks**
### Brief summary of the change made
fixes #5398 

The parser for create table expects a ColumnDefinitionSegment at the PARTITIONED BY statement. This is expecting <fieldname> <type>, but according the documentation: https://docs.aws.amazon.com/athena/latest/ug/querying-iceberg-creating-tables.html. This should be just <fieldname>

Example:

```
CREATE TABLE iceberg_table (id bigint, data string, category string) 
PARTITIONED BY (category)) LOCATION 's3://DOC-EXAMPLE-BUCKET/your-folder/' 
TBLPROPERTIES ( 'table_type' = 'ICEBERG' )
```

Updated the parser to NakedIdentifierSegment to accept the fieldname without quotes

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).

- Added appropriate documentation for the change.

- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by WittierDinosaur — APPROVED** [review]
LGTM

**Review by WittierDinosaur — DISMISSED** [review]
You need to generate the new test yml, please run `python3 test/generate_parse_fixture_yml.py --dialect=athena`

**Comment by jverhoeks** [comment]
The fix seems to be more complicated. For external tables the partioned by does require a <fieldname> <fieldtype> while for the create table not. I'll work on an updated pr.

**Comment by WittierDinosaur** [comment]
Incase it makes this easier, our general philosophy is - make it parse all valid SQL. We're less concerned about invalid combinations successfully parsing

**Review by alanmcruickshank — APPROVED** [review]
I've brought this up to date and passing.

**Pull request merged**
