### PR TITLE
BigQuery: Allow keywords in column reference components

### LINKED ISSUE #1981: Error: "pop from an empty set"
## Expected Behaviour

No runtime error occurs

## Observed Behaviour

Runtime error

```default
CRITICAL   [L054] Applying rule L054 threw an Exception: 'pop from an empty set' 
Traceback (most recent call last):
  File "/opt/conda/envs/py3/lib/python3.8/site-packages/sqlfluff/core/rules/base.py", line 324, in crawl
    res = self._eval(
  File "/opt/conda/envs/py3/lib/python3.8/site-packages/sqlfluff/rules/L054.py", line 112, in _eval
    column_reference_category_set.pop()
KeyError: 'pop from an empty set'
== [/dataplatform/google/runtime/modules/CommonDataModel/bigquery-views/cdm_processing.FctEnergyAppStatusUpdateProcessing.sql] FAIL
L:   7 | P:   1 | L054 | Unexpected exception: 'pop from an empty set'; Could you
                       | open an issue at
                       | https://github.com/sqlfluff/sqlfluff/issues ? You can
                       | ignore this exception for now, by adding '--noqa: L054'
                       | at the end of line 7
L:  17 | P:   1 | L054 | Unexpected exception: 'pop from an empty set'; Could you
                       | open an issue at
                       | https://github.com/sqlfluff/sqlfluff/issues ? You can
                       | ignore this exception for now, by adding '--noqa: L054'
                       | at the end of line 17
L:  27 | P:   1 | L054 | Unexpected exception: 'pop from an empty set'; Could you
                       | open an issue at
                       | https://github.com/sqlfluff/sqlfluff/issues ? You can
                       | ignore this exception for now, by adding '--noqa: L054'
                       | at the end of line 27
```

## Steps to Reproduce

Here is the content of the file referred to in the error message (cdm_processing.FctEnergyAppStatusUpdateProcessing.sql):

```sql
/* jscpd:ignore-start */
SELECT
    t.body.application.id AS ApplicationId,
    t.body.cashbackStatus.electricity.current.status AS ElectricityCashBackStatus, --noqa
    t.body.cashbackStatus.gas.current.status AS GasCashBackStatus --noqa
FROM `${datalake_project_id}.${name_prefix_sans_dashes}_event_service_presentation.applicationStatusUpdate_1_229_v2` AS t
GROUP BY  --noqa: PRS
    t.body.application.id,
    t.body.cashbackStatus.electricity.current.status, --noqa
    t.body.cashbackStatus.gas.current.status  --noqa
UNION ALL
SELECT
    t.body.application.id AS ApplicationId,
    t.body.cashbackStatus.electricity.current.status AS ElectricityCashBackStatus, --noqa
    t.body.cashbackStatus.gas.current.status AS GasCashBackStatus --noqa
FROM `${datalake_project_id}.${name_prefix_sans_dashes}_event_service_presentation.applicationStatusUpdate_3_296_v2` AS t
GROUP BY  --noqa: PRS
    t.body.application.id,
    t.body.cashbackStatus.electricity.current.status, --noqa
    t.body.cashbackStatus.gas.current.status  --noqa
UNION ALL
SELECT
    t.body.application.id AS ApplicationId,
    t.body.cashbackStatus.electricity.current.status AS ElectricityCashBackStatus, --noqa
    t.body.cashbackStatus.gas.current.status AS GasCashBackStatus --noqa
FROM `${datalake_project_id}.${name_prefix_sans_dashes}_event_service_presentation.applicationStatusUpdate_9_229_v2` AS t
GROUP BY  --noqa: PRS
    t.body.application.id,
    t.body.cashbackStatus.electricity.current.status,  --noqa
    t.body.cashbackStatus.gas.current.status   --noqa
/* jscpd:ignore-end */

```
Note that the templating used here is terraform templating (https://www.terraform.io/docs/language/functions/templatefile.html)

## Dialect
bigquery 

## Version
Include the output of `sqlfluff --version` along with your Python version

## Configuration
Not using a config file however we're doing this:

```
sqlfluff lint --dialect bigquery --exclude-rules L016,L031,L014
```

### PR DESCRIPTION
**Pull request by tunetheweb**
### Brief summary of the change made
Fixes #1981 

This is valid BigQuery even though `current` is a keyword:

```sql
-- current is a reserved word but keywords are allowed as part of a nested object name
SELECT
  table1.current.column,
  table1.object.current.column,
  table1.object.nested.current.column,
FROM
  table1
```

Docs: https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical

> A reserved keyword must be a quoted identifier if it is a standalone keyword or the first component of a path expression. It may be unquoted as the second or later component of a path expression.

### Are there any other side effects of this change that we should be aware of?
Only handles Column References. There would be more places where this should be implemented but think this is the main one.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `python test/generate_parse_fixture_yml.py` or by running `tox` locally).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by WittierDinosaur** [comment]
@tunetheweb I don't think this should close the linked issue. It fixes the grammar, that allows the rule to work. The bigger issue here though, is that it isn't raising a parsing error

**Comment by tunetheweb** [comment]
It is raising the parsing error though. The original SQL has lots of ` --noqa` comments which is hiding the parsing error. Remove those and the parsing error is clear.

Will add an extra check to L054 to handle the error better when user does this.

**Comment by WittierDinosaur** [comment]
Oh, fantastic, LGTM then! Was worried that the refactoring had introduced a bug

**Review by WittierDinosaur — APPROVED** [review]

**Comment by jpy-git** [comment]
@tunetheweb congrats you just made the 1000th PR 🥳 

image

**Pull request merged**
