### PR TITLE
Postgres alter policy

### LINKED ISSUE #5075: Unable to parse ALTER POLICY
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

```sql
ALTER POLICY sales_rep_is_self ON invoices
  WITH CHECK (sales_rep = CURRENT_USER AND CURRENT_USER IN (
    SELECT name FROM allowed_users
  ));
```

### Expected Behaviour

Should parse `ALTER POLICY`

### Observed Behaviour

`Found unparsable section: 'ALTER POLICY`

### How to reproduce

Run `sqlfluff parse` with the example query.

### Dialect

postgres

### Version

2.2.0

### Configuration

Default

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Fullcure3**
### Brief summary of the change made
Fixes #5075 

### Are there any other side effects of this change that we should be aware of?
No side effects that I'm aware of.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by greg-finley** [comment]
Hey, looks like a great start! However, could you please add some tests? Here's an example: https://github.com/sqlfluff/sqlfluff/pull/2021

https://github.com/sqlfluff/sqlfluff/wiki/Contributing-Dialect-Changes

**Comment by Fullcure3** [comment]
Thank you for the feedback! This is my first contribution on GitHub so I'm still learning the ropes. I'll review the links and add the tests as soon as I can.

**Comment by Fullcure3** [comment]
@greg-finley Addressed the feedback for test cases. Should be good to merge!

**Review by greg-finley — APPROVED** [review]
Great job! 🙌

**Pull request merged**
