### PR TITLE
Exasol: New consumer group params and unreserved keywords (7.1+)

### PR DESCRIPTION
**Pull request by sti0**
### Brief summary of the change made

This extends the `CREATE / ALTER CONSUMER GROUP` syntax introduced in Exasol 7.1. Additonally I added some new unreserved keywords introduced in 7.1 

### Are there any other side effects of this change that we should be aware of?
Nope

### Pull Request checklist
- [ ] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by jpy-git — APPROVED** [review]
Looks good! 🚀 ✨ 

@tunetheweb I'll hold off merging until after you've done the release (or free to merge in if you've got time to include it) 👍

**Comment by sti0** [comment]
We may could schedule this for the next release. I'm preparing some more PR for the features introduced in 7.1

**Comment by tunetheweb** [comment]
Happy to include in 0.11.0. And can give you till tomorrow am if you want to see what else you can add? But am keen to get it out then as a lot in this already so don’t want to keep delaying it indefinitely. But no really difference between Sunday night and Monday morning so happy to wait one more evening if you want.

**Comment by sti0** [comment]
Ok, lets merge this. Maybe I add two more today. We can package the other ones to come in the next release then.

**Pull request merged**
