### PR TITLE
Allow jinja raw tags

### LINKED ISSUE #681: dbt templater cannot handle "raw" jinja tags
## Expected Behaviour

`sqlfluff lint` on SQL files with `{% raw %}` Jinja tags should be able to be linted and fixed.

## Observed Behaviour

> KeyError: 'raw_end' 

## Steps to Reproduce

-- table_ref.sql
```sql
select 1
from foo
```

-- test_raw.sql
```sql
select
    table_ref.field1,
    {% raw %}
    table_ref.field2,
    table_ref.field3
    {% endraw %}
from
    {{ref('table_ref')}} as table_ref
```

## Version
python
> Python 3.8.2
dbt --version
> installed version: 0.18.1
> latest version: 0.18.1
> 
> Up to date!

sqlfluff -- version
> sqlfluff, version 0.4.0a3

## Configuration
```
[sqlfluff]
templater = dbt
exclude_rules = L003,L013,L022,L027,L009,L031

[sqlfluff:templater:jinja:context]
target = 'dev'

[sqlfluff:indentation]
indented_joins = True

[sqlfluff:rules]
max_line_length = 115

[sqlfluff:rules:L010]
capitalisation_policy = lower
```
.sqlfluffignore
```
target/
dbt_modules/
macros/
```

### PR DESCRIPTION
**Pull request by pwildenhain**
Fixes #681 (hopefully 🤞🏻 )

### CODE REVIEW

**Comment by pwildenhain** [comment]
@cnolanminich Would you mind testing against this PR to ensure it works for your use case?

**Comment by cnolanminich** [comment]
installed from this branch, but still getting the `keyError: rawend` error.

Part of the reason I have the `{% raw %}` tag is because I have  `{%` in the wildcard searches and so `dbt compile` chokes on it. I'm wondering if that might be related to the continued error?

example:

```sql
{% raw %}
        and lower(note_text.note_text) not like '%daycare: {%'
        and lower(note_text.note_text) not like '%grade/ school name:  {%'
        and lower(note_text.note_text) not like '%social history:  {%'
        {% endraw %}
```

**Comment by pwildenhain** [comment]
Interesting! Do you still get the error on the simple query you originally submitted in the issue?

**Comment by cnolanminich** [comment]
still getting the error on my simple SQL. I checked the version of the package in my `pipfile.lock` and it seems to match what's expected:

``

**Comment by alanmcruickshank** [comment]
Thanks @cnolanminich I'll take another look at this tonight. I'll use that snippet you posted in testing.

**Comment by alanmcruickshank** [comment]
@cnolanminich I've got it working for this query which aims to replicate your snippet.
```sql
SELECT
    {% raw %}
    lower(note_text) NOT LIKE '%daycare: {%'
    AND lower(note_text) NOT LIKE '%grade/ school name:  {%'
    AND lower(note_text) NOT LIKE '%social history:  {%'
    {% endraw %}
    AS foo
FROM my_table
```

Are you still getting the error with this version of the branch? If so can you paste more of the query which is triggering it?

**Comment by alanmcruickshank** [comment]
@cnolanminich I've got it working for this query which aims to replicate your snippet.
```sql
SELECT
    {% raw %}
    lower(note_text) NOT LIKE '%daycare: {%'
    AND lower(note_text) NOT LIKE '%grade/ school name:  {%'
    AND lower(note_text) NOT LIKE '%social history:  {%'
    {% endraw %}
    AS foo
FROM my_table
```

Are you still getting the error with this version of the branch? If so can you paste more of the query which is triggering it?

**Comment by cnolanminich** [comment]
works like a charm! thanks @alanmcruickshank

**Pull request merged**
