### PR TITLE
Support parallel linting with diff-quality

### LINKED ISSUE #4094: diff-qualify to take advantage of multiple processes
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

We have compared partial linting (`diff-qualify`) with a full linting (`sqlfluff lint . --processes 4`) on a dbt project with 2200+ models and full linting works faster than `diff-qualify`. More details in this thread https://getdbt.slack.com/archives/CV2KM39KR/p1668983672332239

### Use case

Looking for a faster partial linting. Parallel processing might be a good addition to `diff-qualify`.

### Dialect

snowflake

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by barrywhart**
- [ ] Re: Performance issue, confirm that linting vs diff-quality are being run on the same machine, to eliminate other possible causes

### Brief summary of the change made
Fixes #4094

### Pull Request checklist
- [ ] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by nhrebinka** [comment]
@barrywhart here are some testing steps, I hope they look reasonable

step 1:
```
>pip install diff-cover==7.2.0
Collecting diff-cover==7.2.0
  Downloading diff_cover-7.2.0-py3-none-any.whl (50 kB)
     ---------------------------------------- 50.7/50.7 kB 861.0 kB/s eta 0:00:00
Requirement already satisfied: Jinja2>=2.7.1 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from diff-cover==7.2.0) (3.1.2)
Requirement already satisfied: chardet>=3.0.0 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from diff-cover==7.2.0) (3.0.4)
Requirement already satisfied: pluggy<2,>=0.13.1 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from diff-cover==7.2.0) (1.0.0)
Requirement already satisfied: Pygments<3.0.0,>=2.9.0 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from diff-cover==7.2.0) (2.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from Jinja2>=2.7.1->diff-cover==7.2.0) (2.0.1)
Installing collected packages: diff-cover
  Attempting uninstall: diff-cover
    Found existing installation: diff-cover 6.4.4
    Uninstalling diff-cover-6.4.4:
      Successfully uninstalled diff-cover-6.4.4
Successfully installed diff-cover-7.2.0
```
step 2:
```
>pip install git+https://github.com/barrywhart/sqlfluff.git@bhart-issue_4094_diff_quality_multiple_processes2
Collecting git+https://github.com/barrywhart/sqlfluff.git@bhart-issue_4094_diff_quality_multiple_processes2
  Cloning https://github.com/barrywhart/sqlfluff.git (to revision bhart-issue_4094_diff_quality_multiple_processes2) to c:\users\w500239\appdata\local\temp\pip-req-build-8b77siru
  Running command git clone --filter=blob:none --quiet https://github.com/barrywhart/sqlfluff.git 'C:\Users\w500239\AppData\Local\Temp\pip-req-build-8b77siru'
  Running command git checkout -b bhart-issue_4094_diff_quality_multiple_processes2 --track origin/bhart-issue_4094_diff_quality_multiple_processes2
  Branch 'bhart-issue_4094_diff_quality_multiple_processes2' set up to track remote branch 'bhart-issue_4094_diff_quality_multiple_processes2' from 'origin'.
  Switched to a new branch 'bhart-issue_4094_diff_quality_multiple_processes2'
  Resolved https://github.com/barrywhart/sqlfluff.git to commit f927a9a78f08ab917ab3ced194b28f8abeea1492
  Preparing metadata (setup.py) ... done
Requirement already satisfied: appdirs in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.2) (1.4.4)
Requirement already satisfied: chardet in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.2) (3.0.4)
Requirement already satisfied: click in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.2) (8.0.3)
Requirement already satisfied: colorama>=0.3 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.2) (0.4.3)
Requirement already satisfied: diff-cover>=2.5.0 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.2) (7.2.0)
Requirement already satisfied: Jinja2 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.2) (3.1.2)
Requirement already satisfied: pathspec in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.2) (0.9.0)
Requirement already satisfied: pytest in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.2) (6.2.5)
Requirement already satisfied: pyyaml>=5.1 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.2) (6.0)
Requirement already satisfied: regex in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.2) (2022.10.31)
Requirement already satisfied: tblib in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.2) (1.7.0)
Requirement already satisfied: toml in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.2) (0.10.2)
Requirement already satisfied: tqdm in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.2) (4.62.3)
Requirement already satisfied: typing_extensions in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from sqlfluff==1.4.2) (4.4.0)
Requirement already satisfied: Pygments<3.0.0,>=2.9.0 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from diff-cover>=2.5.0->sqlfluff==1.4.2) (2.9.0)
Requirement already satisfied: pluggy<2,>=0.13.1 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from diff-cover>=2.5.0->sqlfluff==1.4.2) (1.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from Jinja2->sqlfluff==1.4.2) (2.0.1)
Requirement already satisfied: attrs>=19.2.0 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from pytest->sqlfluff==1.4.2) (20.3.0)
Requirement already satisfied: iniconfig in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from pytest->sqlfluff==1.4.2) (1.1.1)
Requirement already satisfied: atomicwrites>=1.0 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from pytest->sqlfluff==1.4.2) (1.4.0)
Requirement already satisfied: packaging in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from pytest->sqlfluff==1.4.2) (20.9)
Requirement already satisfied: py>=1.8.2 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from pytest->sqlfluff==1.4.2) (1.10.0)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\w500239\appdata\local\programs\python\python38\lib\site-packages (from packaging->pytest->sqlfluff==1.4.2) (2.4.7)
```
step 3
```
>diff-quality --violations sqlfluff --compare-branch origin/dev
```
^ before the change it took about 30 minutes on ~50 files on Snowflake & on a large project of 2.5K+ models
after the change I dont see a big difference but I cannot tell if it is running multithread or not.. 🤷‍♀️ 
 I have seen a lot of this before and after the change
```
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Traceback (most recent call last):
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\site-packages\snowflake\connector\vendored\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\site-packages\snowflake\connector\vendored\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\site-packages\snowflake\connector\vendored\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\site-packages\snowflake\connector\vendored\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\site-packages\snowflake\connector\vendored\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\site-packages\snowflake\connector\vendored\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\site-packages\snowflake\connector\vendored\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\site-packages\snowflake\connector\vendored\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\site-packages\snowflake\connector\vendored\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\site-packages\snowflake\connector\vendored\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\w500239\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
snowflake.connector.vendored.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
full lint (`sqlfluff lint .` and any variations) never drops a connection for some reason

**Comment by barrywhart** [comment]
@nhrebinka: I saw your note in Slack about `diff-quality` hanging. These are some thoughts I had related to next steps on that.

Maybe we can make some small changes to try and understand what's happening. One idea:
* IIUC, it's hanging with `diff-quality` and parallelism enabled
* Test if `diff-quality` works correctly _without_ parallelism
* Test running `sqlfluff lint` (with parallelism enabled) directly on the same files. Does that hang?

The above experiment may help determine if the issue is with parallelism itself, or something more specific to the `diff-quality` integration.

It may also be helpful to:
* Get logging set up in the worker processes
* Try and determine if there's a "trigger" for it hanging, e.g.: A particular file, a particular number of files, etc.

We may also want to create a branch that combines this PR and #3976, then test with that. That other PR is still in development, but it uses what we hope is a much nicer dbt integration with a lot of historic cruft removed.

**Comment by nhrebinka** [comment]
@barrywhart I am attaching the log from the direct `sqflfuff lint [list of files]` on this branch. It did drop a connection a few times, trying to figure out if it was my VPN or not. (trying again and will let you know).
[sqlfluff-lint-list-of-files-on-PR4132.txt](https://github.com/sqlfluff/sqlfluff/files/10147656/sqlfluff-lint-list-of-files-on-PR4132.txt)
`diff-quality` (v.7.2.0) was working for over 3 hours on the same list of files and it did not finish, example log msg attaches as an image
image

I will be out of town till Tuesday afternoon, will pick this up when I return. If we can figure it out, it will make a lot of folks happy.

**Comment by barrywhart** [comment]
It'd be interesting to know if the subprocesses in diff-quality are stuck, crashed, or just really really slow.

**Comment by nhrebinka** [comment]
my impression is that they are really slow or going in the loops (I have to prove it)

**Comment by barrywhart** [comment]
Maybe look at "top" or "htop" output to see if it's CPU bound or not. We'll set up subprocess logging next week to get more info.

**Comment by nhrebinka** [comment]
one more test!
`sqlfluff` vs `diff-quality`
====
TEST 1
====
1.  ` (git --no-pager diff --name-only origin/dev..head  -- "*.sql") -join ' '`
2. `sqlfluff lint xx` where xx is a list of files returned with the previous command
run completed within 24 minutes with 8 processes and it linted 17 files
====
TEST 2
====
1. `diff-quality --violations sqlfluff --compare-branch origin/dev` with `logging.DEBUG` in `diff_quality_tool.py`
this ran for 2 hours and 20 minutes and finished with an error:
```
Diff Quality
Quality Report: sqlfluff
Diff: origin/dev...HEAD, staged and unstaged changes
-------------
models/marts/health/pathways/1-stage/core_balances_stage__health__pathways.sql (100%)
models/marts/health/pathways/1-stage/stg_participant_expense_class_count_pivot_stage__health__pathways.sql (100%)
models/marts/health/pathways/1-stage/stg_participant_expense_class_pivot_stage__health__pathways.sql (100%)
models/marts/health/pathways/2-output/pathways_output__health__pathways.sql (100%)
models/prep/2-output/health/pathways_opt/dim_administrator__prep__health__pathways_opt.sql (100%)
models/prep/2-output/health/pathways_opt/dim_contribution_profile__prep__health__pathways_opt.sql (100%)
models/prep/2-output/health/pathways_opt/dim_employer__prep__health__pathways_opt.sql (100%)
models/prep/2-output/health/pathways_opt/dim_participant__prep__health__pathways_opt.sql (100%)
models/prep/2-output/health/pathways_opt/dim_plan__prep__health__pathways_opt.sql (100%)
models/prep/2-output/health/pathways_opt/dim_plan_account__prep__health__pathways_opt.sql (100%)
models/prep/2-output/health/pathways_opt/dim_plan_account_transaction_classification__prep__health__pathways_opt.sql (100%)
models/prep/2-output/health/pathways_opt/dim_plan_account_transaction_description__prep__health__pathways_opt.sql (100%)
models/prep/2-output/health/pathways_opt/dim_plan_account_transaction_profile__prep__health__pathways_opt.sql (100%)
models/prep/2-output/health/pathways_opt/fact_billable_election__prep__health__pathways_opt.sql (100%)
models/prep/2-output/health/pathways_opt/fact_enrollment__prep__health__pathways_opt.sql (100%)
models/prep/2-output/health/pathways_opt/fact_plan_account_snapshot__prep__health__pathways_opt.sql (100%)
models/prep/2-output/health/pathways_opt/fact_plan_account_transaction__prep__health__pathways_opt.sql (100%)
-------------
Total:   465 lines
Violations: 0 lines
% Quality: 100%
-------------
Attempting to acquire lock 2827299785552 on C:\Users\w500239\AppData\Local\Snowflake\Caches\ocsp_cache.lock
Lock 2827299785552 acquired on C:\Users\w500239\AppData\Local\Snowflake\Caches\ocsp_cache.lock
Attempting to release lock 2827299785552 on C:\Users\w500239\AppData\Local\Snowflake\Caches\ocsp_cache.lock
Lock 2827299785552 released on C:\Users\w500239\AppData\Local\Snowflake\Caches\ocsp_cache.lock
```

**Comment by barrywhart** [comment]
Testing on large SQL projects shows that the direct (Python) integration does not perform well for some reason. Closing this PR in favor of #4148, which integrates by shelling out to command-line SQLFluff instead.

**Pull request closed without merging**
