### PR TITLE
Bump version in gettingstarted.rst via the release script

### PR DESCRIPTION
**Pull request by greg-finley**
https://github.com/sqlfluff/sqlfluff/pull/3639#discussion_r925623669

### CODE REVIEW

**Review by tunetheweb — APPROVED** [review]
LGTM!

Thanks again for making our life easier! Automation for the win!

**Comment by greg-finley** [comment]
I wonder why `codecov/project` isn't running?

**Comment by tunetheweb** [comment]
Sometimes gets stuck. It doesn’t “run” so much as get kicked off by codecov gets all the inisividual test run data. If it misses one due to a network glitch it waits for ever. Kicked off the tests again so it hopefully will find whatever it’s missing.


Plus codecov sometimes just stalls 🤷‍♂️ In which case will try again later.

**Comment by tunetheweb** [comment]
And there it is. So guess it did miss one and got it now! Now just need to wait for other jobs to finish!

**Pull request merged**
