### PR TITLE
Snowflake revoke

### PR DESCRIPTION
**Pull request by mhaley-miovision**
Here is the revoke statement as promised. It came together very easily since alot of the grant statement utilities could be re-used, which is nice.

### CODE REVIEW

**Comment by NiallRees** [comment]
Hey @mhaley-miovision looks like there have been some merge conflicts introduced after I merged https://github.com/sqlfluff/sqlfluff/pull/683, would you mind addressing those and then I can review this and get it merged in!

**Comment by mhaley-miovision** [comment]
@NiallRees changes merged again. If you have time it would be nice to get some eyes on this. I think this is the last PR in the set I was working on to need merging. Once this is in we can start to use this tool!

**Comment by NiallRees** [comment]
Looks like there are a few changes to the parsing logic which need to be updated in the `.yml` fixtures! More info here https://github.com/sqlfluff/sqlfluff/blob/master/test/fixtures/parser/README.md

**Comment by mhaley-miovision** [comment]
Updated the yml, let's see how it goes now.

**Review by NiallRees — APPROVED** [review]
It looks like there's a bit of DRYing up that could be done [around here](https://github.com/sqlfluff/sqlfluff/pull/700/files#diff-e07ae5ab00e7f519401a3251b192139d2da4ebf08fd1d7403b795472bff4f29aR1874-R1883) if you feel like it, sorry I missed it in my previous review. Otherwise this looks good! Thanks @mhaley-miovision !

**Comment by mhaley-miovision** [comment]
Hey @NiallRees can we cut a new incremental release like https://github.com/sqlfluff/sqlfluff/releases/tag/0.4.0a3 so I can test out these changes on our project?

**Pull request merged**
