### PR TITLE
Initial support for Starrocks dialect

### PR DESCRIPTION
**Pull request by maver1ck**
This is initial support of Starrocks dialect in sqlfluff.

Implemented:
- Inheritance from MySQL dialect
- CREATE TABLE 
- ROUTINE LOAD operations

### Brief summary of the change made

Fixes: https://github.com/sqlfluff/sqlfluff/issues/6412

### Are there any other side effects of this change that we should be aware of?

No

### Pull Request checklist
- [ ] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by maver1ck** [comment]
I know tests are needed.
What else can be improved ?

**Comment by zhangruchubaba** [comment]
> This is draft for support of Starrocks dialect in sqlfluff.
> 
> ### Brief summary of the change made
> Fixes: #6412
> 
> ### Are there any other side effects of this change that we should be aware of?
> No
> 
> ### Pull Request checklist
> * [ ]  Please confirm you have completed any of the necessary steps below.
> * Included test cases to demonstrate any code changes, which may be one or more of the following:
>   
>   * `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
>   * `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
>   * Full autofix test cases in `test/fixtures/linter/autofix`.
>   * Other.
> * Added appropriate documentation for the change.
> * Created GitHub issues for any relevant followup/future enhancements if appropriate.

Hi man ,after merging your code, can sqlfluff parse field-level data lineage for CREATE TABLE AS SELECT and INSERT INTO TABLE AS SELECT in StarRocks?

**Comment by WittierDinosaur** [comment]
This is a good start - you're missing a few references:
- .github/labeler.yml
- pyproject.yml
- src/sqlfluff/core/dialects/__init__.py
Looks like you're also failing some linting tests

**Comment by maver1ck** [comment]
@WittierDinosaur 
I added missing entries and fixed linting issues.

**Review by WittierDinosaur — APPROVED** [review]
Seems like a good first version. LGTM

**Comment by WittierDinosaur** [comment]
Ah, looks like you need to run black

**Comment by maver1ck** [comment]
@WittierDinosaur 
Rebased and checked with pre-commit.

**Comment by maver1ck** [comment]
@greg-finley fixed missing CLI test and rebased

**Pull request merged**
