### PR TITLE
Allow warnings for specific rules

### LINKED ISSUE #201: Add severity level for lint violations
Most linters tag each violation with a severity level. Text editor integrations have settings to surface violations with severity above one or another level. Fluff should have these levels, even if it as much as a warning for a violation and an error for a parse failure! 

This could be surfaced to the user in the lint output (as text and/or color?) and in the json/yaml output.

### PR DESCRIPTION
**Pull request by alanmcruickshank**
This resolves #201 (THE OLDEST OUTSTANDING ISSUE 🚀 ) - only took over 2 yrs.

This delivers almost exactly against the spec outlined in that original issue.

Rules can be configured as warnings, in which case they're displayed as such, but don't fail the file.

### CODE REVIEW

**Comment by tunetheweb** [comment]
Change itself looks good. However it feels a bit hidden away with just a comment in the default config file. Could we add some more documentation to https://docs.sqlfluff.com/en/stable/configuration.html?

**Comment by alanmcruickshank** [comment]
@tunetheweb - what do you reckon the documentation I've put in? It's fairly brief but I think to the point.

**Comment by tunetheweb** [comment]
Looks great to me!

**Review by tunetheweb — APPROVED** [review]

**Comment by nolanbconaway** [comment]
Heck yeah!!!

**Pull request merged**
