### PR TITLE
Support wildcards in triggers

### LINKED ISSUE #1831: Postgres - can't parse table.*
Specifically in the context of an expression in a trigger statement. 

```
CREATE TRIGGER log_update
    AFTER UPDATE ON accounts
    FOR EACH ROW
    WHEN (OLD.* IS DISTINCT FROM NEW.*)
    EXECUTE FUNCTION log_account_update();
```

This probably wants adding to ANSI - though I can only be certain of Postgres.

### PR DESCRIPTION
**Pull request by tunetheweb**
### Brief summary of the change made

Fixes #1831 

### Are there any other side effects of this change that we should be aware of?
Causes a number of other Yamls to (correctly!) now classify `*` as wildcard expression so looks like more changes than it really is.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by barrywhart** [comment]
Several L047 tests are failing.

**Comment by tunetheweb** [comment]
> Several L047 tests are failing.

Yeah, gonna go with a different, less drastic, approach here. As fixing L047 to handle this new wildcard syntax looks a bit more difficult.

**Comment by barrywhart** [comment]
I see that this change makes the parse tree deeper. 👍🏽

**Comment by tunetheweb** [comment]
> I see that this change makes the parse tree deeper. 👍🏽

Not anymore! This should all work now.

**Comment by tunetheweb** [comment]
Good to review now @barrywhart

**Pull request merged**
