### PR TITLE
Run examples as part of test suite

### LINKED ISSUE #593: Test the API examples as a part of test suite
Originally recommended by @alanmcruickshank  in https://github.com/sqlfluff/sqlfluff/pull/580#pullrequestreview-539203726

### PR DESCRIPTION
**Pull request by alanmcruickshank**
Fixes #593

### CODE REVIEW

**Review by dmateusp — APPROVED** [review]
call the 🚒 @alanmcruickshank is on 🔥

**Comment by barrywhart** [comment]
@dmateusp: OMG, I said the exact same thing one second before seeing your comment.

🔥🔥🔥🔥🔥🔥
💯💯💯💯
Somebody get @alanmcruickshank another keg of ☕️☕️☕️. Soon, there'll be no issues left for the rest of us!

**Review by barrywhart — APPROVED** [review]
:shipit:

**Comment by alanmcruickshank** [comment]
> call the 🚒 @alanmcruickshank is on 🔥

If we're shipping tomorrow - best that we ship the good sh*t

**Pull request merged**
