### PR TITLE
Refactor PG segments to reuse new common segments

### LINKED ISSUE #3557: [postgres] Index USING → false negative
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Creating an index using a specific index method (which is not a function) gets mis-interpreted as a function name.

### Expected Behaviour

No error

### Observed Behaviour

```
sqlfluff lint --nocolor --verbose --dialect postgres 2022-07-05.index-using.sql
==== sqlfluff ====
sqlfluff:                1.1.0 python:                 3.8.10
implementation:        cpython verbosity:                   1
dialect:              postgres templater:               jinja
rules:                                all
==== readout ====

=== [ path: 2022-07-05.index-using.sql ] ===

== [2022-07-05.index-using.sql] FAIL                                                                                                                                              
L:   1 | P:  47 | L017 | Function name not immediately followed by parenthesis.
==== summary ====
violations:        1 status:         FAIL
All Finished!
```

### How to reproduce

Use the following file `2022-07-05.index-using.sql`:
```sql
CREATE INDEX my_json_idx ON my_table USING GIN (metrics_ jsonb_path_ops);
```

### Dialect

postgres

### Version

```
sqlfluff:                1.1.0 python:                 3.8.10
implementation:        cpython verbosity:                   1
dialect:              postgres templater:               jinja
rules:                                all
```

### Configuration

defaults

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by james-johnston-thumbtack**
A previous commit added some useful new reusable segments based on the
upstream PG grammar.  These were initially used only for EXCLUDE
constraints.  However, many of the segments are more broadly applicable.

This commit spreads their use, as well as makes improvements to better
reflect current PG 15 grammar.

This commit should fix #3557, as well as undoubtedly other issues.  (I didn't conduct a more exhaustive search for other issues).

- The new RelationOptionsSegment was used in place of ad-hoc
  sequences in the following locations, wherever the "reloptions" could
  be found:

  CREATE TABLE
  ALTER TABLE: SET / RESET (both column & table level)
  CREATE [MATERIALIZED] VIEW
  CREATE INDEX

- Consistently use TablespaceReferenceSegment.

- Support new NULLS [NOT] DISTINCT on ColumnConstraintSegment,
  TableConstraintSegment, and CREATE INDEX.

- Support passing index parameters to UNIQUE and PRIMARY KEY column
  constraints.

- Remove "OR REPLACE" grammar from CREATE INDEX.  PG doesn't support
  this; it's not part of its grammar.

- Reuse IndexElementSegment for index fields + INCLUDE segment.  Also
  reuse IndexAccessMethodSegment.

- This thoroughly fixes the limitation where we didn't support parsing
  opclasses named NULLS: https://github.com/sqlfluff/sqlfluff/pull/4356
  We can in fact use this to effectively do the needed lookahead:

      Ref(..., exclude=Sequence("NULLS", OneOf("FIRST", "LAST")))

  The new segments introduced in the previous commit that supports
  EXCLUDE included this improvement; this commit spreads their use.

### Pull Request checklist
- [X] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by james-johnston-thumbtack** [comment]
NOTE: this PR is stacked on top of the other one.  So this one is in draft mode until the other one is merged.

**Comment by WittierDinosaur** [comment]
Merge conflicts

**Comment by james-johnston-thumbtack** [comment]
Conflicts resolved: only checksums in 2 YAML files

**Comment by james-johnston-thumbtack** [comment]
Conflicts resolved: besides checksum, there were two adjacent statements in the YAML file, but no conflicts within a single statement.

**Pull request merged**
