### PR TITLE
Change MySQL Create Statement Equals Segment to Optional

### LINKED ISSUE #3664: Mysql CREATE TABLE parse fails on COLLATE/CHARSET keyword without equal sign
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I am trying to lint some create table statements and got parsing errors when using the `COLLATE` keyword if that keyword was not followed with an equal sign.

I also tested this with the `CHARSET` keyword and I had the same parse issue.

### Expected Behaviour

I expect the parsing to work with or without the equal sign since this is legal in mysql.

### Observed Behaviour

`CREATE TABLE` statements with `CHARSET` or `COLLATE` without a trailing equals sign fail to parse.
This might apply to other constructs that are part of a `CREATE TABLE` statement.

### How to reproduce

try to lint the following using mysql dialect:

```sql

## this works
CREATE TABLE works_with_equals (
    id INT
) COLLATE=utf8_general_ci;

## this fails to parse
CREATE TABLE fails_no_equals (
    id INT
) COLLATE utf8_general_ci;

```

### Dialect

dialect: mysql

### Version

version 1.2.1

### Configuration

stock configuration

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by keyem4251**
### Brief summary of the change made

Change MySQL Create EqualsSegment to Optional.  
fixes #3664

### Pull Request checklist
- [✓] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by alanmcruickshank** [comment]
@keyem4251 - the change to the dialect looks great. Are you able to add a test to the test suite too to confirm that an example query passes?

**Comment by keyem4251** [comment]
@alanmcruickshank 
OK. In this case, do I add SQL file in test/fixtures/dialects/mysql and generate yaml file by using generate_parse_fixture_yml.py?

**Comment by barrywhart** [comment]
@keyem4251: That's correct.

**Comment by keyem4251** [comment]
Thanks!

**Comment by barrywhart** [comment]
The new test is failing. Did you generate the YAML file using the same dialect code that's in the PR?

**Comment by keyem4251** [comment]
Yes

**Comment by keyem4251** [comment]
Oh, sorry local environment is old and git pull. file hash is seems correct.

**Review by WittierDinosaur — APPROVED** [review]
LGTM

**Pull request merged**
