### PR TITLE
Add requirements_dev.txt

### LINKED ISSUE #496: Add requirements_dev.txt for formatting/linting checks
@pwildenhain fyi I just hit a minor issue with black, where my outdated version wasn't formatting all the files the same way that the `tox` environment did

what do you think about either having a `requirements_dev.txt` which specifies the version of black to use, or adding `pre-commit` ?

_Originally posted by @dmateusp in https://github.com/sqlfluff/sqlfluff/pull/486#issuecomment-713629122_

### PR DESCRIPTION
**Pull request by pwildenhain**
Closes #496 
FYI @dmateusp

### CODE REVIEW

**Review by alanmcruickshank — CHANGES_REQUESTED** [review]
These changes look great. Is it also possible to use the `requirements_dev.txt` file to replace the references currently in `tox.ini` too? I'm conscious that there are references to libraries in there too.

Unless you can think of a reason that we might keep the two distinct? 🤔

**Comment by pwildenhain** [comment]
You're right, we should keep them aligned. I _think_ I found a good solution. We make the `testenv` a little more bloated, but we get better consistency between `tox` and `venv`. I'm open to further changes though if something still doesn't sit right.

**Comment by alanmcruickshank** [comment]
I'm ok with this approach. What's the thinking on removing the version references in `requirements_dev.txt`? I thought that was part of the problem we were trying to fix?

**Comment by pwildenhain** [comment]
The problem was the while `tox` was using the most recent version of `black`, @dmateusp was not. This is why I added the `-U` (upgrade) flag to `tox.ini` and the `CONTRIBUTING.md` so that we ensure we're always working with a recent version.

I think that's cleaner than specifying minimum versions for each, but I can revert the change if you see otherwise

**Comment by alanmcruickshank** [comment]
Ahhhh, I understand. Makes sense 👍 

Can you add some comments to both the `requirements_dev.txt` and `tox.ini` to remind people of that intent. I will very likely otherwise forget, but I think the intent is sound.

**Comment by pwildenhain** [comment]
Good point, done ✔️

**Review by alanmcruickshank — APPROVED** [review]
LGTM 👍

**Pull request merged**
