### PR TITLE
Allow Redshift `IDENTITY` column `(seed, step)` to be optional

### PR DESCRIPTION
**Pull request by menzenski**
### Brief summary of the change made

Fixes https://github.com/sqlfluff/sqlfluff/issues/3429

The AWS Redshift `CREATE TABLE` [documentation](https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_TABLE_NEW.html) indicates that `(seed, step)` is required on an `IDENTITY` column:

```
CREATE [ [LOCAL ] { TEMPORARY | TEMP } ] TABLE 
[ IF NOT EXISTS ] table_name
( { column_name data_type [column_attributes] [ column_constraints ] 
  | table_constraints
  | LIKE parent_table [ { INCLUDING | EXCLUDING } DEFAULTS ] } 
  [, ... ]  )
[ BACKUP { YES | NO } ]
[table_attribute]

where column_attributes are:
  [ DEFAULT default_expr ]
  [ IDENTITY ( seed, step ) ]                           <-- this should probably be [ IDENTITY [ (seed, step) ] ] 
  [ GENERATED BY DEFAULT AS IDENTITY ( seed, step ) ]   <-- this should probably be  [ GENERATED BY DEFAULT AS IDENTITY [ ( seed, step ) ] ] 
  [ ENCODE encoding ] 
  [ DISTKEY ]
  [ SORTKEY ]
  [ COLLATE CASE_SENSITIVE | COLLATE CASE_INSENSITIVE  ]
```

However, it is not required, as shown by the official AWS examples [here](https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_TABLE_examples.html#r_CREATE_TABLE_NEW-create-a-table-with-default-identity-column):

```sql
CREATE TABLE t1(
  hist_id BIGINT IDENTITY NOT NULL, /* Cannot be overridden */
  base_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, /* Can be overridden */
  business_key varchar(10) ,
  some_field varchar(10) 
);
```

Also: thank you @tunetheweb and @mdahlman for helping guide my first contribution to this project!

### Are there any other side effects of this change that we should be aware of?

Not to my knowledge.

### Pull Request checklist

- [X] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by tunetheweb — APPROVED** [review]
This looks perfect! Assuming all tests pass, will merge and include in next release (maybe this Friday, maybe Friday after).

And hopefully now you’ve gotten over your first PR hurdle you’ll contribute again if you spot anything else that needs fixing!

**Comment by menzenski** [comment]
@tunetheweb thanks! I believe with this issue resolved we can adopt SQLFluff in our new redshift project so I will be using it a lot more in the future

**Comment by tunetheweb** [comment]
Oh did you manually generate the YAML?

There’s a script for that as looks slightly off from the generated one:
https://github.com/sqlfluff/sqlfluff/wiki/Contributing-Dialect-Changes#yml-test-fixture-files

**Comment by menzenski** [comment]
I had done it manually, then I saw the failed PR check. I've since done it the right way and have updated the PR.

**Comment by tunetheweb** [comment]
A lot quicker to use the script! 😄

**Pull request merged**
