### PR TITLE
Reposition before recursion in fixes to avoid internal error

### LINKED ISSUE #3656: Internal error on fixing L032
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

`sqlfluff fix x.sql --dialect=mysql --rules=L032` causes internal error,
where x.sql has following contents:
```
select c1.Name, c2.Name, c5.Name from city as c1
inner join city as c2 using (ID)
inner join (
  select c3.ID, c4.Name from city as c3
  inner join city as c4 using (ID)
  ) as c5
  on c1.ID = c5.ID
  limit 3;
```

This is a valid query and works fine with the world database in MySQL Example Databases (https://dev.mysql.com/doc/index-other.html)
```
mysql> select c1.Name, c2.Name, c5.Name from city as c1
    -> inner join city as c2 using (ID)
    -> inner join (
    ->   select c3.ID, c4.Name from city as c3
    ->   inner join city as c4 using (ID)
    ->   ) as c5
    ->   on c1.ID = c5.ID
    ->   limit 3;
+----------+----------+----------+
| Name     | Name     | Name     |
+----------+----------+----------+
| Kabul    | Kabul    | Kabul    |
| Qandahar | Qandahar | Qandahar |
| Herat    | Herat    | Herat    |
+----------+----------+----------+
3 rows in set (0.00 sec)
```

### Expected Behaviour

success without internal error

### Observed Behaviour

internal error occurred

```
(sqlfluff) ~/prog/python-study/sqlfluff% sqlfluff fix x.sql --dialect=mysql --rules=L032
==== finding fixable violations ====
WARNING    SEG: (<CodeSegment: (None) 'c1'>, <SymbolSegment: (None) '.'>, <CodeSegment: (None) 'ID'>), POS: None
WARNING    Unable to lint x.sql due to an internal error. Please report this as an issue with your query's contents and stacktrace below!
To hide this warning, add the failing file to .sqlfluffignore
Traceback (most recent call last):
  File "/Users/yoichi/.virtualenvs/sqlfluff/lib/python3.10/site-packages/sqlfluff/core/linter/runner.py", line 103, in run
    yield partial()
  File "/Users/yoichi/.virtualenvs/sqlfluff/lib/python3.10/site-packages/sqlfluff/core/linter/linter.py", line 741, in lint_rendered
    return cls.lint_parsed(
  File "/Users/yoichi/.virtualenvs/sqlfluff/lib/python3.10/site-packages/sqlfluff/core/linter/linter.py", line 667, in lint_parsed
    tree, initial_linting_errors, ignore_buff = cls.lint_fix_parsed(
  File "/Users/yoichi/.virtualenvs/sqlfluff/lib/python3.10/site-packages/sqlfluff/core/linter/linter.py", line 586, in lint_fix_parsed
    new_tree, _, _ = tree.apply_fixes(
  File "/Users/yoichi/.virtualenvs/sqlfluff/lib/python3.10/site-packages/sqlfluff/core/parser/segments/base.py", line 1278, in apply_fixes
    s, before, after = seg.apply_fixes(dialect, rule_code, fixes)
  File "/Users/yoichi/.virtualenvs/sqlfluff/lib/python3.10/site-packages/sqlfluff/core/parser/segments/base.py", line 1278, in apply_fixes
    s, before, after = seg.apply_fixes(dialect, rule_code, fixes)
  File "/Users/yoichi/.virtualenvs/sqlfluff/lib/python3.10/site-packages/sqlfluff/core/parser/segments/base.py", line 1278, in apply_fixes
    s, before, after = seg.apply_fixes(dialect, rule_code, fixes)
  [Previous line repeated 3 more times]
  File "/Users/yoichi/.virtualenvs/sqlfluff/lib/python3.10/site-packages/sqlfluff/core/parser/segments/base.py", line 1331, in apply_fixes
    segments=self._position_segments(
  File "/Users/yoichi/.virtualenvs/sqlfluff/lib/python3.10/site-packages/sqlfluff/core/parser/segments/base.py", line 549, in _position_segments
    raise ValueError("Unable to find working position.")
ValueError: Unable to find working position.

==== no fixable linting violations found ====
All Finished 📜 🎉!
```

### How to reproduce

sqlfluff fix x.sql --dialect=mysql --rules=L032

### Dialect

MySQL

### Version

sqlfluff, version 1.2.1
Python 3.10.0

### Configuration

not using configuration file

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by alanmcruickshank**
This resolves #3656 .

The issue was caused by child segments trying to apply fixes to segments inserted or edited by a parent which hadn't yet assigned position markers using `_position_segments`. This simply adds an intermediate step _after_ applying fixes to the parent where we optionally reposition `self` before applying fixes to children.

This will add a very slight performance overhead, but I don't think the `fix` routine is currently the bottleneck. Potentially in future we might be able to more selectively run this routine, but for now this feels ok. Added a test case too.

### CODE REVIEW

**Review by tunetheweb — APPROVED** [review]
Looks like a simple enough fix. But would be good if @barrywhart can review too.

**Review by barrywhart — APPROVED** [review]
Nice, elegant fix! My intuition was that we needed to do the positioning "top down", but there was a high risk I'd fumble around for a loonngg time working out the details.

Thanks!! 🙌

**Comment by barrywhart** [comment]
I noticed the 3.7 tests are failing but couldn't view the output report for some reason. Hopefully something simple!

**Comment by barrywhart** [comment]
A dbt test is failing:
```
E               {% snapshot dim_aggregated_brand_hierarchy_snapshot %}
E               
E               {{
E                   config(
E                     strategy='check',
E                     unique_key='c1',
E                     target_schema='snapshots',
E                     check_cols='all'
E                   )
E               }}
E               
E             -     select c1
E             ?           ---
E             +     select
E             +         c1
E                   from
E                       foo
E               
E               {% endsnapshot %}
```

**Comment by alanmcruickshank** [comment]
> A dbt test is failing:

Yeah I saw this, and I'm really not sure *why* 🤔 . I feel like I've uncovered a bigger bug.

**Comment by alanmcruickshank** [comment]
Ok, no I understand what's going on - by repositioning early - the matching of fixes to segments goes wrong. They no longer "find" their target because it's not the same segment. Will rethink approach.

**Comment by alanmcruickshank** [comment]
NOTE: This now includes the changes from #3661 to confirm that they solve the test fails I was otherwise getting. That will make the diff look weird but means we should merge the other PR first if all looks good.

**Pull request merged**
