### PR TITLE
postgres: Add numeric data types (alternative)

### PR DESCRIPTION
**Pull request by kayman-mk**
Alternative implementation. See #2121 (original)

This solution has a nicer parse tree for the `data_type`
```
- statement:
    create_table_statement:
    - keyword: create
    - keyword: table
    - table_reference:
        identifier: c
    - bracketed:
      - column_reference:
          identifier: ca
      - data_type:
          data_type_identifier: decimal
          bracketed:
          - start_bracket: (
          - literal: '7'
          - comma: ','
          - literal: '2'
          - end_bracket: )
      - end_bracket: )
- statement_terminator: ;

```

Problem so far: data type `decimal precision` is not parsable. Seems to be a problem with the regex, which I can't find
`r'smallint|integer|int2|int4|int8|bigint|real|double\s+precision|smallserial|serial|serial2|serial4|serial8|bigserial'`

TODO: Clean keywords

### Pull Request checklist
- [ ] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `python test/generate_parse_fixture_yml.py` or by running `tox` locally).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by jpy-git** [comment]
375 files changed, that'll need sorting out before I can look at this!

**Comment by kayman-mk** [comment]
Main reason are whitespace changes. I think it was the pre-commit hook.

**Comment by jpy-git** [comment]
guess you ran it on all files rather than just the ones you staged?

**Comment by kayman-mk** [comment]
Yeah, but should be the same result, shouldn't it?

**Comment by jpy-git** [comment]
pre-commit was only introduced last week so we've just been running on new files, so the historical end of line/trailing newlines haven't been fixed. I can do a one of fix of all of these so this doesn't happen again, but will need to be removed from this PR.

**Comment by jpy-git** [comment]
ahh you did, thanks 😄

**Comment by jpy-git** [comment]
Closing: we don't want to be doing this through regex, via keywords in the other PR is more correct.

**Pull request closed without merging**
