### PR TITLE
Revert "Ignore click mypy issues"

### PR DESCRIPTION
**Pull request by greg-finley**
Reverts sqlfluff/sqlfluff#4954

After https://github.com/pallets/click/releases/tag/8.1.5

### CODE REVIEW

**Comment by greg-finley** [comment]
Hmm, still failing ... I guess leave this but we could revert later if needed

**Comment by alanmcruickshank** [comment]
I wonder if this is still useful. I'm getting mypy issues on other PRs again.

**Comment by greg-finley** [comment]
I pondered mypy-ignoring this entire file as well

**Comment by greg-finley** [comment]
And yep click did another release an hour ago

**Pull request merged**
