### PR TITLE
Drop support of python 3.7

### PR DESCRIPTION
**Pull request by zhongjiajie**
### Brief summary of the change made

python 3.7 is EOL at 2023-06-27, which we can see
in https://devguide.python.org/versions/ so we
should drop support of it

BTW, drop support python 3.7 can also reduce code
complex, such as we do not need some package only
support in python 3.7, including `importlib_metadata` and `backports.cached-property`

and we have to use code like

```python
import sys

if sys.version_info >= (3, 8):
    from functools import cached_property
else:  # pragma: no cover
    from backports.cached_property import cached_property

__all__ = ("cached_property",)
```

### Are there any other side effects of this change that we should be aware of?

python 3.7 user can not install sqlfluff

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by zhongjiajie** [comment]
PTAL @alanmcruickshank when you have time

**Review by alanmcruickshank — COMMENTED** [review]
Looks very sensible. I'd rather not merge this yet, until we're ready for the next major release. That may not be for some time - but I'll keep this PR ready for that point 👍

**Comment by zhongjiajie** [comment]
> Looks very sensible. I'd rather not merge this yet, until we're ready for the next major release. That may not be for some time - but I'll keep this PR ready for that point 👍

Get it, and I find you add new label for this PR

**Comment by alanmcruickshank** [comment]
I think now is a good moment to get this merged, I'll work on staging it in shortly 👍

**Review by alanmcruickshank — APPROVED** [review]
This is the right time to merge this 👍

**Pull request merged**
