### PR TITLE
Linter Test Name Duplication

### PR DESCRIPTION
**Pull request by jpers36**
Two of the L003 linter tests have duplicate names.  I've adjusted one to properly match the test case.

Two of the L014 linter tests have duplicate names.  I've adjusted one to properly match the test case.

Two of the L043 linter tests are exactly the same.  I've removed one.

### CODE REVIEW

**Comment by tunetheweb** [comment]
There's a few more of these btw! This is why we could do with yamllint :-)

test_fail_inconsistent_capitalisation_1 in L014.yml
test_fail_inconsistent_capitalisation_1 in L043.yml

Fancy fixing the above in this PR too?

**Comment by jpy-git** [comment]
> test_fail_inconsistent_capitalisation_1 in L014.yml
> test_fail_inconsistent_capitalisation_1 in L043.yml

@tunetheweb yamllint won't check these things cross files

**Comment by jpers36** [comment]
@jpy-git the L043 one was actually test_pass_case_cannot_be_reduced_10.  Both L043 and L014 had internal duplicates.

**Comment by jpers36** [comment]
@tunetheweb those are now addressed!

**Comment by jpy-git** [comment]
> @jpy-git the L043 one was actually test_pass_case_cannot_be_reduced_10. Both L043 and L014 had internal duplicates.

@jpers36 gotcha, thanks for clarifying 👍

**Review by tunetheweb — APPROVED** [review]

**Pull request merged**
