### PR TITLE
Do not check the path in the GitHub annotation test so it'll work on Windows

### PR DESCRIPTION
**Pull request by barrywhart**
Proposed alternative to #1221

### CODE REVIEW

**Review by alanmcruickshank — CHANGES_REQUESTED** [review]
I think it's still worth testing the file output so that we can make sure it still works for most users. In my mind, either we skip the test (as per #1221) or we call `normpath` on all the filenames on both side of the equation. Happy to go with the latter - but I'm also happy to go with the former. @barrywhart What do you reckon?

**Comment by barrywhart** [comment]
I'll add `normpath()`. I knew there was a function which would do this, but I was too lazy yesterday to go and look it up. 😿

**Comment by barrywhart** [comment]
@alanmcruickshank: This is ready for another review. The tests are taking a while to run, unfortunately. 🤔

**Review by alanmcruickshank — APPROVED** [review]
I like this approach. I've closed my other PR. This is failing linting checks, but otherwise looks good!

**Comment by barrywhart** [comment]
I fixed the lint check (just needed to run Black). Merging...

**Pull request merged**
