### PR TITLE
provide custom DeprecatedOption

### LINKED ISSUE #3644: Standardise `--disable_progress_bar` naming
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

As noted in https://github.com/sqlfluff/sqlfluff/pull/3610#discussion_r926014745 `--disable_progress_bar` is the only command line option using underscores instead of dashes.

Should we change this?

This would be a breaking change, so do we leave until next major release?
Or do we accept both options?

### Expected Behaviour

We should be standard in out command line option format

### Observed Behaviour

`--disable_progress_bar` is the only non-standard one

### How to reproduce

N/A

### Dialect

N/A

### Version

1.2.1

### Configuration

N/A

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by adam-tokarski**
### Brief summary of the change made
Fixes #3644 

* introduces custom click's `DeprecatedOption` 
* This is used for handling `--disable_progress_bar`
* It's not covered with any tests yet, because not sure if this approach will defend itself.

#### somewhat longer background
Changing option to another is easy. But to avoid any issues I wanted to have nicely handled both versions of click option (bonus points for informing that one of them is deprecated). I was not able to find working solution, then found on click's GH [issue](https://github.com/pallets/click/issues/2263) with linked SO [example solution](https://stackoverflow.com/a/50402799/5172513). 

Seems to be working, but it's kind of hackish, and I'm not personally very happy of it. But it works now and as long the mentioned issue is opened, there is still a chance that such possibility will be provided. Then we will be able to remove this custom option provided in current PR and use something from package itself.

This is also the reason why I didn't provided any tests for that yet - I want to know if sqlfluff's community (@tunetheweb, @alanmcruickshank?) is happy with proposed solution. If yes, I will provide them.

### Are there any other side effects of this change that we should be aware of?
* nope

### Pull Request checklist
- [ ] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by alanmcruickshank** [comment]
I think this approach is sensible - I agree it's a little hacky, but it seems fairly robust. I agree that setting us up for easier times in the future if a similar feature is merged into `click` makes sense.

On the testing front: we should either cut out parts of the functions we don't need or put together some basic tests for them. Happy for you to decide which bits to remove, and which bits to test.

Would you be happy to put up a pull request to merge the same code into `click` itself?

**Comment by adam-tokarski** [comment]
I've already cut some things I don't see very useful and did small cleanup. Will see if anything more can be found. Also I'm going to provide some tests.

Was thinking about putting that into click, but I guess that this would be change which rather modifies the click core than just extends it (in that hacky way). I don't say no, but it may be no so straightforward.

**Comment by adam-tokarski** [comment]
@alanmcruickshank tests were provided, please take a look on that.

**Comment by alanmcruickshank** [comment]
Nice. Looks good 👍 

A few tests are failing but I think this PR is otherwise good to go.

**Comment by adam-tokarski** [comment]
@alanmcruickshank 
Ah, mypy... I fixed these errors - unfortunately I've needed to set to ignore some of them, but there was also an issue with testing on older Python version, and it's fixed as well.

**Review by alanmcruickshank — APPROVED** [review]

**Pull request merged**
