### PR TITLE
Fully remove python3.6 references

### PR DESCRIPTION
**Pull request by jpy-git**
### Brief summary of the change made

Python3.6 support was recently removed in #2141, however, I can still see several references to python 3.6. Seeing if removing these is fine.

### Are there any other side effects of this change that we should be aware of?
No

### Pull Request checklist
- [X] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `python test/generate_parse_fixture_yml.py` or by running `tox` locally).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by jpy-git** [comment]
@tunetheweb @barrywhart removed the remaining python 3.6 references and tests are working fine 👍

**Comment by tunetheweb** [comment]
Here’s the Python 3.6 SQLFluff download stats:

1028CA69-48A8-43D6-A73B-E19AAEFEFD55

From: https://pypistats.org/packages/sqlfluff

I wonder should we leave this in draft for a week and see what the stats are like now that we are no longer running this in our CI to see the actual real usage?

Since it’s not that much code to clean up, is there any harm in leaving this in for those that use Python 3.6?

**Comment by jpy-git** [comment]
@tunetheweb no, because in the #2141 thats already been merged we've removed the dependencies required for 3.6 to work:
image

So SQLFluff already will no longer work with 3.6, this just finishes the job

**Comment by tunetheweb** [comment]
Ah fair enough. Old users can just stick on 0.9.0 or prior.

**Review by tunetheweb — APPROVED** [review]

**Comment by jpy-git** [comment]
Yeah I think it's safest, then we don't need to waste time with any potential issues that could arise from people using 3.6 when it becomes unsupported 👍

**Pull request merged**
