### PR TITLE
BigQuery: Support PIVOT and UNPIVOT

### LINKED ISSUE #1755: BigQuery PIVOT PRS Error
```sql
WITH tbl AS (
  SELECT
    Gender,Year,SUM(Number) AS Number
  FROM
    `bigquery-public-data.usa_names.usa_1910_current`
  WHERE
    Year >= 2017
  GROUP BY
    Gender, Year
    )
    
 
SELECT
  year, male, female
FROM
  tbl
PIVOT( SUM(Number) FOR gender IN ('M' AS male, 'F' AS female))
ORDER BY
  year;
```

^Relevant query

## Expected Behaviour

I copied pasted `PIVOT` example from an official BigQuery blog [post](https://cloud.google.com/blog/topics/developers-practitioners/cool-summer-with-bigquery-user-friendly-sql) (and lightly edited) after running into this `PRS` error on some of my own SQL. I expect it to parse successfully as BigQuery can execute it successfully. From peaking at the code it doesn't look like SQLFluff supports `PIVOT` yet for BigQuery

## Observed Behaviour

```
==== parsing violations ====
L:  17 | P:   6 |  PRS | Line 17, Position 6: Found unparsable section: "( SUM(Number) FOR
                       | gender IN ('M' AS male..."

```

## Steps to Reproduce

Add snippet into local file and run `sqlfluff parse`

## Dialect

BigQuery

## Version
Include the output of `sqlfluff --version` along with your Python version

sqlfluff, version 0.7.1
Python 3.8.7

## Configuration
```
[sqlfluff]
dialect = bigquery
```

### PR DESCRIPTION
**Pull request by tunetheweb**
### Brief summary of the change made
Fixes #1755 

### Are there any other side effects of this change that we should be aware of?
Makes `PIVOT` and `UNPIVOT` reserved keywords (even though they aren't) to make it easier to parse. We have precedent for this.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `python test/generate_parse_fixture_yml.py` or by running `tox` locally).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by alanmcruickshank — APPROVED** [review]
LGTM 👍

**Comment by alanmcruickshank** [comment]
Maybe worth a review from @barrywhart too as our resident bigquery expert.

**Comment by tunetheweb** [comment]
> Maybe worth a review from @barrywhart too as our resident bigquery expert.

Hey I'm a BigQuery expert too! 😁. And also called Barry - so much confusion! 😁😁

But yeah more reviewers the better.

**Review by barrywhart — APPROVED** [review]
I haven't used `PIVOT` or `UNPIVOT`, but I reviewed it and looks good!

**Pull request merged**
