### PR TITLE
Adds extra check to L054 to avoid weird error messages

### PR DESCRIPTION
**Pull request by tunetheweb**
### Brief summary of the change made

Follow on from #1981 and #1987

Don't try to pop an empty column set in L054 to avoid weird error messages. Shouldn't really happen if there are no parsing errors and no `--noqa` (so took me a while to reproduce a test case!) but good check to have I think.

@jpy-git can you review too please since you added this rule?

### Are there any other side effects of this change that we should be aware of?
Don't think so

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `python test/generate_parse_fixture_yml.py` or by running `tox` locally).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by jpy-git** [comment]
@tunetheweb so the code change is perfect! ⭐ 

You're getting an error in the unit tests though. Reason being that it seems to raise if a parse error is detected at any point during the test, even if it's later suppressed by the inline comment.

**Comment by jpy-git** [comment]
so may need a custom test or could be included as a parsing test and validate that no exception is raised

**Comment by tunetheweb** [comment]
> so may need a custom test or could be included as a parsing test and validate that no exception is raised

Fixed! all tests passing now.

**Comment by jpy-git** [comment]
Nice one, I'm happy with the change 👍

**Review by WittierDinosaur — APPROVED** [review]

**Pull request merged**
