### PR TITLE
Extend ruff checking to docstring rules

### PR DESCRIPTION
**Pull request by alanmcruickshank**
Following on from #5289, this adds the docstring rules to ruff, copying the same configuration as currently exists for `flake8`.

### CODE REVIEW

**Review by zhongjiajie — APPROVED** [review]
LGTM and it catch some things we do not get before

**Review by greg-finley — APPROVED** [review]
Nice! Could/should we have flake8 not do this check now?

**Comment by alanmcruickshank** [comment]
> Nice! Could/should we have flake8 not do this check now?

Yeah good idea. I'll strip some of that out

**Comment by alanmcruickshank** [comment]
> > Nice! Could/should we have flake8 not do this check now?
> 
> Yeah good idea. I'll strip some of that out

Actually... I wont remove it yet, but I'll definitely get `ruff` to run first in the linting step.

**Pull request merged**
