### PR TITLE
Use the slower but safer "spawn" method to create multiprocessing.Pool

### PR DESCRIPTION
**Pull request by barrywhart**
### Brief summary of the change made
@tunetheweb: I think this may avoid the issues you've described where the coverage check sometimes hangs. This PR changes the behavior both for tests and actual usage. It will be a bit slower spawning subprocesses, but since linting takes a long time (minutes), this probably isn't a big concern.

Is there some way we can test to confirm this change is helpful?

Relevant docs:
* https://stackoverflow.com/questions/43818519/what-is-the-meaning-of-context-argument-in-multiprocessing-pool-pool/43818829
* https://python.readthedocs.io/en/stable/library/multiprocessing.html#contexts-and-start-methods

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by tunetheweb** [comment]
Once the run completes can we try unpinning coverage to see if it fixes that issue too?

**Comment by barrywhart** [comment]
@tunetheweb: Any idea why I'm seeing "cancelled" for the "Rules critical errors tests"?! It's happened twice for this PR.

image

**Comment by tunetheweb** [comment]
Usually implies another failure in that test group so no point continuing other tests. Though thought I’d put that in its own group…

**Comment by barrywhart** [comment]
The check runs fine locally on my Mac M1.

image

**Comment by tunetheweb** [comment]
I looked through all the past tests for the PR bad that check never failed. Sure you weren’t confusing it with something else?

**Comment by barrywhart** [comment]
@tunetheweb: Oh sorry -- I meant that it failed twice for **this** PR (two separate commits).

**Comment by barrywhart** [comment]
I temporarily disabled it. I want to test the coverage stuff, then can re-enable it with more logging if needed.

**Comment by barrywhart** [comment]
I can understand "failing", but "cancelled" implies that a human did it, or that it triggered some sort of policy/security issue or ???

**Comment by tunetheweb** [comment]
Oh it’s also cancelled if you submit a new commit as pointless completing that one o e. Then need to refresh this PR page to see latest one. Maybe it was that? Maybe that job cancels quicker than. The others so that’s why you noticed it?

**Comment by barrywhart** [comment]
Hmm, I didn't think I had submitted a new commit, but maybe. I'll pay closer attention now.

**Comment by barrywhart** [comment]
@tunetheweb: Looks like the 3.7 tests are still hanging, even with this change. It's odd, because AFAIK, I made the exact change mentioned in the "coverage" issue, i.e. using "spawn" model to create new processes. TBH, I have not used this process setting before, so I _could* have messed it up, but it seems pretty straightforward.

Since you said this mainly (only?) happens in Python 3.7, think we could use a newer Python version for checking coverage? The project has very little if any version-specific code, so there's not much additional benefit to checking coverage on _every_ supported version of Python.

**Comment by tunetheweb** [comment]
We could to that. Feels less than satisfactory though.

It would be worth trying your branch with their latest patch. Replace this line in requirements_dev.txt:
`coverage`
with this:
`git+https://github.com/nedbat/coveragepy@nedbat/fix-1310`
Which will install their patched version of coverage instead.

**Comment by barrywhart** [comment]
I'll leave this open in case we want to try more experiments. So far, **nothing** has helped. 😿

**Comment by tunetheweb** [comment]
Closing this for now as Coverage are continuing to investigate.

**Pull request closed without merging**
