### PR TITLE
fix: redshift dialect, EXTENSION added

### PR DESCRIPTION
**Pull request by rafalbog**
github.com/sqlfluff/sqlfluff/issues/6023

### Pull Request checklist
- [ ] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by greg-finley** [comment]
Hello! This looks like a good start, but you could please [add a test](https://github.com/sqlfluff/sqlfluff/wiki/Contributing-Dialect-Changes#testing-your-changes)?

**Review by alanmcruickshank — APPROVED** [review]
Test case added

**Comment by rafalbog** [comment]
@greg-finley sory I did not see your msg, will try to be better contributor in the future.
@alanmcruickshank  thx for adding the test  case

**Comment by ferdinandyb** [comment]
@alanmcruickshank thanks for clearing up the PR! Do you have an ETA for a next release where this change can make it?

**Comment by alanmcruickshank** [comment]
> @alanmcruickshank thanks for clearing up the PR! Do you have an ETA for a next release where this change can make it?

We're probably already due a release. I'll see if I can get one shipped this week 👍

**Pull request merged**
