### PR TITLE
Demonstrate BigQuery parse errors

### PR DESCRIPTION
**Pull request by jml**
I was quite excited to see that https://github.com/alanmcruickshank/sqlfluff/pull/332 fixed several bugs I filed. 

However, when I ran…

```console
$ sqlfluff lint --ignore=templating --rules=L001 models/
== [models/adjust/adjust_view.sql] FAIL
L:  18 | P:   4 |  PRS | Found unparsable section: ' except
                       | (partner_parameters)\nfrom\n adju...'
== [models/braze/custom_user_attributes.sql] FAIL
L:  18 | P:   5 |  PRS | Found unparsable section: 'STRUCT(\n username,\n
                       | email,\n ...'
L: 103 | P:  17 |  PRS | Found unparsable section: ' except (user_id, updateable,
                       | watermark,...'
== [models/braze/user_subscription.sql] FAIL
L:  11 | P:   3 |  PRS | Found unparsable section: "CASE subscription_type\n WHEN
                       | 0 THEN '..."
== [models/jira/stg_epics.sql] FAIL
L:  11 | P:  25 |  PRS | Found unparsable section: ' *'
== [models/jira/stg_issues.sql] FAIL
L:  31 | P:   5 |  PRS | Found unparsable section: 'STRUCT(\n status.status_id AS
                       | id,\n...'
L:  42 | P:   5 |  PRS | Found unparsable section: 'ARRAY(\n SELECT AS STRUCT\n
                       | ...'
L:  59 | P:   5 |  PRS | Found unparsable section: 'ARRAY(\n SELECT AS STRUCT\n
                       | ...'
L: 108 | P:   7 |  PRS | Found unparsable section: 'CASE
                       | LOWER(show_on_pipeline_board.name)\n...'
== [models/legacy_models/segment_users.sql] FAIL
L:   7 | P:   4 |  PRS | Found unparsable section: ' except (\n id,\n
                       | context_library_na...'
== [models/legacy_models/subscription_logs_history_view.sql] FAIL
L:  51 | P:  15 |  PRS | Couldn't find closing bracket for opening bracket.
== [models/reports/tech/_pipeline_build_epics.sql] FAIL
L:  28 | P:   5 |  PRS | Found unparsable section: 'ARRAY(\n SELECT AS STRUCT\n
                       | ...'
```

(Note: the `--rules=L001` is a hack to suppress any linter warnings, so I just get parser errors).

… against our code, I still had quite a few parse errors for what I know to be valid BigQuery SQL code.

Rather than file one bug per error, I thought it might be better to submit a PR that adds tests that demonstrate the problem. I'd really love to dig in and fix these issues, but I'm very unlikely to have the time. If you would prefer me to file bugs, I can definitely do that. 

Thank you so much for looking into this! sqlfluff is very promising. 

## Failing tests

- [ ] FAILED test/dialects_test.py::test__dialect__base_file_parse[bigquery-select_except_replace.sql]
- [ ] FAILED test/dialects_test.py::test__dialect__base_file_parse[bigquery-select_except.sql]
- [x] FAILED test/dialects_test.py::test__dialect__base_file_parse[bigquery-select_case.sql] (fixed by #364)
- [ ] FAILED test/dialects_test.py::test__dialect__base_file_parse[bigquery-select_struct.sql]

### CODE REVIEW

**Comment by alanmcruickshank** [comment]
Thanks for this @jml. I'm going to leave this PR open until all of the queries that you've added have been appropriately addressed. These will be useful test cases to work to.

**Comment by alanmcruickshank** [comment]
> (Note: the `--rules=L001` is a hack to suppress any linter warnings, so I just get parser errors).

btw @jml , you can also do us `--ignore templating,linting` to achieve the same thing :)

**Comment by jml** [comment]
Thanks @alanmcruickshank. Should I watch here for progress? 

Also, feel free to give me a nudge on #linters on dbt Slack if I can help in any way. I don't really get time to code these days, but I can review PRs.

**Comment by barrywhart** [comment]
I can potentially work on some of these. Suggest one or two of these and ping me if you like, @alanmcruickshank!

**Comment by barrywhart** [comment]
I created a PR to address the `CASE` example. It's a very simple change, but it causes parse failures in the existing `CASE` tests. Any insights are welcome. See #386.

**Comment by jml** [comment]
The changes in #364 (thank you!) bring this down to three test failures, all to do with BigQuery-specific `select` syntax.

```
FAILED test/dialects_test.py::test__dialect__base_file_parse[bigquery-select_except.sql]
FAILED test/dialects_test.py::test__dialect__base_file_parse[bigquery-select_struct.sql]
FAILED test/dialects_test.py::test__dialect__base_file_parse[bigquery-select_except_replace.sql]
```

I'll turn this into a todo list in the description, so we get a better sense of progress.

**Comment by dmateusp** [comment]
@jml, I added a grammar called `"Not(...)"` which allowed me to resolve ambiguity between SetOperator and a BigQuery Except, I fixed all of your tests (support STRUCT, EXCEPT, REPLACE) https://github.com/Memrise/sqlfluff/pull/1

**Comment by jml** [comment]
> My PR will actually need some docs changes, and other linting, so maybe I should just create a new PR and reference this one, wdyt?

Yeah, I think that's a good idea. Thanks so much for looking into this!

**Comment by barrywhart** [comment]
I tested the `.sql` files in this PR using the latest code in `master` as of 2021-02-09, and they all pass. I think we addressed these issues over time. @jml: Can you confirm this? I think we can close the PR. Thanks for the test cases. 💯

**Comment by jml** [comment]
Thanks @barrywhart! I'll try to take a look over the next few working days.

**Comment by dmateusp** [comment]
hey @jml I'm going to close this PR since @barrywhart had a look, if you see these issues aren't resolved please reopen :)

**Pull request closed without merging**
