### PR TITLE
Fix: Add missing init file to `sqlfluff.core.templaters.slicers`

### PR DESCRIPTION
**Pull request by CrossNox**
### Brief summary of the change made
Running `sqlfluff --help` (or any CLI command) fails with `ModuleNotFoundError: No module named 'sqlfluff.core.templaters.slicers'` due to a missing `__init__.py` file on `src/sqlfluff/core/templaters/slicers`.

### Are there any other side effects of this change that we should be aware of?
`None`

### CODE REVIEW

**Comment by CrossNox** [comment]
I just noticed that [1788](https://github.com/sqlfluff/sqlfluff/pull/1788) adds this file, but IMHO this quick fix can be isolated into a small PR and then merge those changes, so that `main` has a runnable version.

**Comment by tunetheweb** [comment]
Can you add the comment like #1788 does to prevent linting failures.

@barrywhart you happy for this to go ahead of your PR?

**Comment by barrywhart** [comment]
Sure, go ahead. Not sure when mine will be finished.

**Comment by CrossNox** [comment]
> Can you add the comment like #1788 does to prevent linting failures.
> 
> @barrywhart you happy for this to go ahead of your PR?

Added! @barrywhart I couldn't find a way to checkout the file from your fork so that it appeared as authored by you, sorry.

**Comment by barrywhart** [comment]
No worries!

**Comment by WittierDinosaur** [comment]
Perhaps it's worth adding a test case for this?

**Comment by CrossNox** [comment]
@WittierDinosaur do you mean testing the CLI or testing imports?

**Comment by tunetheweb** [comment]
Presume he means to prevent this issue happening again in the future where a new module is added without a `__init__.py` when it's needed?

Would be good if we could add that. But think out of scope of this PR so let's merge this.

**Review by tunetheweb — APPROVED** [review]

**Pull request merged**
