### PR TITLE
Sorted configuration of "Rules Reference"

### PR DESCRIPTION
**Pull request by zhongjiajie**
Keep configuration of "Rules Reference" in alphabetical. Our configuration now look like 
Screen Shot 2021-04-13 at 02 11 10

### CODE REVIEW

**Comment by zhongjiajie** [comment]
I try to build doc locally, checking if this patch working, by using `make html` but I could not see any change. Did I miss something?

**Review by pwildenhain — APPROVED** [review]
This should work, I'll merge it thanks for the contribution 😁

**Comment by pwildenhain** [comment]
Looks like it worked 🥳 

https://docs.sqlfluff.com/en/latest/rules.html

image

**Comment by zhongjiajie** [comment]
Thank for merging

**Comment by pwildenhain** [comment]
Perhaps running `make clean` before running `make html` would work?
https://stackoverflow.com/a/59807519/11381493

**Comment by zhongjiajie** [comment]
@pwildenhain I try it, but html still with outdated content. 😢

**Comment by pwildenhain** [comment]
Weird 😞 I'm honestly not sure what's going on 🤷‍♂️

**Pull request merged**
