### PR TITLE
0.6.0a1 Release

### PR DESCRIPTION
**Pull request by NiallRees**
Thought I'd go for a minor version increment as there's been a significant overhaul recently and this is a potentially dramatic speed increase.

### CODE REVIEW

**Comment by barrywhart** [comment]
Looks good to me! I just merged a fix for #1051, so we may want to include it in the change log.

**Comment by NiallRees** [comment]
> Looks good to me! I just merged a fix for #1051, so we may want to include it in the change log.

Would you mind doing that? I'll then merge and make a release.

**Comment by barrywhart** [comment]
Mind if I include it in #1052? It's not related, but you'd approved that, and I was about to merge it once the build passes.

**Comment by barrywhart** [comment]
Ok, I updated the change log in my PR #1052. Will merge that in a few minutes if the build passes. 🤞🏽

**Comment by barrywhart** [comment]
Merged!

**Comment by NiallRees** [comment]
> Looks good to me! I just merged a fix for #1051, so we may want to include it in the change log.

Could you re approve pls?

**Review by barrywhart — APPROVED** [review]
Looks good. I don't recall -- do we need to update a version number in setup.py as well?

**Pull request merged**
