### PR TITLE
#692: Convert Python relative imports to absolute

### LINKED ISSUE #692: Relative vs absolute imports
Following on from https://github.com/sqlfluff/sqlfluff/pull/688#discussion_r559233302:

@alanmcruickshank 
> Imports appear inconsistent within the file (some are absolute and some are relative). If this isn't necessary I think we should be consistent and make them relative. If there are some occasions where absolute references are necessary then this should be documented with a comment to say why.

@me
> ...my understanding is that absolute imports are preferred over relative. Where I had to adjust/add an import, I went for absolute, but didn't touch the rest. The main reason is that an absolute import is visually far more expressive in terms of project structure, and and it's easier to fix issues too if the project structure moves around with a find and replace vs relative imports. We should definitely be consistent though - I'll make an issue to decide one way or the other, let's make the decision there and take action in another PR?

Any other opinions on this?

### PR DESCRIPTION
**Pull request by barrywhart**
Resolves #692.

I ran a tool called [`absolute_imports`](https://pypi.org/project/abs-imports/), which updated the imports automatically. This is my second attempt at this PR, and it addresses the issues noted in that one (#744).

Aside: This is an interesting PR. I ran a tool (`abs_imports`) to change the code for a project (SQLFluff) that changes other code (SQL). Meta FTW! 😎

### CODE REVIEW

**Comment by barrywhart** [comment]
The linter is failing, but I think those are legacy issues -- this PR is **only** touching imports, AFAIK.

**Comment by NiallRees** [comment]
Looks like there are a few conflicts here before we can marge fyi @barrywhart !

**Comment by barrywhart** [comment]
@NiallRees: What do you mean about conflicts? I don't see any merge conflicts, just linter failures which I think predate this PR but are being flagged by it.

I'll double check what the linter (Black) actually wants to do. I see it's only complaining about 8 files or so.

**Comment by barrywhart** [comment]
@NiallRees: Ah, now I see the conflicts. I must've forgotten to refresh the page. I fixed the conflicts and ran Black. The linter complaints were legit -- it wanted some of the modified import lines reformatted (e.g. wrapping long lines). I think this is good to go now.

**Comment by barrywhart** [comment]
Oh no! Our CircleCI builds are "failing" because we've hit some sort of quota:

>This job has been blocked because no credits are available on your plan. Please upgrade to continue building.

**Review by NiallRees — APPROVED** [review]

**Pull request merged**
