### PR TITLE
Issue 1056: Correctly handle Ctrl-C when running parallel linting

### LINKED ISSUE #1056: Parallel linting is un-killable
`sqlfluff 0.6.0a1`

running lint `--parallel 4`.

# Expected outcome.

While running if I press `ctrl+c` to abort the process it should stop gracefully.

# What actually happens.

I get a traceback output but the process doesn't actually stop. Eventually I have to kill the shell to get it to exit.

### PR DESCRIPTION
**Pull request by barrywhart**
Resolves #1056

### CODE REVIEW

**Comment by alanmcruickshank** [comment]
This definitely works 👍 , I wonder if we can make it more elegant however. The traceback is very long for the `KeyboardInterrupt` that I'm getting, and for an abort I don't think we need to print that interrupt.

Something in how `click` handles `KeyboardInterrupt` makes it more graceful, but I'm not exactly sure how.

**Comment by barrywhart** [comment]
@alanmcruickshank: Can you paste the output you're seeing, for reference? Currently, I'm not catching the KeyboardInterrupt exception. We could catch that to avoid any automatic output such as a stack trace. The key change in this PR is the signal handling stuff, which prevents the child processes from seeing the interrupt.

**Comment by barrywhart** [comment]
I'll be away from the computer today. If y'all want, feel free to merge this and then do additional changes, or I can pick this up tomorrow.

**Comment by alanmcruickshank** [comment]
So if I run a linting command on the project and then press `ctrl+c` once and once only I get this:


<details>
  <summary>Log output</summary>
  <pre>
  $ pipenv run sqlfluff lint -vv
  ==== sqlfluff ====
  sqlfluff:         0.6.0a1 python:             3.8.6
  dialect:        snowflake verbosity:              2
  templater:            dbt dbt:              =0.19.1
  rules:       L004, L010, L011, L014, L025
  == Raw Config:
  core:
      bench:              False
      dialect:            snowflake
      exclude_rules:      L009
      ignore:             []
      ignore_templated_areas:True
      nocolor:            False
      output_line_length: 80
      recurse:            True
      rules:              L004,L010,L011,L014,L025
      runaway_limit:      10
      sql_file_exts:      .sql,.sql.j2,.dml,.ddl
      templater:          dbt
      verbose:            2
  indentation:
      indented_joins:     False
      template_blocks_indent:True
  rules:
      allow_scalar:       True
      comma_style:        trailing
      indent_unit:        space
      max_line_length:    80
      single_table_references:consistent
      tab_space_size:     4
      unquoted_identifiers_policy:all
      L003:
          lint_templated_tokens:True
      L010:
          capitalisation_policy:lower
      L014:
          capitalisation_policy:lower
          extended_capitalisation_policy:consistent
      L016:
          ignore_comment_lines:False
      L029:
          unquoted_identifiers_policy:aliases
      L030:
          capitalisation_policy:consistent
      L038:
          select_clause_trailing_comma:forbid
      L040:
          capitalisation_policy:consistent
      L042:
          forbid_subquery_in: join
      L047:
          prefer_count_1:     False
  templater:
      unwrap_wrapped_queries:True
      jinja:
          apply_dbt_builtins: True
          macros:
              dbt_config:         {% macro config() %}{% for k in kwargs %}{% endfor %}{% endmacro %}
              dbt_is_incremental: {% macro is_incremental() %}True{% endmacro %}
              dbt_ref:            {% macro ref(model_ref) %}{{model_ref}}{% endmacro %}
              dbt_source:         {% macro source(source_name, table) %}{{source_name}}_{{table}}{% endmacro %}
              dbt_var:            {% macro var(variable) %}item{% endmacro %}
  
  ==== readout ====
  
  === [ path: C:\Users\alan\dev3\tails-analytics-dbt\data_warehouse ] ===
  
  == [C:\Users\alan\dev3\tails-analytics-dbt\data_warehouse\models\base\advertising\stg_stitch__bing_fr.sql] TEMPLATING
  === [dbt templater] Compiling dbt project...
  
  Aborted!
  
  Aborted!
  
  alan@ALAN-XPS-2020 C:\Users\alan\dev3\tails-analytics-dbt\data_warehouse
  $ pipenv run sqlfluff lint -vv -p 2
  ==== sqlfluff ====
  sqlfluff:         0.6.0a1 python:             3.8.6
  dialect:        snowflake verbosity:              2
  templater:            dbt dbt:              =0.19.1
  rules:       L004, L010, L011, L014, L025
  == Raw Config:
  core:
      bench:              False
      dialect:            snowflake
      exclude_rules:      L009
      ignore:             []
      ignore_templated_areas:True
      nocolor:            False
      output_line_length: 80
      recurse:            True
      rules:              L004,L010,L011,L014,L025
      runaway_limit:      10
      sql_file_exts:      .sql,.sql.j2,.dml,.ddl
      templater:          dbt
      verbose:            2
  indentation:
      indented_joins:     False
      template_blocks_indent:True
  rules:
      allow_scalar:       True
      comma_style:        trailing
      indent_unit:        space
      max_line_length:    80
      single_table_references:consistent
      tab_space_size:     4
      unquoted_identifiers_policy:all
      L003:
          lint_templated_tokens:True
      L010:
          capitalisation_policy:lower
      L014:
          capitalisation_policy:lower
          extended_capitalisation_policy:consistent
      L016:
          ignore_comment_lines:False
      L029:
          unquoted_identifiers_policy:aliases
      L030:
          capitalisation_policy:consistent
      L038:
          select_clause_trailing_comma:forbid
      L040:
          capitalisation_policy:consistent
      L042:
          forbid_subquery_in: join
      L047:
          prefer_count_1:     False
  templater:
      unwrap_wrapped_queries:True
      jinja:
          apply_dbt_builtins: True
          macros:
              dbt_config:         {% macro config() %}{% for k in kwargs %}{% endfor %}{% endmacro %}
              dbt_is_incremental: {% macro is_incremental() %}True{% endmacro %}
              dbt_ref:            {% macro ref(model_ref) %}{{model_ref}}{% endmacro %}
              dbt_source:         {% macro source(source_name, table) %}{{source_name}}_{{table}}{% endmacro %}
              dbt_var:            {% macro var(variable) %}item{% endmacro %}
  
  ==== readout ====
  
  === [ path: C:\Users\alan\dev3\tails-analytics-dbt\data_warehouse ] ===
  
  == [C:\Users\alan\dev3\tails-analytics-dbt\data_warehouse\models\base\advertising\stg_stitch__bing_fr.sql] PASS
  == [C:\Users\alan\dev3\tails-analytics-dbt\data_warehouse\models\base\advertising\stg_stitch__bing_uk.sql] PASS
  Process SpawnPoolWorker-2:
  Traceback (most recent call last):
    File "C:\Users\alan\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
      self.run()
    File "C:\Users\alan\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 108, in run
  
      self._target(*self._args, **self._kwargs)
    File "C:\Users\alan\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
      self.run()
      result = (True, func(*args, **kwds))rams\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    File "C:\Users\alan\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 108, in run
      self._target(*self._args, **self._kwargs)
      return f()rs\alan\dev3\sqlfluff\src\sqlfluff\core\linter.py", line 1441, in _apply
    File "C:\Users\alan\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
      result = (True, func(*args, **kwds))
      return linter._lint_path_core(fname, fix)uff\core\linter.py", line 1452, in _lint_path_parallel_wrapper
    File "c:\users\alan\dev3\sqlfluff\src\sqlfluff\core\linter.py", line 1441, in _apply
      return f()
      return self.lint_string(qlfluff\src\sqlfluff\core\linter.py", line 1521, in _lint_path_core
      return linter._lint_path_core(fname, fix)uff\core\linter.py", line 1452, in _lint_path_parallel_wrapper
    File "c:\users\alan\dev3\sqlfluff\src\sqlfluff\core\linter.py", line 1237, in lint_string
      parsed = self.parse_string(in_str=in_str, fname=fname, config=config)
      return self.lint_string(qlfluff\src\sqlfluff\core\linter.py", line 1521, in _lint_path_core
    File "c:\users\alan\dev3\sqlfluff\src\sqlfluff\core\linter.py", line 914, in parse_string
      templated_file, templater_violations = self.templater.process(
      parsed = self.parse_string(in_str=in_str, fname=fname, config=config)37, in lint_string
    File "c:\users\alan\dev3\sqlfluff\src\sqlfluff\core\templaters\dbt.py", line 202, in process
      return self._unsafe_process(fname, in_str, config)
      templated_file, templater_violations = self.templater.process(line 914, in parse_string
    File "c:\users\alan\dev3\sqlfluff\src\sqlfluff\core\templaters\dbt.py", line 238, in _unsafe_process
      selected = self.dbt_selector_method.search(
      return self._unsafe_process(fname, in_str, config)templaters\dbt.py", line 202, in process
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\cached_property.py", line 36, in __get__
      value = obj.__dict__[self.func.__name__] = self.func(obj)
      selected = self.dbt_selector_method.search(f\core\templaters\dbt.py", line 238, in _unsafe_process
    File "c:\users\alan\dev3\sqlfluff\src\sqlfluff\core\templaters\dbt.py", line 128, in dbt_selector_method
      self.dbt_manifest, previous_state=None
      value = obj.__dict__[self.func.__name__] = self.func(obj)b\site-packages\cached_property.py", line 36, in __get__
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\cached_property.py", line 36, in __get__
      value = obj.__dict__[self.func.__name__] = self.func(obj)
      self.dbt_manifest, previous_state=Nonelfluff\core\templaters\dbt.py", line 128, in dbt_selector_method
    File "c:\users\alan\dev3\sqlfluff\src\sqlfluff\core\templaters\dbt.py", line 104, in dbt_manifest
      self.dbt_manifest = load_manifest(
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\parser\manifest.py", line 862, in load_manifest
      return ManifestLoader.load_all(config, macro_manifest, macro_hook)
      value = obj.__dict__[self.func.__name__] = self.func(obj)
    File "c:\users\alan\dev3\sqlfluff\src\sqlfluff\core\templaters\dbt.py", line 104, in dbt_manifest
      self.dbt_manifest = load_manifest(
      loader.load(macro_manifest=macro_manifest)use-irGXymbI\lib\site-packages\dbt\parser\manifest.py", line 442, in load_all
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\parser\manifest.py", line 862, in load_manifest
      return ManifestLoader.load_all(config, macro_manifest, macro_hook)
      self.parse_project(project, macro_manifest, old_results)ib\site-packages\dbt\parser\manifest.py", line 290, in load
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\parser\manifest.py", line 442, in load_all
      loader.load(macro_manifest=macro_manifest)
      self.parse_with_cache(path, parser, old_results)GXymbI\lib\site-packages\dbt\parser\manifest.py", line 237, in parse_project
      self.parse_project(project, macro_manifest, old_results)ib\site-packages\dbt\parser\manifest.py", line 290, in load
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\parser\manifest.py", line 188, in parse_with_cache
      parser.parse_file(block)
      self.parse_with_cache(path, parser, old_results)GXymbI\lib\site-packages\dbt\parser\manifest.py", line 237, in parse_project
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\parser\schemas.py", line 632, in parse_file
      dct = self.raw_renderer.render_data(dct)
      parser.parse_file(block)alenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\parser\manifest.py", line 188, in parse_with_cache
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\config\renderer.py", line 50, in render_data
      return deep_map(self.render_entry, data)
      dct = self.raw_renderer.render_data(dct)house-irGXymbI\lib\site-packages\dbt\parser\schemas.py", line 632, in parse_file
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\utils.py", line 217, in deep_map
      return _deep_map(func, value, ())
      return deep_map(self.render_entry, data)house-irGXymbI\lib\site-packages\dbt\config\renderer.py", line 50, in render_data
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\utils.py", line 180, in _deep_map
      ret = {
      return _deep_map(func, value, ())ta_warehouse-irGXymbI\lib\site-packages\dbt\utils.py", line 217, in deep_map
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\utils.py", line 181, in <dictcomp>
      k: _deep_map(func, v, (keypath + (str(k),)))
      ret = {Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\utils.py", line 180, in _deep_map
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\utils.py", line 175, in _deep_map
      ret = [
      k: _deep_map(func, v, (keypath + (str(k),)))e-irGXymbI\lib\site-packages\dbt\utils.py", line 181, in <dictcomp>
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\utils.py", line 176, in <listcomp>
      _deep_map(func, v, (keypath + (idx,)))
      ret = [Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\utils.py", line 175, in _deep_map
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\utils.py", line 180, in _deep_map
      ret = {
      _deep_map(func, v, (keypath + (idx,)))rehouse-irGXymbI\lib\site-packages\dbt\utils.py", line 176, in <listcomp>
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\utils.py", line 181, in <dictcomp>
      k: _deep_map(func, v, (keypath + (str(k),)))
      ret = {Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\utils.py", line 180, in _deep_map
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\utils.py", line 175, in _deep_map
      ret = [
      k: _deep_map(func, v, (keypath + (str(k),)))e-irGXymbI\lib\site-packages\dbt\utils.py", line 181, in <dictcomp>
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\utils.py", line 176, in <listcomp>
      _deep_map(func, v, (keypath + (idx,)))
      ret = [Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\utils.py", line 175, in _deep_map
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\utils.py", line 180, in _deep_map
      ret = {
      _deep_map(func, v, (keypath + (idx,)))rehouse-irGXymbI\lib\site-packages\dbt\utils.py", line 176, in <listcomp>
      k: _deep_map(func, v, (keypath + (str(k),)))e-irGXymbI\lib\site-packages\dbt\utils.py", line 181, in <dictcomp>
      ret = {Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\utils.py", line 180, in _deep_map
      ret = func(value, keypath)envs\data_warehouse-irGXymbI\lib\site-packages\dbt\utils.py", line 185, in _deep_map
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\utils.py", line 181, in <dictcomp>
      k: _deep_map(func, v, (keypath + (str(k),)))
      return self.render_value(value, keypath)house-irGXymbI\lib\site-packages\dbt\config\renderer.py", line 30, in render_entry
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\utils.py", line 185, in _deep_map
      ret = func(value, keypath)
      return get_rendered(value, self.context, native=True)I\lib\site-packages\dbt\config\renderer.py", line 41, in render_value
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\config\renderer.py", line 30, in render_entry
      return self.render_value(value, keypath)
      template = get_template(alenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\clients\jinja.py", line 575, in get_rendered
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\config\renderer.py", line 41, in render_value
      return get_rendered(value, self.context, native=True)
      return env.from_string(template_source, globals=ctx)bI\lib\site-packages\dbt\clients\jinja.py", line 528, in get_template
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\clients\jinja.py", line 582, in get_rendered
      return render_template(template, ctx, node)
      return cls.from_code(self, self.compile(source), globals, None)-packages\jinja2\environment.py", line 941, in from_string
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\clients\jinja.py", line 533, in render_template
      return template.render(ctx)
      return self._compile(source, filename)rehouse-irGXymbI\lib\site-packages\jinja2\environment.py", line 636, in compile
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\dbt\clients\jinja.py", line 184, in render
      self.root_render_func(self.new_context(vars))
      return super()._compile(source, filename)  # type: ignoreb\site-packages\dbt\clients\jinja.py", line 101, in _compile
    File "C:\Users\alan\.virtualenvs\data_warehouse-irGXymbI\lib\site-packages\jinja2\environment.py", line 1144, in new_context
      return new_context(
      return compile(source, filename, "exec")house-irGXymbI\lib\site-packages\jinja2\environment.py", line 601, in _compile
      parent = dict(globals or (), **vars)warehouse-irGXymbI\lib\site-packages\jinja2\runtime.py", line 93, in new_context
  KeyboardInterrupt
  
  Aborted!
  
  Aborted!
  </pre>
</details>

There's also quite a long delay between the first interrupt and the `Aborted!`  messages, so a message which tell people there might be a slight delay might be useful. If I press `ctrl+c` more times before then and _don't wait_, then I just get more tracebacks.

**Comment by barrywhart** [comment]
@alanmcruickshank: Ahh, or is it "arghhh" -- I see you are running on Windows. IIUC, the `multiprocessing` module works _completely differently_ on Windows due to Linux having `fork()` and Windows not having it. This PR specifically prevents child processes from "seeing" Ctrl-C events on Linux. It probably has no impact on Windows. I'll try a few tweaks, but I may need you try some experiments and possibly tinker with some things. I think we're going to see 3 sources of performance and/or behavior differences with `--parallel`:
* Operating system
* Hardware: SSDs will likely handle high levels of parallelism better than spinning disks. With spinning disks, fast serial reads can degrade into slow random reads when multiple processes are reading from disk at the same time. One possible way to address this: Have the main process read the files and pass _contents_, not paths, to the child processes.
* Nature of the SQL being linted: How many warnings are being returned, possibly the size of the files.
  * Possible improvement: Could the worker processes print their own output, rather than returning warnings to the main process? In order for this to work well, we'd need to have them take turns, so we don't get output from multiple files jumbled together.

**Comment by barrywhart** [comment]
@alanmcruickshank: I made some tweaks to this PR which should address the issues you raised:
* Now the child processes explicitly disable Ctrl-C handling at startup time. There's perhaps a narrow window at the beginning when a Ctrl-C *might* be seen by a child process (basically a race condition), but by the time the children are actually linting, they should be ignoring Ctrl-C and letting the main process handle them.
* Now the parent process explicitly detects `KeyboardInterrupt` events, prints a message saying "I'm cleaning up now", then explicitly terminates the child processes, rather than letting the automated cleanup in the pool's context manager do it.

**Comment by barrywhart** [comment]
Moving this PR back to "draft" status.  think it's a good time to refactor the parallel and serial code into separate "runner" classes. The current organic, thrown-together structure is becoming unwieldy in light of things like:
* Threading: Used only by automated tests because it's helpful for capturing coverage and works similarly, but not identically, to processes.
* Windows: Needs additional initialization since it doesn't inherit global state from the main process.

**Comment by barrywhart** [comment]
@alanmcruickshank: This is ready for another review. I think I've handled the issues you were seeing (which I believe were Windows specific). I refactored the serial/parallel processing portions of the linter into a new module `sqlfluff.core.linter.runner.py` for current readability and future extensibility. It's possible we'll need further Windows-specific changes, and this design supports that better than the previous mishmash of random functions.

**Comment by alanmcruickshank** [comment]
@barrywhart - nice! Even if I spam `ctrl+c` this works nicely 👍 . Great user feedback....

```
==== readout ====

=== [ path: C:\Users\alan\dev3\tails-analytics-dbt\data_warehouse ] ===

== [C:\Users\alan\dev3\tails-analytics-dbt\data_warehouse\models\base\advertising\stg_stitch__bing_uk.sql] PASS
== [C:\Users\alan\dev3\tails-analytics-dbt\data_warehouse\models\base\advertising\stg_stitch__bing_fr.sql] PASS
Received keyboard interrupt. Cleaning up and shutting down...
==== summary ====
files:             2 violations:        0
clean files:       2 unclean files:     0
avg per file:   0.00 unclean rate:     0%
status:         PASS

Aborted!
```

**Review by alanmcruickshank — APPROVED** [review]
This is pretty neat. Good work 👍 

I love the reusability in the different runners.

**Pull request merged**
