### PR TITLE
Per file dialect selection fix

### PR DESCRIPTION
**Pull request by LauraRichter**
### Brief summary of the change made

This change addresses this issue: https://github.com/sqlfluff/sqlfluff/issues/3559

The issue author asked for it to be possible to set the dialect per file, and a suggestion in the issue discussion was that it could be set using an in-file configuration directive. From the documentation, it reads like this should already be possible:
https://docs.sqlfluff.com/en/stable/configuration.html
with syntax like this:
```
-- sqlfluff:dialect:bigquery
```

But it doesn't work. Why?
It is because the config parameter `core.dialect` will be changed to the value provided in the file, BUT, the parameter `core.dialect_obj` is set when the FluffConfig is initialised, before the file is read in, and not updated by the inline config.

So this pull request makes the behaviour consistent - now an inline dialect directive changes both the dialect and the dialect_obj

### Are there any other side effects of this change that we should be aware of?

No

### Pull Request checklist
- [ ] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by alanmcruickshank — COMMENTED** [review]
Looks like a very sensible approach 👍 . Thanks for contributing this. I'll review properly once test suite has passed.

**Comment by greg-finley** [comment]
Thanks for the contribution! I was able to link to the related issue manually, but you could link it next time in the PR description with one of the [magic words](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Comment by LauraRichter** [comment]
> magic words

Oh I see! Thanks!

**Comment by LauraRichter** [comment]
> @LauraRichter - there's one line not covered by your tests, are you able to add an additional test case which covers it? Everything else looks good.

Will do!

**Review by greg-finley — APPROVED** [review]
Thanks, nice work! 👍

**Pull request merged**
