### PR TITLE
In addition to Codecov, also upload to Coveralls

### PR DESCRIPTION
**Pull request by barrywhart**
### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by alanmcruickshank** [comment]
Given #4195 seems to have worked, do you still want to explore this one or should we close it? I'm not against switching to coveralls if you think it will be more reliable.

**Comment by barrywhart** [comment]
I'll see if I can get it working, then I'll save the file or branch somewhere for later, if Codecov starts failing again.

**Comment by barrywhart** [comment]
I experimented with the `pip install coveralls` approach, but using the official GitHub action is probably better (because more standard?).

https://github.com/marketplace/actions/coveralls-github-action#complete-parallel-job-example

**Review by alanmcruickshank — APPROVED** [review]
Let's try it!

**Pull request merged**
