### PR TITLE
Support dbt 1.7

### LINKED ISSUE #5841: dbt `1.7.14` breaks with `ImportError: cannot import name 'read_user_config' from 'dbt.config'`
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

`dbt-core` has just released `1.7.14`; installing `dbt-core` `1.7.14`, `dbt-bigquery` `1.7.7` and the latest `sqlfluff` `3.0.5` and `sqlfluff-templater-dbt` `3.0.5` then trying to lint results in `ImportError: cannot import name 'read_user_config' from 'dbt.config'`

All else the same but using `dbt-core` `1.7.13` linting works

Probably relevant, dbt-core 1.7.14 release notes - https://github.com/dbt-labs/dbt-core/releases/tag/v1.7.14
https://github.com/dbt-labs/dbt-core/issues/9183 is mentioned and sounds like it might be relevant

### Expected Behaviour

linting should work without errors

### Observed Behaviour

linting tails with `ImportError: cannot import name 'read_user_config' from 'dbt.config'`

### How to reproduce

install `dbt-core` `1.7.14`, `dbt-bigquery` `1.7.7`, `sqlfluff` `3.0.5`, and `sqlfluff-templater-dbt` `3.0.5`
run `sqlfluff lint`

### Dialect

bigquery

### Version

 `dbt-core` `1.7.14`, `dbt-bigquery` `1.7.7`, `sqlfluff` `3.0.5`, and `sqlfluff-templater-dbt` `3.0.5`

```
python --version
Python 3.12.1
```

```
poetry run sqlfluff --version
sqlfluff, version 3.0.5
```

### Configuration

probably not relevant

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by WittierDinosaur**
### Brief summary of the change made
Fixes #5841 

Also adds dbt 1.7 to the test suite. Thanks @jtcohen6 for identifying the fix

### Are there any other side effects of this change that we should be aware of?
No

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by edgarrmondragon — APPROVED** [review]

**Review by greg-finley — APPROVED** [review]

**Comment by elyobo** [comment]
Thanks @greg-finley for such a quick resolution!

**Comment by anshjain18** [comment]
@greg-finley 
Till the time this fix gets published, what can we do to patch the fix in our dbt?
Also, I think multiple fixes are published together every 2-3 weeks. So during that duration, whats the advisable way to get those fixes in our local machines?

**Comment by edgarrmondragon** [comment]
@anshjain18 depends on how you install sqlfluff, but you can always install from the HEAD of `main`. For example, using [`pipx`](https://github.com/pypa/pipx):

```
pipx install git+https://github.com/sqlfluff/sqlfluff.git
```

**Comment by anshjain18** [comment]
@edgarrmondragon 
Should we have this automation that every PR merge triggers a patch version release automatically? I think some open-source projects do that

**Comment by elyobo** [comment]
@anshjain18 it's released now FYI - https://github.com/sqlfluff/sqlfluff/releases/tag/3.0.6

**Pull request merged**
