### PR TITLE
MySQL: Better `UNSIGNED` support

### LINKED ISSUE #3249: mysql: INT UNSIGNED datatype is not supported properly
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

In a `CREATE TABLE` statement with a field of type `INT UNSIGNED`, the keyword `UNSIGNED` is treated as a column constraint, but actually `INT UNSIGNED` is its own datatype. This implementation detail causes issues when trying to use the datatype `INT UNSIGNED` in other contexts, such as `DECLARE`'ing a variable.

### Expected Behaviour

CREATE TABLE statement:
```
% echo "CREATE TABLE t (id INT UNSIGNED)" | sqlfluff parse - --dialect mysql
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    statement:
[L:  1, P:  1]      |        create_table_statement:
[L:  1, P:  1]      |            keyword:                                          'CREATE'
[L:  1, P:  7]      |            whitespace:                                       ' '
[L:  1, P:  8]      |            keyword:                                          'TABLE'
[L:  1, P: 13]      |            whitespace:                                       ' '
[L:  1, P: 14]      |            table_reference:
[L:  1, P: 14]      |                identifier:                                   't'
[L:  1, P: 15]      |            whitespace:                                       ' '
[L:  1, P: 16]      |            bracketed:
[L:  1, P: 16]      |                start_bracket:                                '('
[L:  1, P: 17]      |                [META] indent:
[L:  1, P: 17]      |                column_definition:
[L:  1, P: 17]      |                    identifier:                               'id'
[L:  1, P: 19]      |                    whitespace:                               ' '
[L:  1, P: 20]      |                    data_type:
[L:  1, P: 20]      |                        data_type_identifier:                 'INT'
[L:  1, P: 23]      |                        whitespace:                           ' '
[L:  1, P: 24]      |                        keyword:                              'UNSIGNED'
[L:  1, P: 32]      |                [META] dedent:
[L:  1, P: 32]      |                end_bracket:                                  ')'
[L:  1, P: 33]      |    newline:                                                  '\n'
```

DECLARE statement:
```
% echo "DECLARE x INT UNSIGNED;" | sqlfluff parse - --dialect mysql
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    statement:
[L:  1, P:  1]      |        declare_statement:
[L:  1, P:  1]      |            keyword:                                          'DECLARE'
[L:  1, P:  8]      |            whitespace:                                       ' '
[L:  1, P:  9]      |            variable:                                         'x'
[L:  1, P: 10]      |            whitespace:                                       ' '
[L:  1, P: 11]      |            data_type:
[L:  1, P: 11]      |                data_type_identifier:                         'INT'
[L:  1, P: 11]      |                whitespace:                                   ' '
[L:  1, P: 11]      |                keyword:                                      'UNSIGNED'
[L:  1, P: 14]      |    statement_terminator:                                     ';'
[L:  1, P: 15]      |    newline:                                                  '\n'
```

### Observed Behaviour

CREATE TABLE statement:
```
% echo "CREATE TABLE t (id INT UNSIGNED)" | sqlfluff parse - --dialect mysql
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    statement:
[L:  1, P:  1]      |        create_table_statement:
[L:  1, P:  1]      |            keyword:                                          'CREATE'
[L:  1, P:  7]      |            whitespace:                                       ' '
[L:  1, P:  8]      |            keyword:                                          'TABLE'
[L:  1, P: 13]      |            whitespace:                                       ' '
[L:  1, P: 14]      |            table_reference:
[L:  1, P: 14]      |                identifier:                                   't'
[L:  1, P: 15]      |            whitespace:                                       ' '
[L:  1, P: 16]      |            bracketed:
[L:  1, P: 16]      |                start_bracket:                                '('
[L:  1, P: 17]      |                [META] indent:
[L:  1, P: 17]      |                column_definition:
[L:  1, P: 17]      |                    identifier:                               'id'
[L:  1, P: 19]      |                    whitespace:                               ' '
[L:  1, P: 20]      |                    data_type:
[L:  1, P: 20]      |                        data_type_identifier:                 'INT'
[L:  1, P: 23]      |                    whitespace:                               ' '
[L:  1, P: 24]      |                    column_constraint_segment:
[L:  1, P: 24]      |                        keyword:                              'UNSIGNED'
[L:  1, P: 32]      |                [META] dedent:
[L:  1, P: 32]      |                end_bracket:                                  ')'
[L:  1, P: 33]      |    newline:                                                  '\n'
```

DECLARE statement:
```
% echo "DECLARE x INT UNSIGNED;" | sqlfluff parse - --dialect mysql
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    statement:
[L:  1, P:  1]      |        declare_statement:
[L:  1, P:  1]      |            keyword:                                          'DECLARE'
[L:  1, P:  8]      |            whitespace:                                       ' '
[L:  1, P:  9]      |            variable:                                         'x'
[L:  1, P: 10]      |            whitespace:                                       ' '
[L:  1, P: 11]      |            data_type:
[L:  1, P: 11]      |                data_type_identifier:                         'INT'
[L:  1, P: 14]      |        unparsable:                                           !! Expected: 'Nothing...'
[L:  1, P: 14]      |            whitespace:                                       ' '
[L:  1, P: 15]      |            raw:                                              'UNSIGNED'
[L:  1, P: 23]      |    statement_terminator:                                     ';'
[L:  1, P: 24]      |    newline:                                                  '\n'

==== parsing violations ====
L:   1 | P:  14 |  PRS | Line 1, Position 14: Found unparsable section: ' UNSIGNED'
```

### How to reproduce

See above.

### Dialect

mysql

### Version

```
% sqlfluff --version
sqlfluff, version 0.13.0

% python --version
Python 2.7.16

% python3 --version
Python 3.9.12
```

### Configuration

None/default.

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### LINKED ISSUE #3429: Parse error in Redshift dialect in CREATE TABLE expression with IDENTITY column
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

A `CREATE TABLE` expression with an `IDENTITY` column throws a parse error in the redshift dialect of sqlfluff.

### Expected Behaviour

I expected this SQL to be parsed without error. It is valid Redshift SQL (indeed, this sql statement is copied from [the AWS documentation](https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_TABLE_examples.html#r_CREATE_TABLE_NEW-create-a-table-with-default-identity-column).

### Observed Behaviour

A parse error is thrown when this SQL is linted:

```
$ sqlfluff lint
== [/Users/matt/sandbox/sqlfluff-redshift-mwe/create_table.sql] FAIL
L:   1 | P:   1 |  PRS | Line 1, Position 1: Found unparsable section: 'CREATE
                       | TABLE t1(\n hist_id BIGINT IDENTI...'
L:   4 | P:  27 | L005 | Commas should not have whitespace directly before them.
All Finished!
```

Here's the output of running `sqlfluff lint -vvvvv`: [error.log](https://github.com/sqlfluff/sqlfluff/files/8846098/error.log)

### How to reproduce

Minimal example is [in this git repository](https://github.com/menzenski/sqlfluff-redshift-mwe):

`create_table.sql` file:
```sql
CREATE TABLE t1(
  hist_id BIGINT IDENTITY NOT NULL, /* Cannot be overridden */
  base_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, /* Can be overridden */
  business_key varchar(10) ,
  some_field varchar(10)
);
```

`.sqlfluff` file:
```toml
[sqlfluff]
dialect = redshift
```

If the `IDENTITY` / `GENERATED BY DEFAULT AS IDENTITY` are removed, this SQL is parsed without error:

`create_table.sql` file: 
```sql
CREATE TABLE t1(
  hist_id BIGINT NOT NULL, /* Cannot be overridden */
  base_id BIGINT NOT NULL, /* Can be overridden */
  business_key varchar(10) ,
  some_field varchar(10)
);
```

### Dialect

Redshift

### Version

```shell
$ sqlfluff --version
sqlfluff, version 0.13.2
```

```shell
$ python -V
Python 3.9.11
```

### Configuration

`.sqlfluff` file:

```toml
[sqlfluff]
dialect = redshift
```

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by tunetheweb**
### Brief summary of the change made

Fixes #3249

### Are there any other side effects of this change that we should be aware of?
Shouldn't be as was in ANSI anyway

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by barrywhart — COMMENTED** [review]
I notice there are no new tests in this PR. Is this something we should test (and is there a reasonable way to do so)?

**Comment by tunetheweb** [comment]
The parse tree has changed:

image

That is the test.

**Comment by tunetheweb** [comment]
Note the original issue had this:

> In a CREATE TABLE statement with a field of type INT UNSIGNED, the keyword UNSIGNED is treated as a column constraint, but actually INT UNSIGNED is its own datatype.

As you can see from the parse tree, the `UNSIGNED` is no longer a column constraint and is now part of the datatype - as requested.

**Review by WittierDinosaur — APPROVED** [review]
LGTM

**Pull request merged**
