### PR TITLE
L027: Check table aliases exists

### LINKED ISSUE #2992: BigQuery: Accessing `STRUCT` elements evades triggering L027
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Accessing unreferenced `STRUCT` elements using BigQuery dot notation in a multi table query does not trigger L027.

### Expected Behaviour

L027 gets triggered.

### Observed Behaviour

L027 does not get triggered.

### How to reproduce

```sql
SELECT
    t1.col1,
    t2.col2,
    events.id
FROM t_table1 AS t1
LEFT JOIN t_table2 AS t2
    ON TRUE
```

### Dialect

BigQUery

### Version

`0.11.2` using online.sqlfluff.com

### Configuration

N/A

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by dmohns**
### Brief summary of the change made

Fixes #2992

The idea of this PR is to add the functionality to L027 to check whether a qualified reference is actually *valid*, i.e. exists in the list of valid table/view references.

Overall, this seems to be working and covering all test cases correctly. However, the way it is implemented feels pretty hacky and I cannot get rid of the feeling that there is a better way of doing it. 

Also, I'm not sure if it is within SQLFluff design to allow a single rule to trigger different `LintResult` s.

### Are there any other side effects of this change that we should be aware of?

Depending on the quality of `table_aliases` and `standalone_aliases` there might be valid SQL's which's aliases are not correctly resolved by them. In this case, L027 would fire incorrectly. However, we seem to not cover such a case in existing SQLs.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by tunetheweb** [comment]
I think we should go with this. Doesn't look too hacky to me.

It might lead to a few double reporting of issues as per https://github.com/sqlfluff/sqlfluff/issues/2992#issuecomment-1088106451 but think that's OK.

@barrywhart could you have a review and a read of above comment and see what you think?

**Comment by dmohns** [comment]
Ok, cool. I'm changing this from Draft -> Ready for Review. Let me know what you think about making the check for valid references a configurable option to L027 which is disabled by default, as part of the review.

**Comment by barrywhart** [comment]
@dmohns: What do you mean by this?
>I'm not sure if it is within SQLFluff design to allow a single rule to trigger different `LintResult`s.

The `_eval()` function can return multiple `LintResult` objects. See rule L034, for example.

**Review by barrywhart — APPROVED** [review]

**Comment by barrywhart** [comment]
Looks good to me!

**Pull request merged**
