### PR TITLE
Issue 1395: Add support for SnowSQL variables

### PR DESCRIPTION
**Pull request by samlader**
### Brief summary of the change made

This is the first time I'm contributing to SQLFluff, please treat this PR as an initial draft and give me guidance on whether the approach I've taken here is correct or if there's any changes I can make to improve this PR. 🙂 

This PR adds support for SnowSQL variables, which makes progress on issue #1395. 

### Are there any other side effects of this change that we should be aware of?

These changes expand the current definition of referenced variable names. I am not aware of any side effects.

### Pull Request checklist
- [X] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/parser` (note YML files can be auto generated with `python test/generate_parse_fixture_yml.py` or by running `tox` locally).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by tunetheweb** [comment]
Looking pretty good to me! Let’s see what the CI run says.

**Review by tunetheweb — APPROVED** [review]
I’m happy with this change and think it’s good to merge. Let me know if all done or still adding to it?

**Comment by samlader** [comment]
Brill, I'm happy for you to merge! 🙌

**Comment by tunetheweb** [comment]
Good job! And welcome onboard as a contributor! 😁

Hopefully now you’ve seen how to add to dialects you’ll consider future PRs too! Would be great to have an actual Snowflake user look at the other [Snowflake issues](https://github.com/sqlfluff/sqlfluff/labels/snowflake)! Fixed some myself and was going to look at these but don’t use it at all so easy to make mistakes.

**Pull request merged**
