### PR TITLE
Postgres :  Add `ALTER AGGREGATE` Statement

### LINKED ISSUE #3556: [postgres] aggregate DDL: unparseable section
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Receiving parsing errors while linting aggregate-related PostgreSQL DDL.

### Expected Behaviour

No parsing errors.

### Observed Behaviour

```
==== sqlfluff ====
sqlfluff:                1.1.0 python:                 3.8.10
implementation:        cpython verbosity:                   1
dialect:              postgres templater:               jinja
rules:                                all
==== readout ====

=== [ path: 2022-07-05.aggregate.sql ] ===

== [2022-07-05.aggregate.sql] FAIL                                                                                                                                                
L:   1 | P:   1 |  PRS | Line 1, Position 1: Found unparsable section: 'CREATE
                       | AGGREGATE range_agg_preserve_gaps...'
L:   8 | P:   1 |  PRS | Line 8, Position 1: Found unparsable section: 'CREATE OR
                       | REPLACE AGGREGATE range_agg_pr...'
L:  15 | P:   1 |  PRS | Line 15, Position 1: Found unparsable section: 'ALTER
                       | AGGREGATE range_agg_preserve_gaps ...'
L:  17 | P:   1 |  PRS | Line 17, Position 1: Found unparsable section: 'ALTER
                       | AGGREGATE my_agg (TSTZRANGE) OWNER...'
L:  18 | P:   1 |  PRS | Line 18, Position 1: Found unparsable section: 'ALTER
                       | AGGREGATE my_agg (TSTZRANGE) OWNER...'
L:  19 | P:   1 |  PRS | Line 19, Position 1: Found unparsable section: 'ALTER
                       | AGGREGATE my_agg (TSTZRANGE) OWNER...'
L:  20 | P:   1 |  PRS | Line 20, Position 1: Found unparsable section: 'ALTER
                       | AGGREGATE my_agg (TSTZRANGE) OWNER...'
L:  22 | P:   1 |  PRS | Line 22, Position 1: Found unparsable section: 'ALTER
                       | AGGREGATE my_agg (*) SET SCHEMA ap...'
L:  24 | P:   1 |  PRS | Line 24, Position 1: Found unparsable section: 'DROP
                       | AGGREGATE IF EXISTS my_agg (*) CASC...'
WARNING: Parsing errors found and dialect is set to 'postgres'. Have you configured your dialect correctly?
==== summary ====
violations:        9 status:         FAIL
All Finished!
```

### How to reproduce

Reproducible as above with the following file `2022-07-05.aggregate.sql`:
```sql
CREATE AGGREGATE range_agg_preserve_gaps (TSTZRANGE)
(
    sfunc = tstzrange_arr_merge,
    stype = TSTZRANGE[],
    initcond = '{}'
);

CREATE OR REPLACE AGGREGATE range_agg_preserve_gaps (TSTZRANGE)
(
    sfunc = tstzrange_arr_merge,
    stype = TSTZRANGE[],
    initcond = '{}'
);

ALTER AGGREGATE range_agg_preserve_gaps (TSTZRANGE) RENAME TO my_agg;

ALTER AGGREGATE my_agg (TSTZRANGE) OWNER TO me;
ALTER AGGREGATE my_agg (TSTZRANGE) OWNER TO CURRENT_ROLE;
ALTER AGGREGATE my_agg (TSTZRANGE) OWNER TO CURRENT_USER;
ALTER AGGREGATE my_agg (TSTZRANGE) OWNER TO SESSION_USER;

ALTER AGGREGATE my_agg (*) SET SCHEMA api;

DROP AGGREGATE IF EXISTS my_agg (*) CASCADE;
```

### Dialect

postgres

### Version

```
sqlfluff:                1.1.0 python:                 3.8.10
implementation:        cpython verbosity:                   1
dialect:              postgres templater:               jinja
rules:                                all
```

### Configuration

defaults

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by R3gardless**
### Brief summary of the change made

Support for parsing `ALTER AGGREGATE` statements in PostgreSQL.

- fix #3556 

### Are there any other side effects of this change that we should be aware of?
None

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
```SQL
ALTER AGGREGATE range_agg_preserve_gaps (TSTZRANGE) RENAME TO my_agg;

ALTER AGGREGATE my_agg (TSTZRANGE) OWNER TO me;
ALTER AGGREGATE my_agg (TSTZRANGE) OWNER TO CURRENT_ROLE;
ALTER AGGREGATE my_agg (TSTZRANGE) OWNER TO CURRENT_USER;
ALTER AGGREGATE my_agg (TSTZRANGE) OWNER TO SESSION_USER;

ALTER AGGREGATE my_agg (*) SET SCHEMA api;

ALTER AGGREGATE complex_agg_function(integer, text, numeric)
RENAME TO renamed_agg_function;
```
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by R3gardless** [comment]
When looking at the code, both `DropAggregateStatementSegment` and `CreateAggregateStatementSegment` use `ObjectReferenceSegment`, but I'm not sure if it should be `FunctionNameSegment` instead. Which one is correct?

**Comment by R3gardless** [comment]
Thanks for the reply. 
I’m not very familiar with the inner architecture of PostgreSQL. If an `Aggregate Function` wraps a `Function` objects, I would prefer using `ObjectReferenceSegment`. Otherwise, I think using `FunctionNameSegment` would be better.

**Comment by R3gardless** [comment]
@alanmcruickshank Finally I use `ObjectReferenceSegment` because I'm not entirely sure if `FunctionNameSegment` is the right choice.

**Review by alanmcruickshank — APPROVED** [review]
LGTM! Thanks for the edit. I think it's probably the right call for now.

**Pull request merged**
