### PR TITLE
Fix issue with inline ignores not respecting comment lines

### LINKED ISSUE #1977: Disable rule inline doesn't work for commented sections of code
## Expected Behaviour

Adding -- noqa: L016 to the end of a commented line should ignore the 'Line too long' rule

## Observed Behaviour

Rule still fails for commented line even with the --noqa addition

## Steps to Reproduce

-- kkajshdkjhndkndansdjkasndjks knasdkasdkjaskjdhkajhdjkadn kahdkahnsjkdhkajdiundueubebd dkldkkljdalsd -- noqa: L016

## Dialect

Snowflake

## Version

SQLFluff v 0.8.2, Python v 3.8.2

## Configuration

```
[sqlfluff]
verbose = 0
nocolor = False
dialect = snowflake
templater = jinja
rules = None
exclude_rules = None
recurse = 0
output_line_length = 80
runaway_limit = 10
ignore_templated_areas = True
sql_file_exts = .sql,.sql.j2,.dml,.ddl

[sqlfluff:indentation]
indented_joins = False
template_blocks_indent = True

[sqlfluff:templater]
unwrap_wrapped_queries = True

[sqlfluff:templater:jinja]
apply_dbt_builtins = True

[sqlfluff:templater:jinja:macros]
# Macros provided as builtins for dbt projects
dbt_ref = {% macro ref(model_ref) %}{{model_ref}}{% endmacro %}
dbt_source = {% macro source(source_name, table) %}{{source_name}}_{{table}}{% endmacro %}
dbt_config = {% macro config() %}{% for k in kwargs %}{% endfor %}{% endmacro %}
dbt_var = {% macro var(variable) %}item{% endmacro %}
dbt_is_incremental = {% macro is_incremental() %}True{% endmacro %}

[sqlfluff:rules]
tab_space_size = 4
max_line_length = 80
indent_unit = space
comma_style = trailing
allow_scalar = False
single_table_references = unqualified
unquoted_identifiers_policy = all

[sqlfluff:rules:L003]
lint_templated_tokens = True

[sqlfluff:rules:L010]
capitalisation_policy = upper

[sqlfluff:rules:L014]
extended_capitalisation_policy = lower

[sqlfluff:rules:L016]
ignore_comment_lines = False

[sqlfluff:rules:L029]
unquoted_identifiers_policy = aliases

[sqlfluff:rules:L030]
capitalisation_policy = lower

[sqlfluff:rules:L038]
select_clause_trailing_comma = forbid

[sqlfluff:rules:L040]
capitalisation_policy = upper

[sqlfluff:rules:L042]
forbid_subquery_in = both

[sqlfluff:rules:L047]
prefer_count_1 = False
```

### PR DESCRIPTION
**Pull request by jpy-git**
### Brief summary of the change made

Fixes #1977. Inline ignores weren't being processed on comment lines leading to issues like seen in the issue and the screenshot below. The fix is very simple.

image

### Are there any other side effects of this change that we should be aware of?
No

### Pull Request checklist
- [X] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `python test/generate_parse_fixture_yml.py` or by running `tox` locally).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by jpy-git** [comment]
Just looking up where to add inline ignore tests for this.

**Comment by tunetheweb** [comment]
Should we add a test case?

**Comment by tunetheweb** [comment]
Ah missed your comment!

**Comment by jpy-git** [comment]
@tunetheweb I've added the unit tests now 😄

**Comment by tunetheweb** [comment]
Probably getting really picky here but I presume this handles other inline comments too (I think it does but not sure)?

```sql
this_is_not_so_big a # Hash inline comment --noqa: L012
this_is_not_so_big a /* Full inline comment */ --noqa: L012
```

Should we add test cases just to be sure?

**Comment by jpy-git** [comment]
@tunetheweb got those extra unit tests added now 👍

**Review by tunetheweb — APPROVED** [review]

**Review by barrywhart — APPROVED** [review]

**Comment by jpy-git** [comment]
LGTM 🚀

**Pull request merged**
