### PR TITLE
Stop adding trailing os.sep if ignore file is on the root of the file…

### LINKED ISSUE #4181: Sqlfluffignore file isn't read if it is located at the filesystem root of a Linux system
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.


### What Happened

We lint our codebase using sqlfluff. We deploy our entire codebase in the root of the filesystem of a docker container during CI\CD. We have one, master .sqlfluffignore that resides at the root of the project, consequently, this .sqlfluffignore is also located at the root of the filesystem.

The function paths_from_path in linter.py adds an os.sep character at the end of the base where .sqlfluffignore is found which is the way to go in almost all cases except for when the .sqlfluffignore file is found at the root. Then, all gitignore-like path specifications to ignore are built from '//.sqlfulffignore'. 

### Expected Behaviour

````bash
root@e8d186c674fb:/# sqlfluff lint --format human sql/some/path/00_copy_logs_from_s3.sql 
WARNING    Exact file path sql/some/path/00_copy_logs_from_s3.sql was given but it was ignored by a .sqlfluffignore pattern in /, re-run with `--disregard-sqlfluffignores` to skip .sqlfluffignore 
All Finished 📜 🎉!
root@e8d186c674fb:/# 
````

### Observed Behaviour

````bash
root@e8d186c674fb:/# sqlfluff lint --format human sql/some/path/00_copy_logs_from_s3.sql 
matching:   0%|                                                                                                                                                                                                             | 0/3467 [00:00<?, ?it/s]
````

### How to reproduce

Dockerfile: 
````Dockerfile
FROM python:3

COPY . .

RUN mkdir -p some/path/ &&\
         mv test.sql some/path/

RUN pip install sqlfluff

CMD ["sqlfluff lint --format human some/path/test.sql"]
````

### Dialect

Redshift

### Version

1.4.1

### Configuration


### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by baa-ableton**
… system

### Brief summary of the change made

fixes #4181 

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by alanmcruickshank — APPROVED** [review]
I can't think of a good way of testing this sensibly, so I'm happy for it to go through without a unit test.

Thanks for the contribution!

**Comment by baa-ableton** [comment]
Hello @alanmcruickshank ,

I made 1 new commit to pass linting tests. As for Windows tests, I don't work with windows systems much, and I dont want to keep pinging you to run testing. From what I can tell from the previous tests' run is that the ignore file is not being read in windows systems after my change. I guess the "/" is not sitting well with windows systems. I am thinking of:

`               abs_ignore_base + "" if abs_ignore_base == os.sep else os.sep` 

in order to make the line OS-agnostic. What do you think?

**Comment by baa-ableton** [comment]
@alanmcruickshank ,

I rewrote my if expression to comply with both OS families. I think all should be good now when the tests are run.

**Comment by baa-ableton** [comment]
Team, please let me know if you need anything else from me. The tests are passing now but a 'codecov/project' is expected and I'm not sure what that is :)

**Comment by barrywhart** [comment]
The codecov check is prone to get stuck. I'll see if I can unstick it.

**Comment by alanmcruickshank** [comment]
I've put together a different PR (#4195) to try and sort the codecov issues, but I don't think this PR can actually change the coverage - so I'll manually force it through for this one.

**Pull request merged**
