### PR TITLE
#692: Convert Python relative imports to absolute

### LINKED ISSUE #692: Relative vs absolute imports
Following on from https://github.com/sqlfluff/sqlfluff/pull/688#discussion_r559233302:

@alanmcruickshank 
> Imports appear inconsistent within the file (some are absolute and some are relative). If this isn't necessary I think we should be consistent and make them relative. If there are some occasions where absolute references are necessary then this should be documented with a comment to say why.

@me
> ...my understanding is that absolute imports are preferred over relative. Where I had to adjust/add an import, I went for absolute, but didn't touch the rest. The main reason is that an absolute import is visually far more expressive in terms of project structure, and and it's easier to fix issues too if the project structure moves around with a find and replace vs relative imports. We should definitely be consistent though - I'll make an issue to decide one way or the other, let's make the decision there and take action in another PR?

Any other opinions on this?

### PR DESCRIPTION
**Pull request by barrywhart**
Resolves #692.

I ran a tool called [`absolute_imports`](https://pypi.org/project/abs-imports/), which updated the imports automatically. It seems to work correctly. I noticed that many (but not all) of the files show in `git diff` and GitHub as **every line changed**. I suspect but have not confirmed that these files were using Windows line endings.

**Because of this, if we merge the PR, the file history (`git diff`, `git blame`) will be a bit weird. For the affected files, it'll look as if I changed every line.** If this is a concern, I can look at generating a version of this PR that does not have this behavior (probably hacking some fancier whitespace/newline handling into the `absolute_imports` tool).

For the same reason, I recommend reviewing this PR using the GitHub option that [hides whitespace changes](https://github.blog/2018-05-01-ignore-white-space-in-code-review/).

### CODE REVIEW

**Comment by dmateusp** [comment]
@barrywhart I imagine one of the reasons this is failing, is the `src.sqlfluff...` rather than `sqlfluff.`

For the tabs vs spaces and windows vs unix spaces, I suggest we figure out some way to have these be consistent on the code-base, and we merge that as a separate PR

**Comment by alanmcruickshank** [comment]
> @barrywhart I imagine one of the reasons this is failing, is the `src.sqlfluff...` rather than `sqlfluff.`

Agreed.

> For the tabs vs spaces and windows vs unix spaces, I suggest we figure out some way to have these be consistent on the code-base, and we merge that as a separate PR

@dmateusp - do you know a good way of enforcing or linting this? I think it's a great idea - and also something really hard to manually enforce or police.

**Comment by dmateusp** [comment]
@alanmcruickshank in our dbt project we use a pre-commit hook:

```
    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.1.9
      hooks:
        # converts tabs to whitespaces for indentation
        # (ignores Makefiles by default)
        - id: remove-tabs
```

Seems to fix the windows vs unix issues for us

**Comment by barrywhart** [comment]
Heh, great catch re: the `src.` thing. After all the failures, the thought crossed my mind, but I promptly forgot about it. I'll try and circle back to this next week using the correct base directory and preserving line endings, etc.

**Comment by barrywhart** [comment]
Closing this PR due to line ending and `src/` directory issues. I'll open a new, hopefully better one.

**Pull request closed without merging**
