### PR TITLE
Teradata: Database statement and Set Session Database

### LINKED ISSUE #1675: Enable DATABASE command for Teradata
Teradata has some commands to set the database schema.

`SS DATABASE`/`SET SESSION DATABASE`: https://docs.teradata.com/r/eWpPpcMoLGQcZEoyt5AjEg/3349cznZ3~nbYO3d726_aA
`DATABASE`: https://forgetcode.com/teradata/1095-setting-default-database

## Expected Behaviour

In Hive, we do have the `USE` command implemented.

```
echo "USE databasename;" | sqlfluff parse --dialect hive -
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    statement:
[L:  1, P:  1]      |        use_statement:
[L:  1, P:  1]      |            keyword:                                          'USE'
[L:  1, P:  4]      |            whitespace:                                       ' '
[L:  1, P:  5]      |            database_reference:
[L:  1, P:  5]      |                identifier:                                   'databasename'
[L:  1, P: 17]      |    statement_terminator:                                     ';'
[L:  1, P: 18]      |    newline:                                                  '\n'
```

The goal would be to parse the Teradata command similarly.

## Observed Behaviour

```
echo "DATABASE hello;" | sqlfluff parse --dialect teradata -
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    statement:
[L:  1, P:  1]      |        unparsable:                                           !! Expected: 'StatementSegment'
[L:  1, P:  1]      |            raw:                                              'DATABASE'
[L:  1, P:  9]      |            whitespace:                                       ' '
[L:  1, P: 10]      |            raw:                                              'hello'
[L:  1, P: 15]      |    statement_terminator:                                     ';'
[L:  1, P: 16]      |    newline:                                                  '\n'
```

## Steps to Reproduce

The following commands all fail:

```
echo "DATABASE hello;" | sqlfluff parse --dialect teradata -
echo "SS DATABASE hello;" | sqlfluff parse --dialect teradata -
echo "SET SESSION DATABASE hello;" | sqlfluff parse --dialect teradata -
```

(Set session appears to be used for multiple other things, that might be a separate ticket.)

## Dialect

Teradata

## Version

sqlfluff==0.7.0
python==3.9.6

## Configuration

Default.

### PR DESCRIPTION
**Pull request by mdahlman**
### Brief summary of the change made

fixes #1675

### Are there any other side effects of this change that we should be aware of?
None

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - 2 new `.sql`/`.yml` parser test cases

### CODE REVIEW

**Comment by tunetheweb** [comment]
You need to resolve the conflict in `test/fixtures/dialects/postgres/postgres_create_function.yml` and merge to main. At the moment the Files tab is showing too many differences.

On that, can you reset your main branch before your next PR? That will avoid this AND avoid the huge commit history you see in each of your PRs.

Here's some details on that (including my personally, preferred way of managing this): https://github.com/sqlfluff/sqlfluff/wiki/Git-Guide#resyncing-your-main-branch-to-upstream

**Comment by mdahlman** [comment]
Is it too late to clean things up for this PR?
Yes, I can certainly fix this ahead of the next one.

**Comment by tunetheweb** [comment]
It fine for this one. Just for next time. Just need merge in main and regen the YAMLs to resolve the conflict and should be good.

**Review by tunetheweb — APPROVED** [review]
LGTM!

**Pull request merged**
