### PR TITLE
T-SQL: Parameter assignment in SELECT vs alias

### LINKED ISSUE #5678: [TSQL] AL09 throws an AssertionError where assigning variables in a select statement
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When having sqlfluff run fix on query where the variables are assigned in a select statement, AL09 will throw an error.

sqlfluff\rules\aliasing\AL09.py", line 99, in _eval
    assert whitespace and column_identifier and alias_identifier
AssertionError

### Expected Behaviour

It should be able to handle this valid sql statement.

### Observed Behaviour

It will throw an exception during the fix

sqlfluff\rules\aliasing\AL09.py", line 99, in _eval
    assert whitespace and column_identifier and alias_identifier
AssertionError

if I run lint it will give this error:
L:   4 | P:   1 | AL09 | Unexpected exception: ;
Could you open an issue at
                       | https://github.com/sqlfluff/sqlfluff/issues ?
You can
                       | ignore this exception for now, by adding '-- noqa: AL09'
                       | at the end
of line 4

                       | [aliasing.self_alias.column]

### How to reproduce

created simple query:
declare @variable nvarchar(50)

select @variable = Column1
from Table1
where Column2 = 'test'

and ran sqlfluff fix against that query.

### Dialect

tsql

### Version

3.0.1

### Configuration

[sqlfluff]
dialect = tsql
max_line_length = 120
 #RF06 Exclude forcing Quoted Identifier 
 #CV01 Exclude using != over <>
 #ST06 Exclude column reordering
exclude_rules = RF06, CV01, ST06
large_file_skip_byte_limit = 0
processes = -1

[sqlfluff:rules:layout.long_lines]
ignore_comment_lines = True
ignore_comment_clauses = True

[sqlfluff:layout:type:comma]
spacing_after = touch
line_position = leading

[sqlfluff:rules:capitalisation.identifiers]
ignore_words = dbo
#don't mess with Kronos tables that start with lower case t
ignore_words_regex = ^t[A-z][A-z]*$
extended_capitalisation_policy = pascal

[sqlfluff:indentation]
indent_joins = False
indent_unit = tab
indented_using_on = True
allow_implicit_indents = True
indented_on_contents = False

[sqlfluff:rules:references.special_chars]
ignore_words_regex = ([$(])

[sqlfluff:rules:capitalisation.types]
extended_capitalisation_policy = lower

[sqlfluff:rules:aliasing.table]
aliasing = explicit

[sqlfluff:rules:aliasing.column]
aliasing = explicit

[sqlfluff:rules:aliasing.length]
min_alias_length = 2

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by drjwelch**
### Brief summary of the change made

Fixes #5678 

AltAliasExpressionSegment can be matched by ParameterNameSegment (i.e. a SELECT projection that looks like @myparam = mycolumn).  AT09 tries to obtain `alias_identifier` from this segment, but it only looks for naked_identifier or quoted_identifier types and ParameterNameSegment is of type "parameter".  There are no matches and the resulting alias_identifier is None and fails the the assertion.

### Are there any other side effects of this change that we should be aware of?
Statement was wrongly classified and linted as an alias; this change fixes that without any other side effect.  All tests pass.

### Pull Request checklist
- [X] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`. N/A
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`). YES
  - Full autofix test cases in `test/fixtures/linter/autofix`. N/A
  - Other.
- Added appropriate documentation for the change. N/A - commented on issue
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by WittierDinosaur — APPROVED** [review]
LGTM

**Comment by greg-finley** [comment]
@drjwelch thanks for the contribution! Could you try generating the fixtures again? See failed CI test for details.

**Comment by greg-finley** [comment]
Hmm, I think you have done a bad merge. Could you try to clean it up or open a fresh PR?

**Comment by drjwelch** [comment]
Sorry, I'll start again; I couldn't work out if the CI check had a failing test (on create_function) or just a bad YAML hash, but I'm pretty sure I followed the instructions for the latter.

**Comment by greg-finley** [comment]
No worries, feel free to tag me in the new PR

**Pull request closed without merging**
