### PR TITLE
Postgres: Add Support for PostGIS operators

### LINKED ISSUE #4260: Support PostGIS operators
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Most of our needs are well handled by the PostgreSQL dialect, but there is at least one operator (`<->`) specific to PostGIS that keeps causing parsing to fail. I suspect at least a few of the other operators would cause similar problems, though I just haven't encountered them much in my code yet. 

https://postgis.net/docs/reference.html#Operators

Another issue (https://github.com/sqlfluff/sqlfluff/issues/1290) led to PostGIS data types being included in the postgres dialect, but perhaps it would be better and more accurate to spin off a PostGIS sub-dialect. 

### Use case

I would love for SQLFluff to fully support PostgreSQL's PostGIS extension. 

### Dialect

PostgreSQL

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by WittierDinosaur**
### Brief summary of the change made
Fixes #4260 

### Are there any other side effects of this change that we should be aware of?
Yes. I had to remove the multi-character JSON operators from the lexer (they shouldn't have been there in the first place). This has, in turn, caused some allocations of operators to change. Postgres has the same syntax for multiple types of operators, so this is unavoidable. This shouldn't cause any significant regression - the raw of the operator remains the same. We may change which these default to in the future.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by burhanyasar** [comment]
Hi, thanks for creating the great stuff here! I was happy to find it out and add it to our project; however, we then ended up using postgis and things started failing.

I assume the pipeline logs aren't available anymore since the PR is old.

I have checked out this branch, merged the latest main into it locally. Then, when I run the fixture generation command. I get an issue with duckdb dialect.

```
python test/generate_parse_fixture_yml.py
```

The problem seems below, lambda arrow is not evaluating?
```
SELECT COLUMNS(c -> c = '%num%') FROM addresses;
```

If I comment out that line in select_columns.sql, I get the full generation working on all dialects and tests run, and it looks like only failures on this lambda arrow remain.

Following the changes in this PR, I tried to add the string lexer for lambda arrow before the like operator in duckdb dialect and that could solve the generation issue for select columns but then caused issues in json examples.

If anyone can hint me to some direction, how I should approach it etc. I can try finalizing the PR or help in any way I can.

**Comment by burhanyasar** [comment]
Also, the output from the parse command `python src/sqlfluff parse --dialect duckdb test/fixtures/dialects/duckdb/select_columns.sql`

```
 start_bracket:                    '('
[L:  2, P: 16]      |                            [META] indent:
[L:  2, P: 16]      |                            unparsable:                       !! Expected: "<Ref: 'ColumnsExpressionFunctionContentsSegment'> to start sequence. Found <WordSegment: ([L:  2, P: 16]) 'c'>"
[L:  2, P: 16]      |                                word:                         'c'
[L:  2, P: 17]      |                                whitespace:                   ' '
[L:  2, P: 18]      |                                minus:                        '-'
[L:  2, P: 19]      |                                greater_than:                 '>'
[L:  2, P: 20]      |                                whitespace:                   ' '
[L:  2, P: 21]      |                                word:                         'c'
[L:  2, P: 22]      |                                whitespace:                   ' '
[L:  2, P: 23]      |                                word:                         'LIKE'
[L:  2, P: 27]      |                                whitespace:                   ' '
[L:  2, P: 28]      |                                single_quote:                 "'%num%'"
[L:  2, P: 35]      |                            [META] dedent:
[L:  2, P: 35]      |                            end_bracket:                      ')'

```

**Comment by WittierDinosaur** [comment]
Hey @burhanyasar - absolutely feel free to take over this, or create a branch in parallel to fix it. I never came back to this after the initial PR. I kind of dislike the approach I took with this, which is why I never picked it up again. I think the proper way really is to lex the different combinations separately, rather than to concatenate them in the parser. But yeah, if you want to pick this up, go for it.

**Comment by burhanyasar** [comment]
@WittierDinosaur created this PR here: https://github.com/sqlfluff/sqlfluff/pull/5830

**Comment by WittierDinosaur** [comment]
Superseded by #5830

**Pull request closed without merging**
