### PR TITLE
L025: Derived query requires alias -- also handle UNION, etc.

### LINKED ISSUE #3547: tsql: code corruption alias removed L025
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I have the following query

``` 
SELECT * FROM (
        SELECT col FROM dbo.tab
        UNION
        SELECT -1 AS col
) AS a
```

I tried to format that.

### Expected Behaviour

Query is formatted and still executable.

### Observed Behaviour

Query broken.

### How to reproduce

```
PS > cat .\sqlfluff-9.config
[sqlfluff]
dialect = tsql
templater = raw
PS > cat .\sqlfluff-9.sql
SELECT * FROM (
        SELECT col FROM dbo.tab
        UNION
        SELECT -1 AS col
) AS a
PS > sqlfluff fix .\sqlfluff-9.sql --config .\sqlfluff-9.config
==== finding fixable violations ====
== [sqlfluff-9.sql] FAIL
L:   5 | P:   6 | L025 | Alias 'a' is never used in SELECT statement.
==== fixing violations ====
1 fixable linting violations found
Are you sure you wish to attempt to fix these? [Y/n]
```

### Dialect

tsql

### Version

current git

### Configuration

see above

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by barrywhart**
### Brief summary of the change made
Fixes #3547 
This is a one-line change to yesterday's PR (#3546)

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by tunetheweb — APPROVED** [review]
Approved. Could you do me a favour though and search the rules for `set_expression`? I’ve a funny feeling another rules uses that with `select_expression` and one other too which we might want to add here.

**Comment by barrywhart** [comment]
Will do. It'll probably be this afternoon. I'm about to go somewhere with the family.

**Comment by tunetheweb** [comment]
Maybe just merge this in meantime then?

**Comment by barrywhart** [comment]
@tunetheweb: Good catch! The other case is `with_compound_statement`. I added a test case and a fix for that too. Once the build passes, I'll merge this and make the release.

**Pull request merged**
