### PR TITLE
Prepare 0.13.0

### PR DESCRIPTION
**Pull request by tunetheweb**
We have another 41 changes merged since the last release, so let's do a release at the end of the week.

@NiallRees @jmc-bbk @dmohns you have open PRs so please work on getting them closed by Thursday if you want them included.

### CODE REVIEW

**Comment by barrywhart** [comment]
What, no 1.0? 😁

**Comment by tunetheweb** [comment]
Did consider it but some more big changes in this one, and we said 1.0 would be a smaller release so we didn't jinx ourselves!

**Comment by tunetheweb** [comment]
Reminder for myself: If we merge #3118 (which I think we can for this release) then we should bump this to 0.13.0 instead.

**Review by barrywhart — APPROVED** [review]

**Comment by mrcool4** [comment]
Any update on this release please?

**Comment by tunetheweb** [comment]
Plan was always to release today. Though have a few PRs that think we should hold off for so might be weekend. Monday at the latest.

**Pull request merged**
