### PR TITLE
L036: Treat wildcard as multiple select targets (i.e. separate line)

### LINKED ISSUE #3420: L036 - no alert for new line requirement of wildcard
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

image

### Expected Behaviour

Wildcard should require a new line:

> SELECT
>  *
> FROM my_model

### Observed Behaviour

No error message found after running:

> sqlfluff lint dbt/models/example/my_second_dbt_model.sql

### How to reproduce

We have done: 
```
pip install sqlfluff
pip install sqlfluff-templater-dbt
```

The directory structure:

```
project
|
|__.sqlfluff
|
|__.sqlfluffignore
|
|__dbt
       |
       |__models
                 |
                 |__example
                            |
                            |__my_second_dbt_model.sql
```

                 

### Dialect

bigquery

### Version

sqlfluff version 0.13.1

### Configuration

In our `.sqlfluff`:

```
[sqlfluff]
verbose = 0
nocolor = False
dialect = bigquery
templater = jinja
rules = None
exclude_rules = L027, L031, L032, L034, L035, L042, L051, L060
recurse = 0
output_line_length = 100
runaway_limit = 10
ignore = templating
ignore_templated_areas = True
# Comma separated list of file extensions to lint.
sql_file_exts = .sql,.sql.j2,.dml,.ddl

[sqlfluff:indentation]
indented_joins = False
indented_using_on = False
template_blocks_indent = True

[sqlfluff:templater]
unwrap_wrapped_queries = True

[sqlfluff:templater:jinja]
apply_dbt_builtins = True
load_macros_from_path = ./dbt/macros

[sqlfluff:templater:jinja:macros]
# Macros provided as builtins for dbt projects
dbt_ref = {% macro ref(model_ref) %}{{model_ref}}{% endmacro %}
dbt_source = {% macro source(source_name, table) %}{{source_name}}_{{table}}{% endmacro %}
dbt_config = {% macro config() %}{% for k in kwargs %}{% endfor %}{% endmacro %}
dbt_var = {% macro var(variable) %}item{% endmacro %}
dbt_is_incremental = {% macro is_incremental() %}True{% endmacro %}

# Some rules can be configured directly from the config common to other rules.
[sqlfluff:rules]
tab_space_size = 2
max_line_length = 80
indent_unit = space
comma_style = trailing
allow_scalar = False
single_table_references = consistent
unquoted_identifiers_policy = all

# Some rules have their own specific config.
[sqlfluff:rules:L003]
lint_templated_tokens = True
hanging_indents = False
tab_space_size = 2

[sqlfluff:rules:L010]  # Keywords
capitalisation_policy = upper

[sqlfluff:rules:L014]  # Unquoted identifiers
extended_capitalisation_policy = lower

[sqlfluff:rules:L016]
ignore_comment_lines = False

[sqlfluff:rules:L018]
tab_space_size = 2

[sqlfluff:rules:L019]
comma_style = trailing

[sqlfluff:rules:L029]  # Keyword identifiers
unquoted_identifiers_policy = all

[sqlfluff:rules:L030]  # Function names
capitalisation_policy = upper

[sqlfluff:rules:L038]
select_clause_trailing_comma = forbid

[sqlfluff:rules:L040]  # Null & Boolean Literals
capitalisation_policy = upper

[sqlfluff:rules:L047]  # Consistent syntax to count all rows
prefer_count_0 = False
prefer_count_1 = False

[sqlfluff:rules:L064]
preferred_quoted_literal_style = double_quotes

```

In our `.sqlfluffignore`:

```
target/
# dbt <1.0.0
dbt_modules/
# dbt >=1.0.0
macros/
target/
```

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by barrywhart**
### Brief summary of the change made
Fixes #3420

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by tunetheweb — APPROVED** [review]
Approved, but I wonder if we should make this configurable? Some might prefer the current formatting.

**Comment by barrywhart** [comment]
@tunetheweb: Re: The current formatting, I'd be inclined to treat that as a separate issue (enhancement), since the behavior has apparently been documented this way for a long time. Want to create that issue? I'd be happy to work on it.

**Comment by tunetheweb** [comment]
It’s been documented like that, but didn’t act like that. And who reads the docs 😄

That’s why I was suggesting doing this as part of this.

**Comment by tunetheweb** [comment]
Raised #3425

**Pull request merged**
