### PR TITLE
reindent refactor

### PR DESCRIPTION
**Pull request by alanmcruickshank**
This is some of the code elements of #4314 . This PR should have no substantive effect, it's just pure refactoring. It does however support some of the comment logic changes intended in the original PR.

### CODE REVIEW

**Comment by WittierDinosaur** [comment]
Looks good - but you've lost a bit of code coverage

**Comment by WittierDinosaur** [comment]
Looks good - but you've lost a bit of code coverage

**Comment by alanmcruickshank** [comment]
@WittierDinosaur - right you are. I think that clause makes sense to keep - so I've marked it as no cover. Could you give me a review and I'll get this in?

**Review by WittierDinosaur — APPROVED** [review]
LGTM

**Pull request merged**
