### PR TITLE
Handle renamed dbt exceptions

### PR DESCRIPTION
**Pull request by greg-finley**
### Brief summary of the change made

CI is broken after https://github.com/dbt-labs/dbt-core/pull/6539

### Are there any other side effects of this change that we should be aware of?
There could be some more graceful way to handle this by checking the dbt version, but I am not seeing that. This probably works?

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by barrywhart — APPROVED** [review]

**Comment by barrywhart** [comment]
The PR looks good to me. We do sometimes check the dbt version explicitly, but the simpler approach you're using is better in some ways. Checking version numbers can be handy when the differences between versions are more subtle than an `ImportError`.

**Comment by nicolasvo-doctolib** [comment]
Hi @greg-finley @barrywhart , when will these changes be available?

**Comment by greg-finley** [comment]
@nicolasvo-doctolib it's in the `2.0.0a4` release.

**Comment by moseleyi** [comment]
Has anybody still get these errors? I can't get sqlfluff to work at all

```
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\sqlfluff.exe\__main__.py", line 4, in <module>
  File "C:\Python38\lib\site-packages\sqlfluff\__init__.py", line 6, in <module>
    from sqlfluff.api import lint, fix, parse, list_rules, list_dialects
  File "C:\Python38\lib\site-packages\sqlfluff\api\__init__.py", line 4, in <module>
    from sqlfluff.api.simple import lint, fix, parse, APIParsingError
  File "C:\Python38\lib\site-packages\sqlfluff\api\simple.py", line 4, in <module>
    from sqlfluff.core import (
  File "C:\Python38\lib\site-packages\sqlfluff\core\__init__.py", line 9, in <module>
    from sqlfluff.core.linter import Linter
  File "C:\Python38\lib\site-packages\sqlfluff\core\linter\__init__.py", line 6, in <module>
    from sqlfluff.core.linter.linter import Linter
  File "C:\Python38\lib\site-packages\sqlfluff\core\linter\linter.py", line 32, in <module>
    from sqlfluff.core.rules import get_ruleset
  File "C:\Python38\lib\site-packages\sqlfluff\core\rules\__init__.py", line 12, in <module>
    for plugin_rules in get_plugin_manager().hook.get_rules():
  File "C:\Python38\lib\site-packages\sqlfluff\core\plugin\host.py", line 12, in get_plugin_manager
    pm.load_setuptools_entrypoints(project_name)
  File "C:\Python38\lib\site-packages\pluggy\_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "C:\Python38\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Python38\lib\site-packages\sqlfluff_templater_dbt\__init__.py", line 3, in <module>
    from sqlfluff_templater_dbt.templater import DbtTemplater
  File "C:\Python38\lib\site-packages\sqlfluff_templater_dbt\templater.py", line 17, in <module>
    from dbt.exceptions import (
ImportError: cannot import name 'CompilationException' from 'dbt.exceptions' (C:\Python38\lib\site-packages\dbt\exceptions.py)
```

**Pull request merged**
