### PR TITLE
Redshift-dialect: Support GRANT USAGE ON DATASHARE

### PR DESCRIPTION
**Pull request by josef-v**
### Introduction
Hi, this is my first pull request here. I am not really sure if I made it the right way, it seems that adding this statement to redshift dialect is kind of "ad hoc".

However, redshift seems to be full of those extra rules bending additions, so it's probably the only possible approach.

Rationale for my change: I have started a new job, we use redshift. We use sqlfluff. There is a ton of ignored files due to these unparsable extras in redshift dialect.

### Brief summary of the change made

Adding ability to parse `GRANT USAGE ON DATASHARE` [statements](https://docs.aws.amazon.com/redshift/latest/dg/r_GRANT.html) in Redshift dialect.

```
GRANT USAGE
    ON DATASHARE datashare_name
    TO NAMESPACE 'namespaceGUID' [, ...] | ACCOUNT 'accountnumber' [ VIA DATA CATALOG ] [, ...]
```

_Note: The first example in the AWS Redshift documentation violates the syntax :facepalm:_ 

**Disclaimer: I have not yet tested all those examples with live instance of Redshift, that's why it's still a draft. I will try it tomorrow and switch the state of this PR once I'll see that it's parsed.**

### Are there any other side effects of this change that we should be aware of?
No

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - *N/A* `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - *N/A* Full autofix test cases in `test/fixtures/linter/autofix`.
  - *N/A* Other.
- *N/A* Added appropriate documentation for the change.
- *N/A* Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by josef-v** [comment]
I have just verified that using multiple namespaces or accounts in the same GRANT statement causes a syntax error. I have submitted a feedback on this section of the aws documentation as it seems it's either incorrect or at least confusing.

**Review by alanmcruickshank — APPROVED** [review]
Looks pretty sensible to me! Thanks for putting this together.

**Comment by alanmcruickshank** [comment]
@josef-v - if these statements work - then I'm happy to merge this. 👍 .

Just mark is as "ready for review" when you've done your testing.

**Comment by josef-v** [comment]
> @josef-v - if these statements work - then I'm happy to merge this. 👍 .

@alanmcruickshank 
Hi Alan, that's the actual problem I am having. Those testing statements do not work but are made according to the redshift documentation. So the question is, is it better to merge documentation compliant statements or actual implementation compliant statements? The second choice is probably better but I would be glad for another opinion on this.

**Comment by alanmcruickshank** [comment]
> Hi Alan, that's the actual problem I am having. Those testing statements do not work but are made according to the redshift documentation.

Ahhhh interesting 🙃 . Good question.

I would rather that the test statements _do_ actually work, although I appreciate the issues if Redshift isn't following it's own docs. Are you able to find some statements that do work? I don't currently have access to a Redshift instance to do the testing myself. I'm very happy to re-review once that's done.

**Comment by josef-v** [comment]
Changed to work with current redshift implementation. I have also added a note that this is not according to the documentation. Rebased.
@alanmcruickshank

**Review by WittierDinosaur — APPROVED** [review]
LGTM

**Comment by WittierDinosaur** [comment]
Linting errors

**Comment by josef-vondrlik** [comment]
Fixed, sorry for that.

**Comment by josef-v** [comment]
Fixed. Sorry for that.

**Pull request merged**
