### PR TITLE
Due to performance and other issues, revert the osmosis implementation of the templater for now

### PR DESCRIPTION
**Pull request by barrywhart**
### Brief summary of the change made
Makes progress on #4263

This PR essentially rolls back much of the earlier templater rewrite (PR #3976), but it's a bit simpler because I removed support for dbt versions prior to 1.0.

I focused on rolling back the templater.py changes, leaving in place some of the ancillary changes, because I do want to re-introduce the new templater implementation in the near future. That planned work is captured in a new enhancement issue #4271.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by alanmcruickshank — CHANGES_REQUESTED** [review]
If we're rolling back a bunch of the changes, I think there are a couple of other bits:
1. requirements in the `setup.cfg` file for the plugin.
2. remove the vendored code (I'm up for re-including it, but there's a hopeful chance that by the time we use it again it's got an actual release which we can import).
3. we should probably reinclude the test which checks sorting: `test__templater_dbt_sequence_files_ephemeral_dependency`.

Otherwise this looks sensible for now. Sorry it hasn't worked out smoothly yet. I'm also convinced that there's something in this eventually.

**Comment by barrywhart** [comment]
Yes, I believe the problems are surmountable, just don't want to delay the perf fix that long.

**Comment by barrywhart** [comment]
@alanmcruickshank: I made all the changes you suggested. Ready for another review.

**Review by alanmcruickshank — APPROVED** [review]
LGTM

**Pull request merged**
