### PR TITLE
Issue 847: Whitespace.is_whitespace should be True

### LINKED ISSUE #847: Whitespace token is_whitespace is False
I expect segment.is_whitespace of a Whitespace token is True, however, it is set to False.

## Expected Behaviour
segment.is_whitespace return True

## Observed Behaviour
segment.is_whitespace return False
## Version
Include the output of `sqlfluff --version` along with your Python version

## Configuration
```
Include your SQLFluff configuration here
```

### PR DESCRIPTION
**Pull request by barrywhart**
I'd like @alanmcruickshank's review on this before merging, because the very existence of the `is_whitespace` property seems like a leftover from long ago. Since it's currently not used **anywhere** in the SQLFluff code base, I'm wondering whether improving it is a good idea, or if we should just remove it. The small change in this PR is probably not going to address other cases where `is_whitespace` is wrong (i.e. `False` when it should be `True`), such as:
* the `whitespace` token [here](https://github.com/sqlfluff/sqlfluff/blob/master/src/sqlfluff/core/dialects/dialect_ansi.py#L52)
* the `newline` token [here](https://github.com/sqlfluff/sqlfluff/blob/master/src/sqlfluff/core/dialects/dialect_ansi.py#L85)

### CODE REVIEW

**Comment by alanmcruickshank** [comment]
Great catch. You're right that it's not used at all at the moment. Part of me thinks we should remove it, although I wonder whether it might become more useful going forward.

If we're going to keep it, then we should address the other two you mention. I'll suggest the changes...

**Comment by alanmcruickshank** [comment]
Actually - it's going to need to be some deeper changes to address the other points. I'm happy to pick that up in a separate PR. @barrywhart - can you make sure this PR doesn't close the open issue? I'll sort the rest.

**Comment by barrywhart** [comment]
Ok, @alanmcruickshank, I removed the "resolves <<issue number>>" from the PR. Do you want me to merge this? I'm happy to merge or close, whichever you prefer.

**Comment by SuperBo** [comment]
Hi all, @barrywhart , @alanmcruickshank, 
I think is_whitespace should also be true for new line and tab segment. In that case, we can use is_whitespace to skip whitespace token (space, newline, tab, etc...) when traveling the parse tree.

**Review by alanmcruickshank — APPROVED** [review]
Happy to merge!

**Pull request merged**
