### PR TITLE
Remove support for Python 3.6 (it's "end of life" December 23, 2021)

### PR DESCRIPTION
**Pull request by barrywhart**
### Brief summary of the change made

Removes support for Python 3.6.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `python test/generate_parse_fixture_yml.py` or by running `tox` locally).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by tunetheweb — APPROVED** [review]
I see another couple of references:

image

Or we happy to leave those in there and continue to support 3.6 unofficially?

Also FYI, in `.github/codecov.yml` we have this:

```
  notify:
    after_n_builds: 11
```

As of this PR:
- 4 linux standard runs are eligible 3.7 - 3.10
- 5 linux DBT runs (dbt018 - dbt100)
- 1 windows standard run runs
- 1 windows dbt run

Windows Linux is usually last to finish and think we now need it as a bit of coverage depends on that.

So think this is OK to leave. Or could reduce to 10 to get early feedback of code coverage but then you sometimes get false negatives of missing coverage.

**Comment by barrywhart** [comment]
Last night, I removed those 2 other 3.6 references, and some tests were failing -- some weird pickling error in the progress bar tests. I'm guessing it was the stuff in `runner.py`. So I'd prefer to leave that for now if that's okay.

**Comment by barrywhart** [comment]
I'm good with leaving it at 11. False positives are 😿

**Comment by jpy-git** [comment]
> I'm good with leaving it at 11. False positives are 😿

Was wondering why we kept getting coverage errors before all the tests had finished since we added dbt100. Glad this will start working properly again 🎉

**Comment by tunetheweb** [comment]
Yeah it’s annoying you have to remember to change this. But annoying. We used to have more headroom when Windows standard wasn’t required so didn’t matter it was the last to complete. I wonder if there’s a better way than just setting the number and telling codecov. Would be nice if we could say at least I’ve standard, dbt and windows test has to run.

**Pull request merged**
