### PR TITLE
Refactor match libs and remove _match.

### PR DESCRIPTION
**Pull request by alanmcruickshank**
This was inspired from the work being done on mypy.

The existence of `BaseGrammar._match()` and `BaseSegment._match()` was a bit of a historical oddity, and both were intending to do the same thing. This PR removes any of the `._match()` methods and simple wraps and of the `.match()` methods in a common decorator.

With that done it was possible to pull some of the logic out of `parser.grammar` and `parser.segments_base` (which are both pretty bloated) and move them into some smaller sub modules. Most of that logic covered logging routines and string handling, so there are a few improvements to those routines in here too.

Would appreciate a review on whether this actually makes things easier to understand? My hope is that this makes things more maintainable. @pwildenhain do you think I've managed that?

### CODE REVIEW

**Review by pwildenhain — APPROVED** [review]
Still wrapping my head around segments and grammars, and this PR definitely helped me understand these concepts better 🙌 

❤️ Love that you were able to abstract the validation and logging away from the actual (dual) functionality of `match` I think this PR is a sure win for readability and maintainability.


Does this also help with the circular dependency issue we were seeing in #459?

**Comment by alanmcruickshank** [comment]
> Does this also help with the circular dependency issue we were seeing in #459?

No not yet unfortunately, but I think it's a step in the right direction.

**Comment by alanmcruickshank** [comment]
That was painful to merge into master with both the `EphemeralSegment` and `black` changes. 😬

**Comment by pwildenhain** [comment]
Hopefully no more super disruptive PRs like that for a while 🤞

**Pull request merged**
