### PR TITLE
Redshift: Allow Whitespace Around Cast Operators

### LINKED ISSUE #2720: Redshift: Fail to parse whitespace around casting operators
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

The following query in Redshift is legal:

```sql
SELECT amount_of_honey :: float
FROM bear_inventory;
```

However, when running `sqlfluff lint --dialect=redshift --ignore templating example.sql` with the `.sqlfluff` specification below, I get a parse error:

```bash
== [example.sql] FAIL                                                                                                                                         
L:   1 | P:  23 |  PRS | Line 1, Position 23: Found unparsable section: ' :: float'
All Finished 📜 🎉!
```

I have a feeling this is due to Redshift failing to parse whitespace around casting operators. This is because you do not see parse errors with Redshift's ancestor dialects:

```bash
>>> sqlfluff lint --dialect=postgres --ignore templating example.sql
== [example.sql] FAIL                                                                                                                                         
L:   1 | P:  24 | L039 | Unnecessary whitespace found.
L:   1 | P:  27 | L010 | Keywords must be consistently upper case.
All Finished 📜 🎉!
>>> sqlfluff lint --dialect=ansi --ignore templating example.sql
== [example.sql] FAIL                                                                                                                                         
L:   1 | P:  24 | L039 | Unnecessary whitespace found.
L:   1 | P:  27 | L010 | Keywords must be consistently upper case.
All Finished 📜 🎉!


### Expected Behaviour

Query is linted with no parse errors (but can have rule flags).

### Observed Behaviour

SQLFluff indicates a parse error:

```bash
>>> sqlfluff lint --dialect=redshift --ignore templating example.sql
== [example.sql] FAIL                                                                                                                                         
L:   1 | P:  23 |  PRS | Line 1, Position 23: Found unparsable section: ' :: float'
All Finished 📜 🎉!
```

### How to reproduce

1. Install requirements: `pip install dbt==0.20.0 sqlfluff==0.10.1 markupsafe==2.0.1`
2. Create the following `.sqlfluff` file in the working directory:
```
[sqlfluff]
verbose = 0
nocolor = False
dialect = redshift
templater = jinja
rules = None
exclude_rules = L009,L011,L019,L029,L031,L034,L054
recurse = 0
output_line_length = 160
runaway_limit = 10
ignore_templated_areas = True
encoding = autodetect
# Comma separated list of file extensions to lint.

# NB: This config will only apply in the root folder.
sql_file_exts = .sql,.sql.j2,.dml,.ddl

[sqlfluff:indentation]
indented_joins = False
indented_using_on = True
template_blocks_indent = True

[sqlfluff:templater]
unwrap_wrapped_queries = True

[sqlfluff:templater:jinja]
apply_dbt_builtins = True

[sqlfluff:templater:jinja:macros]
# Macros provided as builtins for dbt projects
dbt_ref = {% macro ref(model_ref) %}{{model_ref}}{% endmacro %}
dbt_source = {% macro source(source_name, table) %}{{source_name}}_{{table}}{% endmacro %}
dbt_config = {% macro config() %}{% for k in kwargs %}{% endfor %}{% endmacro %}
dbt_var = {% macro var(variable) %}item{% endmacro %}
dbt_is_incremental = {% macro is_incremental() %}True{% endmacro %}

# Some rules can be configured directly from the config common to other rules.
[sqlfluff:rules]
tab_space_size = 4
max_line_length = 160
indent_unit = space
comma_style = trailing
allow_scalar = True
single_table_references = consistent
unquoted_identifiers_policy = all

# Some rules have their own specific config.
[sqlfluff:rules:L003]
lint_templated_tokens = True

[sqlfluff:rules:L007]  # Keywords
operator_new_lines = after

[sqlfluff:rules:L010]  # Keywords
capitalisation_policy = consistent

[sqlfluff:rules:L014]  # Unquoted identifiers
extended_capitalisation_policy = consistent

[sqlfluff:rules:L016]
ignore_comment_lines = False

[sqlfluff:rules:L029]  # Keyword identifiers
unquoted_identifiers_policy = aliases

[sqlfluff:rules:L030]  # Function names
capitalisation_policy = consistent

[sqlfluff:rules:L038]
select_clause_trailing_comma = forbid

[sqlfluff:rules:L040]  # Null & Boolean Literals
capitalisation_policy = consistent

[sqlfluff:rules:L042]
# By default, allow subqueries in from clauses, but not join clauses.
forbid_subquery_in = join

[sqlfluff:rules:L047]  # Consistent syntax to count all rows
prefer_count_1 = False
prefer_count_0 = False
```
3. Create an `example.sql` file in the working directory with the following content:
```sql
SELECT amount_of_honey :: float
FROM bear_inventory;
```
4. Run `sqlfluff lint --dialect=redshift --ignore templating example.sql`.

### Dialect

`redshift`

### Version

`sqlfluff==0.10.1`

### Configuration

`.sqlfluff`:
```
[sqlfluff]
verbose = 0
nocolor = False
dialect = redshift
templater = jinja
rules = None
exclude_rules = L009,L011,L019,L029,L031,L034,L054
recurse = 0
output_line_length = 160
runaway_limit = 10
ignore_templated_areas = True
encoding = autodetect
# Comma separated list of file extensions to lint.

# NB: This config will only apply in the root folder.
sql_file_exts = .sql,.sql.j2,.dml,.ddl

[sqlfluff:indentation]
indented_joins = False
indented_using_on = True
template_blocks_indent = True

[sqlfluff:templater]
unwrap_wrapped_queries = True

[sqlfluff:templater:jinja]
apply_dbt_builtins = True

[sqlfluff:templater:jinja:macros]
# Macros provided as builtins for dbt projects
dbt_ref = {% macro ref(model_ref) %}{{model_ref}}{% endmacro %}
dbt_source = {% macro source(source_name, table) %}{{source_name}}_{{table}}{% endmacro %}
dbt_config = {% macro config() %}{% for k in kwargs %}{% endfor %}{% endmacro %}
dbt_var = {% macro var(variable) %}item{% endmacro %}
dbt_is_incremental = {% macro is_incremental() %}True{% endmacro %}

# Some rules can be configured directly from the config common to other rules.
[sqlfluff:rules]
tab_space_size = 4
max_line_length = 160
indent_unit = space
comma_style = trailing
allow_scalar = True
single_table_references = consistent
unquoted_identifiers_policy = all

# Some rules have their own specific config.
[sqlfluff:rules:L003]
lint_templated_tokens = True

[sqlfluff:rules:L007]  # Keywords
operator_new_lines = after

[sqlfluff:rules:L010]  # Keywords
capitalisation_policy = consistent

[sqlfluff:rules:L014]  # Unquoted identifiers
extended_capitalisation_policy = consistent

[sqlfluff:rules:L016]
ignore_comment_lines = False

[sqlfluff:rules:L029]  # Keyword identifiers
unquoted_identifiers_policy = aliases

[sqlfluff:rules:L030]  # Function names
capitalisation_policy = consistent

[sqlfluff:rules:L038]
select_clause_trailing_comma = forbid

[sqlfluff:rules:L040]  # Null & Boolean Literals
capitalisation_policy = consistent

[sqlfluff:rules:L042]
# By default, allow subqueries in from clauses, but not join clauses.
forbid_subquery_in = join

[sqlfluff:rules:L047]  # Consistent syntax to count all rows
prefer_count_1 = False
prefer_count_0 = False
```

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by PLBMR**
### Brief summary of the change made

Fixes #2720 .

- **Allows whitespace around cast operators (`::`) in the `redshift` dialect.** I allowed this by adjusting the `DatatypeSegment` in the `redshift` dialect to match grammar using a `Sequence` parser instead of just a `OneOf` parser, and allowed that `Sequence` to have gaps (`allow_gaps=True`). This aligns the parsing logic of `DatatypeSegment`s in the `redshift` dialect to with its ancestor dialects (`postgres`, `ansi`); both of this ancestor dialects parse `DatatypeSegment`s using a `Sequence` parser. I demonstrated that `sqlfluff` now allows for whitespaces around cast operators in the `redshift` dialect with `test/fixtures/dialects/redshift/redshift_cast_with_whitespaces.sql` and `test/fixtures/dialects/redshift/redshift_cast_with_whitespaces.yml`.

### Are there any other side effects of this change that we should be aware of?

This change will allow whitespace around any `DataTypeSegment` in the `redshift` dialect. This is a good thing, as data type definitions across the Redshift specification are flexible to surrounding whitespace.

### Pull Request checklist
- [x ] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`. **(N/A for this change)**
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`). **(DONE, see `test/fixtures/dialects/redshift/redshift_cast_with_whitespaces.sql` and `test/fixtures/dialects/redshift/redshift_cast_with_whitespaces.yml`)**
  - Full autofix test cases in `test/fixtures/linter/autofix`. **(N/A for this change)**
  - Other. **(N/A for this change)**
- Added appropriate documentation for the change. **(DONE)**
- Created GitHub issues for any relevant followup/future enhancements if appropriate. **(N/A for this change)**

### CODE REVIEW

**Review by tunetheweb — CHANGES_REQUESTED** [review]
Wouldn't it be easier, and more syntaxically correct to override the ShorthandCastSegment segment instead to allow gaps?

```py
@redshift_dialect.segment(replace=True)
class ShorthandCastSegment(BaseSegment):
    """A casting operation using '::'."""

    type = "cast_expression"
    match_grammar = Sequence(
        Ref("CastOperatorSegment"), Ref("DatatypeSegment"), allow_gaps=True
    )
```

**Comment by PLBMR** [comment]
> Wouldn't it be easier, and more syntaxically correct to override the ShorthandCastSegment segment instead to allow gaps?
> 
> ```python
> @redshift_dialect.segment(replace=True)
> class ShorthandCastSegment(BaseSegment):
>     """A casting operation using '::'."""
> 
>     type = "cast_expression"
>     match_grammar = Sequence(
>         Ref("CastOperatorSegment"), Ref("DatatypeSegment"), allow_gaps=True
>     )
> ```

@tunetheweb good callout! Technically, Both the `ansi` and `postgres` dialect should also support this. Hence, I'm going to simply adjust the `ShorthandCastSegment` in `ansi`, and have `postgres` and `redshift` dialects inherit this change.

**Comment by PLBMR** [comment]
@tunetheweb made the change :)

**Comment by tunetheweb** [comment]
Curious does rule L039 catch these whitespaces? Cause they do seem unnecessary to me. Or at least does it catch multiple ones?

**Comment by PLBMR** [comment]
> Curious does rule L039 catch these whitespaces? Cause they do seem unnecessary to me. Or at least does it catch multiple ones?

Agreed. `L039` does catch these whitespaces:

```bash
>>> .tox/generate-fixture-yml/bin/sqlfluff lint --dialect=redshift test/fixtures/dialects/redshift/redshift_cast_with_whitespaces.sql
== [test/fixtures/dialects/redshift/redshift_cast_with_whitespaces.sql] FAIL                                                                                                      
L:   6 | P:  24 | L039 | Unnecessary whitespace found.
L:  11 | P:  23 | L039 | Unnecessary whitespace found.
L:  11 | P:  31 | L039 | Unnecessary whitespace found.
L:  11 | P:  33 | L039 | Unnecessary whitespace found.
L:  14 | P:  23 | L039 | Unnecessary whitespace found.
L:  14 | P:  25 | L039 | Unnecessary whitespace found.
L:  17 | P:  23 | L039 | Unnecessary whitespace found.
L:  17 | P:  31 | L039 | Unnecessary whitespace found.
L:  21 | P:  24 | L039 | Unnecessary whitespace found.
L:  21 | P:  27 | L010 | Keywords must be consistently upper case.
L:  24 | P:  24 | L039 | Unnecessary whitespace found.
L:  24 | P:  27 | L010 | Keywords must be consistently upper case.
L:  27 | P:  23 | L039 | Unnecessary whitespace found.
L:  27 | P:  28 | L039 | Unnecessary whitespace found.
L:  30 | P:  24 | L039 | Unnecessary whitespace found.
L:  30 | P:  26 | L039 | Unnecessary whitespace found.
L:  33 | P:  23 | L039 | Unnecessary whitespace found.
L:  33 | P:  27 | L039 | Unnecessary whitespace found.
L:  33 | P:  29 | L039 | Unnecessary whitespace found.
L:  37 | P:   1 | L036 | Select targets should be on a new line unless there is
                       | only one select target.
L:  39 | P:  21 | L011 | Implicit/explicit aliasing of table.
L:  39 | P:  21 | L031 | Avoid aliases in from clauses and join conditions.
L:  40 | P:  25 | L011 | Implicit/explicit aliasing of table.
L:  40 | P:  25 | L031 | Avoid aliases in from clauses and join conditions.
L:  41 | P:  19 | L039 | Unnecessary whitespace found.
L:  41 | P:  21 | L039 | Unnecessary whitespace found.
L:  41 | P:  49 | L039 | Unnecessary whitespace found.
L:  41 | P:  53 | L039 | Unnecessary whitespace found.

**Review by tunetheweb — APPROVED** [review]

**Pull request merged**
