### PR TITLE
Added type hints to some rule files

### PR DESCRIPTION
**Pull request by ttomasz**
### Brief summary of the change made
makes progress on #1059
I tried to follow style from PR #1515 using BaseSegment for segment and Tuple[RawSegment] for raw_stack.

### Are there any other side effects of this change that we should be aware of?
No

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `python test/generate_parse_fixture_yml.py` or by running `tox` locally).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by alanmcruickshank** [comment]
@ttomasz - I realise it's a much bigger change, but what do you think to this bigger refactor? It replaces the `_eval()` interface with a dataclass which I think is much more user friendly.

Would appreciate feedback from @tunetheweb and @barrywhart on this too - my suggestion is a potentially breaking change to any rule plugins (which I realise are still relatively rare - but even so).

**Comment by barrywhart** [comment]
Changing the rule interface sounds good to me. The old way was a little obscure, in that it wasn't really clear what parameters were available unless you happened to look at `kwargs` or the function that was calling the rules.

I've only seen a handful of questions about custom rules in Slack, so I don't think many users will be affected.

**Comment by ttomasz** [comment]
> 
> 
> @ttomasz - I realise it's a much bigger change, but what do you think to this bigger refactor? It replaces the `_eval()` interface with a dataclass which I think is much more user friendly. That also makes it much easier to do effective type hinting.
> 
> Would appreciate feedback from @tunetheweb and @barrywhart on this too - my suggestion is a potentially breaking change to any rule plugins (which I realise are still relatively rare - but even so).

@alanmcruickshank  Thanks for taking the time to look into this, your changes look nice 🙂 Are there any changes left that I should do here?

**Comment by tunetheweb** [comment]
> Would appreciate feedback from @tunetheweb and @barrywhart on this too - my suggestion is a potentially breaking change to any rule plugins (which I realise are still relatively rare - but even so).

Fraid I'm gonna stay out of this one. I am but a Python novice so no idea what you're all talking about here! 🤣

But happy for it to be merged if you three are all good.

**Comment by tunetheweb** [comment]
OK let's merge this. Can you resolve the conflicts @ttomasz ?

**Comment by ttomasz** [comment]
Conflicts resolved 🙂

**Pull request merged**
