### PR TITLE
Issue 667: Add optional IGNORE/RESPECT NULLS to BigQuery function parameter grammar

### LINKED ISSUE #667: array_agg(x IGNORE NULLS) is unparseable - dialect bigquery
With the following piece of test sql for BigQuery, one can produce an unparsable section error:
```
SELECT
    array_agg(t1) AS a1,
    array_agg(t2 IGNORE NULLS) AS a2,
FROM

    test_table

``` 
## Expected Behaviour

Expected test SQL to be parseable, as "IGNORE NULL" appears to be valid according to https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#array_agg and is understood from BQ.

## Observed Behaviour

== [test.sql] FAIL
L:   3 | P:   5 |  PRS | Found unparsable section: 'array_agg(t2 IGNORE
                       | NULLS)'

## Version
sqlfluff, version 0.3.6
Python 3.8.1

## Configuration
```
[sqlfluff]
dialect = bigquery
```

Given a bit of guidance, I could offer to commit and PR a fix, if nobody else wants to be super quick on this one.

### PR DESCRIPTION
**Pull request by barrywhart**
Resolves #667

### CODE REVIEW

**Comment by NiallRees** [comment]
Noice. Please could you add `.yml` files for each of these test cases just to show definitively that they are being parsed correctly?

**Comment by barrywhart** [comment]
@NiallRees: Done!

I ran into a little issue generating the `.yml` files. `sqlfluff parse -f yaml` outputs a file that includes a top-level `filepath` key. I had to remove that so the outer key was just `file`. Is that a known thing? I didn't see it mentioned in the parser fixtures [`README.md`](https://github.com/sqlfluff/sqlfluff/blob/master/test/fixtures/parser/README.md).

**Comment by NiallRees** [comment]
> @NiallRees: Done!
> 
> I ran into a little issue generating the `.yml` files. `sqlfluff parse -f yaml` outputs a file that includes a top-level `filepath` key. I had to remove that so the outer key was just `file`. Is that a known thing? I didn't see it mentioned in the parser fixtures [`README.md`](https://github.com/sqlfluff/sqlfluff/blob/master/test/fixtures/parser/README.md).

It is - I just forgot to add it to the README.md! I'll approve this - if you wouldn't mind adding that info that would be great

**Review by NiallRees — APPROVED** [review]

**Comment by barrywhart** [comment]
@NiallRees: I updated the `README.md` with both docs on how to clean up the YAML output as well as a piped `bash` command to automate it.

Will merge once the tests pass.

**Comment by NiallRees** [comment]
> @NiallRees: I updated the `README.md` with both docs on how to clean up the YAML output as well as a piped `bash` command to automate it.
> 
> Will merge once the tests pass.

🙌 that will save so much time. I'm not totally clear why we have to remove the file segment, newlines and whitespace though!

**Comment by barrywhart** [comment]
The Python 3.8 error is a CircleCI problem, not a problem with the PR. Merging.

**Comment by barrywhart** [comment]
@NiallRees: I agree about "why do we need this". I suspect we could tweak the test code to avoid this requirement, and I would be 👍 on doing that. That would make it much easier to add new tests.

**Pull request merged**
