### PR TITLE
Improve release checklist to make releases easier

### PR DESCRIPTION
**Pull request by tunetheweb**
### Brief summary of the change made

Add regexs and other improvements to release checklist

### Are there any other side effects of this change that we should be aware of?
Nope just documentation

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by tunetheweb** [comment]
@barrywhart some of the things you raised on last release

**Comment by tunetheweb** [comment]
Did you spot anything else while doing last night's release btw @barrywhart ? Can definitely automate some of the above, but first step is document anything that's not obvious to someone doing a release for first time (or first time in a while).

**Review by barrywhart — APPROVED** [review]
Looks good!

As we discussed yesterday, it would be cool to automate some of this, but the mixture of semi-automated drafts plus multi-step release (as last-minute PRs are merged) makes this tricky. Personally, I'd rather keep focusing on improving SQLFluff itself for now. I think we're getting pretty close to where I'd like us to be. 💪🤞

**Comment by tunetheweb** [comment]
The converting the release notes to CHANGELOG is a bit annoying.

Ideally they’d be a GitHub Action that could be run (either manually, or via applying a label to a release PR, or commenting with a particular phrase), which would read the changes in the Draft release, and update this branch’s CHANGELOG with the latest (applying the regex formatting automatically) and that this could be called again and again as more PRs are merged.

Updating forked branches in GitHub Actions is messy though. But maybe Action could open PR initially from main repo to solve that and update the version numbers?

Anyway, I agree not critical. So will will leave that issue to get around to at some point. Might have a play later…

**Pull request merged**
