### PR TITLE
Greatly improved Snowflake syntax support

### LINKED ISSUE #996: Snowflake: Does not support `SET` command.
Snowflake dialect does not support SQL variables (As defined in [Snowflake's doc](https://docs.snowflake.com/en/sql-reference/sql/set.html).)

Code Sample ([Source](https://docs.snowflake.com/en/sql-reference/sql/set.html#examples)):

```
set v1 = 10;
```

## Expected Behaviour

`SET <var> = <expression>` is parsed.

## Observed Behaviour

Encountered an unparsable error when parsing `SET <var> = <expr>;` statement.

Output when executing `sqlfluff parse`:
```
$ sqlfluff parse test.sql --dialect snowflake
[0](1, 1, 1)        |file:
[0](1, 1, 1)        |    statement:
[0](1, 1, 1)        |        unparsable:                                           !! Expected: 'statement'
[0](1, 1, 1)        |            raw:                                              'set'
[3](1, 1, 4)        |            whitespace:                                       ' '
[4](1, 1, 5)        |            raw:                                              'v1'
[6](1, 1, 7)        |            whitespace:                                       ' '
[7](1, 1, 8)        |            raw:                                              '='
[8](1, 1, 9)        |            whitespace:                                       ' '
[9](1, 1, 10)       |            raw:                                              '10'
[11](1, 1, 12)      |    statement_terminator:                                     ';'
[12](1, 1, 13)      |    newline:                                                  '\n'

==== parsing violations ====
L:   1 | P:   1 |  PRS | Found unparsable section: 'set v1 = 10'
```

## Steps to Reproduce

1. Create a file with the code sample above.
2. Run `sqlfluff parse <file> --dialect snowflake`

## Version
Include the output of `sqlfluff --version` along with your Python version

## Configuration
Default - No configuration. Please note that the Snowflake dialect is specified in the command line call.

### LINKED ISSUE #1201: Grammar refers to 'PolicyKeywordSegment' which was not found in the snowflake dialect
Hi,
I'm trying to parse a Snowflake query with a CREATE MASKING POLICY statement:

```sql
CREATE OR REPLACE MASKING POLICY
        XXXX.XX.example_MASKING_POLICY AS (val VARCHAR) RETURNS VARCHAR ->
      CASE WHEN is_role_in_session('SNOWFLAKE_PII')
        THEN val
        ELSE '*** masked ***'
      END
      COMMENT = 'Applied 2021-07-13T03:12:16+0000';
```

## Expected Behaviour
The statement to be parsed
## Observed Behaviour
The program exits with error: RuntimeError: Grammar refers to 'PolicyKeywordSegment' which was not found in the snowflake dialect

## Steps to Reproduce
sqlfluff parse  --dialect snowflake query.sq
## Version
0.6.0
## Configuration
N/A

### LINKED ISSUE #1202: Support Snowflake Alter table set masking policy
Hi.
Can you please add support in the snowflake dialect to ALTER TABLE ... MODIFY COLUMN yyy SET MASKING POLICY. Example:

``
ALTER TABLE
        xxxx.example_table
      MODIFY COLUMN
        employeeCode SET MASKING POLICY  example_MASKING_POLICY;
``

### LINKED ISSUE #1209: Can't parse `CREATE TABLE` statement with Snowflake dialect
Hello,
I'm encountering issues while trying to parse `CREATE TABLE` statements with the Snowflake dialect.
This seems to be related to https://github.com/sqlfluff/sqlfluff/issues/1033.

Table comments are only parsed when the `CREATE` statement is recognized as a `dialect_snowflake.CreateStatementSegment`, and not a `dialect_ansi.CreateTableStatementSegment`. If the statement contains for example a column definition segment, it is seen as ANSI because the Snowflake dialect doesn't allow column definitions:

```shell
% echo "CREATE TABLE foo_table COMMENT = '1';" | sqlfluff parse -c --dialect snowflake -
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    statement:
[L:  1, P:  1]      |        create_statement:
[L:  1, P:  1]      |            keyword:                                          'CREATE'
[L:  1, P:  8]      |            keyword:                                          'TABLE'
[L:  1, P: 14]      |            object_reference:
[L:  1, P: 14]      |                identifier:                                   'foo_table'
[L:  1, P: 24]      |            snowflake_comment:
[L:  1, P: 24]      |                keyword:                                      'COMMENT'
[L:  1, P: 32]      |                comparison_operator:                          '='
[L:  1, P: 34]      |                literal:                                      "'1'"
[L:  1, P: 37]      |    statement_terminator:                                     ';'

% echo "CREATE TABLE foo_table (bar INTEGER) COMMENT = '1';" | sqlfluff parse -c --dialect snowflake -
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    statement:
[L:  1, P:  1]      |        create_table_statement:
[L:  1, P:  1]      |            keyword:                                          'CREATE'
[L:  1, P:  8]      |            keyword:                                          'TABLE'
[L:  1, P: 14]      |            table_reference:
[L:  1, P: 14]      |                identifier:                                   'foo_table'
[L:  1, P: 24]      |            bracketed:
[L:  1, P: 24]      |                start_bracket:                                '('
[L:  1, P: 25]      |                column_definition:
[L:  1, P: 25]      |                    identifier:                               'bar'
[L:  1, P: 29]      |                    data_type:
[L:  1, P: 29]      |                        data_type_identifier:                 'INTEGER'
[L:  1, P: 36]      |                end_bracket:                                  ')'
[L:  1, P: 37]      |        unparsable:                                           !! Expected: 'Nothing...'
[L:  1, P: 38]      |            raw:                                              'COMMENT'
[L:  1, P: 46]      |            raw:                                              '='
[L:  1, P: 48]      |            raw:                                              "'1'"
[L:  1, P: 51]      |    statement_terminator:                                     ';'

==== parsing violations ====
L:   1 | P:  37 |  PRS | Line 1, Position 37: Found unparsable section: " COMMENT = '1'"
```

Notice the difference between `create_statement` (Snowflake, can't have column definition) and `create_table_statement` (ansi, can't have Snowflake comment).

## Expected Behaviour

A `create table` statement containing both column definition and Snowflake comment should not throw a parsing error.

## Observed Behaviour

See above.

## Steps to Reproduce

See above.

## Version

Running sqlfluff directly from the current `master` branch.
```
% sqlfluff --version
sqlfluff, version 0.6.0
% python --version
Python 3.8.10
```

## Configuration

Default configuration.

### LINKED ISSUE #1210: Merge part of the Exasol/MySQL dialects with Snowflake dialect
Some Snowflake statements are not supported; however they work with the Exasol or MySQL dialects. Maybe they should have a common ancestor, so the Snowflake dialect can be expanded without code duplication?

Some examples:

## MERGE INTO

Works with Exasol, not Snowflake.

```shell
% echo "MERGE INTO foo USING bar on foo.x = bar.x WHEN MATCHED THEN UPDATE SET foo.y = 0;" | sqlfluff parse -c --dialect snowflake -
# unparsable tree
==== parsing violations ====
L:   1 | P:   1 |  PRS | Line 1, Position 1: Found unparsable section: 'MERGE INTO foo
                       | USING bar on foo.x = bar....'

% echo "MERGE INTO foo USING bar on foo.x = bar.x WHEN MATCHED THEN UPDATE SET foo.y = 0;" | sqlfluff parse -c --dialect exasol -
# all good
```

## GROUPING SETS

Works with Exasol, not Snowflake.

```shell
% echo "SELECT foo, bar FROM baz GROUP BY GROUPING SETS (foo, bar)" | sqlfluff parse -c --dialect snowflake -
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    statement:
[L:  1, P:  1]      |        select_statement:
[L:  1, P:  1]      |            select_clause:
[L:  1, P:  1]      |                keyword:                                      'SELECT'
[L:  1, P:  8]      |                select_clause_element:
[L:  1, P:  8]      |                    column_reference:
[L:  1, P:  8]      |                        identifier:                           'foo'
[L:  1, P: 11]      |                comma:                                        ','
[L:  1, P: 13]      |                select_clause_element:
[L:  1, P: 13]      |                    column_reference:
[L:  1, P: 13]      |                        identifier:                           'bar'
[L:  1, P: 17]      |            from_clause:
[L:  1, P: 17]      |                keyword:                                      'FROM'
[L:  1, P: 22]      |                from_expression:
[L:  1, P: 22]      |                    from_expression_element:
[L:  1, P: 22]      |                        table_expression:
[L:  1, P: 22]      |                            table_reference:
[L:  1, P: 22]      |                                identifier:                   'baz'
[L:  1, P: 26]      |            groupby_clause:
[L:  1, P: 26]      |                keyword:                                      'GROUP'
[L:  1, P: 32]      |                keyword:                                      'BY'
[L:  1, P: 35]      |                column_reference:
[L:  1, P: 35]      |                    identifier:                               'GROUPING'
[L:  1, P: 43]      |                unparsable:                                   !! Expected: 'Nothing...'
[L:  1, P: 44]      |                    raw:                                      'SETS'
[L:  1, P: 49]      |                    bracketed:
[L:  1, P: 49]      |                        start_bracket:                        '('
[L:  1, P: 50]      |                        raw:                                  'foo'
[L:  1, P: 53]      |                        comma:                                ','
[L:  1, P: 55]      |                        raw:                                  'bar'
[L:  1, P: 58]      |                        end_bracket:                          ')'

==== parsing violations ====
L:   1 | P:  43 |  PRS | Line 1, Position 43: Found unparsable section: ' SETS (foo, bar)'

% echo "SELECT foo, bar FROM baz GROUP BY GROUPING SETS (foo, bar)" | sqlfluff parse -c --dialect exasol -
# all good
```

## CALL

Works with MySQL, not Snowflake.

```shell
% echo "CALL foo(1);" | sqlfluff parse -c --dialect snowflake -
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    statement:
[L:  1, P:  1]      |        unparsable:                                           !! Expected: 'StatementSegment'
[L:  1, P:  1]      |            raw:                                              'CALL'
[L:  1, P:  6]      |            raw:                                              'foo'
[L:  1, P:  9]      |            bracketed:
[L:  1, P:  9]      |                start_bracket:                                '('
[L:  1, P: 10]      |                raw:                                          '1'
[L:  1, P: 11]      |                end_bracket:                                  ')'
[L:  1, P: 12]      |    statement_terminator:                                     ';'

==== parsing violations ====
L:   1 | P:   1 |  PRS | Line 1, Position 1: Found unparsable section: 'CALL foo(1)'

% echo "CALL foo(1);" | sqlfluff parse -c --dialect mysql -
# all good
```

## Version

Running sqlfluff directly from the current `master` branch.
```
% sqlfluff --version
sqlfluff, version 0.6.0
% python --version
Python 3.8.10
```

## Configuration

Default configuration.

### LINKED ISSUE #1224: Snowflake dialect issues
CREATE ROLE IF NOT EXISTS ROLE-NAME-DASH;
SET THIS_ROLE=CURRENT_ROLE();
GRANT ROLE ROLE-NAME-DASH TO ROLE IDENTIFIER($THIS_ROLE);
CALL MyStoredProcedure(CURRENT_ROLE());
GRANT OWNERSHIP ON USER MYUSER TO ROLE SOME_ROLE;

## Expected Behaviour
1. object names with dashes are valid
2. SET variable is valid
3. referencing variable is valid $THIS_ROLE
4. CALL stored procedure is valid
5. changing ownership role on USER is valid.

## Observed Behaviour
== [test.sql] FAIL
L:   1 | P:  31 |  PRS | Line 1, Position 31: Found unparsable section:
                       | '-NAME-DASH'
L:   1 | P:  31 | L006 | Missing whitespace after -
L:   2 | P:   1 |  PRS | Line 2, Position 1: Found unparsable section: 'SET
                       | THIS_ROLE=CURRENT_ROLE()'
L:   3 | P:   1 |  PRS | Line 3, Position 1: Found unparsable section: 'GRANT
                       | ROLE ROLE-NAME-DASH TO ROLE IDENTI...'
L:   3 | P:  46 |  LXR | Unable to lex characters: '$THIS_ROLE...'
L:   4 | P:   1 |  PRS | Line 4, Position 1: Found unparsable section: 'CALL
                       | MyStoredProcedure(CURRENT_ROLE())'
L:   5 | P:   1 |  PRS | Line 5, Position 1: Found unparsable section: 'GRANT
                       | OWNERSHIP ON USER MYUSER TO ROLE S...'
All Finished 📜 🎉!

## Steps to Reproduce
sqlfluff lint --dialect snowflake test.sql

## Version
0.6.1
python 3.8

### LINKED ISSUE #1345: Snowflake Is Inheriting From Postgres
Snowflake dialect inherits from Postgres. It shouldn't, it isn't based on Postgres. It adds a dependency when developing in Postgres, to ensure that a) your code is Snowflake compliant, b) you add a hack into your code to keep it Snowflake compliant, or c) you fix Snowflake's issues. 

An example:

ANSI Dialect defines DESCRIBE parse grammar as 

```
    parse_grammar = Sequence(
        "DESCRIBE",
        Ref("NakedIdentifierSegment"),
        Ref("ObjectReferenceSegment"),
    )
```

where NakedIdentifierSegment is:

```
        lambda dialect: RegexParser(
            r"[A-Z0-9_]*[A-Z][A-Z0-9_]*",
            CodeSegment,
            name="naked_identifier",
            type="identifier",
            anti_template=r"^(" + r"|".join(dialect.sets("reserved_keywords")) + r")$",
        )
```

In Postgres, USER is a reserved keyword.

In Snowflake, this is a valid command:

```
DESCRIBE USER my_user;
```

### PR DESCRIPTION
**Pull request by tunetheweb**
### Brief summary of the change made

Separated out Snowflake from Postgres and added a lot of new syntax after doing a sweep of the [open Snowflake issues](https://github.com/sqlfluff/sqlfluff/issues?q=is%3Aissue+is%3Aopen+label%3Asnowflake).

- Fixes #996 - Support `SET`
- Fixes #1201 - Support `CREATE MASKING POLICY`
- Fixes #1202 - Support `SET MASKING POLICY`
- Fixes #1209 - Support Snowflake `COMMENT`
- Fixes #1210 - Support `MERGE INTO` and `GROUPING SETS`
- Fixes #1224 - Support `SET`, `GRANT ROLE`, `CALL`, `GRANT OWNERSHIP`
Makes progress on  #1227 - Adds initial support for PIPES (Paths and Externals not supported)
- Fixes #1345 - Snowflake is now dependent on ANSI dialect directly and not postgres.
- Added DELETE... USING... syntax (see https://github.com/sqlfluff/sqlfluff/pull/1353#issuecomment-912861336)

Also added a lot of test coverage for this.

### Are there any other side effects of this change that we should be aware of?

Snowflake is now no longer dependent on Postgres as per #1345

### Pull Request checklist
- [X] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/parser` (note YML files can be auto generated with `python test/generate_parse_fixture_yml.py` or by running `tox` locally).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by NathanHowell** [comment]
@tunetheweb is it difficult to add support for `DELETE FROM x USING y, z`?

**Comment by tunetheweb** [comment]
> @tunetheweb is it difficult to add support for `DELETE FROM x USING y, z`?

Like the other maintainers aren't already gonna kill me for the size of this PR! 😉

Oh well, might as well be hung for a sheep as a lamb! Added in https://github.com/sqlfluff/sqlfluff/pull/1353/commits/2176a6e62e70e08a51187de7fcc8012541532fe1

Next time an issue would be appreciated so can reference in PR.

**Comment by WittierDinosaur** [comment]
Great stuff! Looks good, but there's so much I have no idea how to review it.

**Comment by tunetheweb** [comment]
> Great stuff! Looks good, but there's so much I have no idea how to review it.

Yeah it's quite chunky alight. But if you could have a review it would be greatly appreciated!

- The new YML files can be ignored as auto generated.
- The edits to existing YMLs ones are small (though just spotted two incorrect ones I've just fixed so goes to show you never can tell!).
- The SQL just needs a glance over to see if you agree with it, think it's representative coverage, or can think of any other edge cases. I've included all examples from the Snowflake documentation for that syntax so think this should be good and not require much of a review, but let me know if you diagree.
- The ANSI changes are very small and due to the fact that permissions are handled here even if dialect specific (there's a note in the file explaining why). Anyway that's the only reason there are any changs there.

After that we're left with the big one - the dialect_snowflake.py file changes.

Obviously there are a lot here! There's no denying that. And maybe in hindsight I should have stopped myself and raised several PRs for this instead of lumping in one big one, but I got carried away. Saying that, most of them are fairly standard grammar additions so would be good to know if you spot anything here you would have done differently, or which you're having trouble following.

**Review by WittierDinosaur — APPROVED** [review]
Looks good to me. With the understanding that the size of it means the review can't be all that in-depth, nothing in the code is screaming out as wrong. Any bugs that may be lurking will no doubt be minor compared to the amount of content added. Have you cross-referenced the functions added with the postgres-inherited functions that will be lost?

**Comment by tunetheweb** [comment]
> Looks good to me. With the understanding that the size of it means the review can't be all that in-depth, nothing in the code is screaming out as wrong. Any bugs that may be lurking will no doubt be minor compared to the amount of content added.

Thanks @WittierDinosaur ! Now if any @sqlfluff/sqlfluff-maintainers fancies giving their OK then I can merge?

> Have you cross-referenced the functions added with the postgres-inherited functions that will be lost?

Yes, but with the last released version. As noted in https://github.com/sqlfluff/sqlfluff/pull/1347#discussion_r701451147 there wasn't actually that much in there, before all this recent Postgres activity! For each one that I added in (can't even remember if there was any to be honest!), I double checked the Snowflake syntax and didn't add it back in (or added a corrected version). So pretty sure we haven't lost anything in this from last release.

I didn't check anything since the last release, so might not have gained as much as if we'd stayed on Postgres but, as you correctly noted, the are often different anyway and if there was a desire for those functions I'm presuming an issue would have been raised.

**Review by barrywhart — APPROVED** [review]
Looks great!

**Comment by NiallRees** [comment]
This is ace @tunetheweb 😍

**Pull request merged**
