### PR TITLE
Add missing chardet install in setup.py

### LINKED ISSUE #1925: Add chardet to setup.py installation requirements
## Expected Behaviour

Able to run sqlfluff after `pip install sqlfluff==0.8.1`

## Observed Behaviour
```
import chardet
ModuleNotFoundError: No module named 'chardet'
```

## Steps to Reproduce

`pip install sqlfluff==0.8.1` on a system that doesn't have `chardet` installed.

## Version
sqlfluff version 0.8.1
python version 3.6.2

### PR DESCRIPTION
**Pull request by jpy-git**
### Brief summary of the change made

Fixes #1925. chardet was missing from setup.py. 

The reason we likely missed this in unit tests was because in tox.ini we install requirements.txt (which had chardet), followed by a developer install of sqlfluff, rather than installing the package and its requirements via just setup.py. This is something I've already resolved in #1860 so just need that merged in to prevent this in the future.

### Are there any other side effects of this change that we should be aware of?
No, fixes missing requirement

### Pull Request checklist
- [X] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `python test/generate_parse_fixture_yml.py` or by running `tox` locally).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by tunetheweb** [comment]
Hmmmm #1843 was supposed to prevent this happening. Any ideas why that didn't pick this up this time?

**Comment by jpy-git** [comment]
@tunetheweb because `pip-test-pull-request` only checks parse/lint of a statement via stdin. `chardet` is used to detect character encoding of a file so those tests don't touch the bit of the code that tries to `import chardet`

**Comment by tunetheweb** [comment]
OK cause we're using stdin for our test. Which I specifically choose as wouldn't have access to the repo.

Wonder should we enhance that as part of this to also add a test like this:

```yml
    - name: Run a simple select lint test with a file
      run: |
        echo "select 1" > test.sql
        sqlfluff lint test.sql
```

WDYT?

**Comment by jpy-git** [comment]
yeah makes sense!

or could do `sqlfluff lint <(echo "select 1")` which mimics file input

**Comment by jpy-git** [comment]
maybe do one via std in and one via file

**Comment by jpy-git** [comment]
that plus #1860 should put us in a pretty good position to catch these in the future

**Comment by tunetheweb** [comment]
Cool can you add to this PR then? Will have another look at #1860

**Comment by jpy-git** [comment]
got those extra pip test added :)

**Review by barrywhart — APPROVED** [review]

**Comment by barrywhart** [comment]
Good catch! This has probably been broken for months. 😅

**Comment by jpy-git** [comment]
We should look at removing `requirements.txt` at some point as `tox` handles all the requirements from `setup.py`, so `requirements.txt` is unnecessary and likely to cause confusion.

Similar for `requirements_dev.txt` as those dependencies can just go in their own tox environment. (i.e run tox -e flake8) to run flake8 in it's own environment

**Comment by barrywhart** [comment]
I think the txt files are useful for ensuring stable CI builds. A new dependent package may break SQLFluff, but it shouldn't break the build.

One technique I've found very useful is to have two flavors of the build, one using just setup.py and one using txt files. If both break, it's a bug in our code. If only the former one breaks, that's an issue with a dependency. Saves a lot of "red herring" issues...

**Comment by jpy-git** [comment]
> One technique I've found very useful is to have two flavors of the build, one using just setup.py and one using txt files. If both break, it's a bug in our code. If only the former one breaks, that's an issue with a dependency. Saves a lot of "red herring" issues...

but surely if you just run `tox -e py` it installs the deps first from setup.py so if there was an error in the dependencies install you'd just see it in the log?
The only places requirements.txt is used in the ci is `check-yaml-files-generation.yml` and `.readthedocs.yml`  both of which should be replaced with tox for consistency

**Comment by tunetheweb** [comment]
We've never convinced @barrywhart to use `tox` 😁

**Pull request merged**
