### PR TITLE
Add a --quiet option for fix

### LINKED ISSUE #1834: Enable quiet mode/no-verbose in CLI for use in pre-commit hook
There seems to be only an option to increase the level of verbosity when using SQLFluff [CLI](https://docs.sqlfluff.com/en/stable/cli.html), not to limit it further.

It would be great to have an option to further limit the amount of prints when running `sqlfluff fix`, especially in combination with deployment using a pre-commit hook. For example, only print the return status and the number of fixes applied, similar to how it is when using `black` in a pre-commit hook:
image

This hides the potentially long list of fixes that are being applied to the SQL files, which can get quite verbose.

### PR DESCRIPTION
**Pull request by alanmcruickshank**
This resolves #1834. Another oldie, but perhaps useful for some users. Added a few type hints along the way.

### CODE REVIEW

**Comment by WittierDinosaur** [comment]
What's the rationale behind requiring force?

**Comment by alanmcruickshank** [comment]
> What's the rationale behind requiring force?

I was thinking that unless there's _some_ output, then you wouldn't know what you were confirming. That means that it would feel a bit strange to ask for confirmation.

If you were a user and used `--quiet` but not `--force` what would you expect to happen?

**Comment by WittierDinosaur** [comment]
i was thinking it'd be along the lines of:
```
sqlfluff fix --quiet
12 fixable violations found
Confirm fix?
```

**Review by WittierDinosaur — APPROVED** [review]
LGTM

**Pull request merged**
