### PR TITLE
Pytest coverage exceptions for Core code - part 1

### PR DESCRIPTION
**Pull request by tunetheweb**
### Brief summary of the change made

Progress on #1314 this adds coverage exceptions (using `# pragma: no cover`) for the `src/sql/core` files exception for:
- src/sql/core/parser (big one and this PR is big enough)
- src/sql/core/templaters (a lot of changes in #1264 waiting to be merged so best left alone)

**_It often seems to be `src/sqlfluff/core/linter/runner.py` which causes us noise in PR so hopefully the fact it is covered to 100% in this PR will reduce that noise until we can get to 100%._**

The remaining ones will be covered in a future PR.

The rest have been addressed and now show 100% coverage:

```
Name                                                 Stmts   Miss  Cover   Missing
----------------------------------------------------------------------------------
src/sqlfluff/__init__.py                                 9      0   100%
src/sqlfluff/api/__init__.py                             2      0   100%
src/sqlfluff/api/info.py                                 9      0   100%
src/sqlfluff/api/simple.py                              32      0   100%
src/sqlfluff/cli/__init__.py                             0      0   100%
src/sqlfluff/cli/commands.py                           276      0   100%
src/sqlfluff/cli/formatters.py                         134      0   100%
src/sqlfluff/cli/helpers.py                             75      0   100%
src/sqlfluff/core/__init__.py                            8      0   100%
src/sqlfluff/core/config.py                            266      0   100%
src/sqlfluff/core/dialects/__init__.py                  17      0   100%
src/sqlfluff/core/dialects/base.py                      83      0   100%
src/sqlfluff/core/dialects/common.py                     9      0   100%
src/sqlfluff/core/errors.py                             67      0   100%
src/sqlfluff/core/file_helpers.py                        9      0   100%
src/sqlfluff/core/linter/__init__.py                     4      0   100%
src/sqlfluff/core/linter/common.py                      35      0   100%
src/sqlfluff/core/linter/linted_dir.py                  44      0   100%
src/sqlfluff/core/linter/linted_file.py                178      0   100%
src/sqlfluff/core/linter/linter.py                     329      0   100%
src/sqlfluff/core/linter/linting_result.py              72      0   100%
src/sqlfluff/core/linter/runner.py                      86      0   100%
src/sqlfluff/core/parser/__init__.py                     7      0   100%
src/sqlfluff/core/parser/context.py                     82      7    91%   50-51, 120-121, 156, 182, 195
src/sqlfluff/core/parser/grammar/__init__.py             6      0   100%
src/sqlfluff/core/parser/grammar/anyof.py               98      2    98%   84, 188
src/sqlfluff/core/parser/grammar/base.py               273     19    93%   103, 173, 284, 288, 472, 594, 650, 660, 674, 738, 744-745, 759-760, 795, 807, 829, 839-847
src/sqlfluff/core/parser/grammar/conditional.py         34      7    79%   46, 50, 54, 56, 60, 71, 88
src/sqlfluff/core/parser/grammar/delimited.py           76      5    93%   33, 84, 130, 178, 211
src/sqlfluff/core/parser/grammar/greedy.py              86     11    87%   34, 82-83, 85-86, 98-99, 101-102, 142, 180
src/sqlfluff/core/parser/grammar/noncode.py             18      2    89%   24, 30
src/sqlfluff/core/parser/grammar/sequence.py           135      7    95%   54, 111, 224, 252, 290, 311-312
src/sqlfluff/core/parser/helpers.py                     30      2    93%   8, 30
src/sqlfluff/core/parser/lexer.py                      216      4    98%   196, 249, 312, 546
src/sqlfluff/core/parser/markers.py                     77      6    92%   10, 52, 55, 58, 61, 105
src/sqlfluff/core/parser/match_logging.py               35      1    97%   22
src/sqlfluff/core/parser/match_result.py                55     10    82%   12, 75-83, 91-92, 100, 120
src/sqlfluff/core/parser/match_wrapper.py               26      1    96%   55
src/sqlfluff/core/parser/matchable.py                   15      3    80%   9-10, 30
src/sqlfluff/core/parser/parser.py                      16      1    94%   9
src/sqlfluff/core/parser/parsers.py                     59      1    98%   175
src/sqlfluff/core/parser/segments/__init__.py            5      0   100%
src/sqlfluff/core/parser/segments/base.py              434     38    91%   88, 96, 102, 111, 147, 196, 223, 247-252, 254, 305-306, 328, 362, 457, 473, 541-554, 618-621, 737, 758, 780, 786, 797, 898, 907, 975, 1055
src/sqlfluff/core/parser/segments/ephemeral.py          25      0   100%
src/sqlfluff/core/parser/segments/generator.py           5      0   100%
src/sqlfluff/core/parser/segments/meta.py               35      3    91%   28, 83, 103
src/sqlfluff/core/parser/segments/raw.py               110      1    99%   140
src/sqlfluff/core/plugin/__init__.py                     4      0   100%
src/sqlfluff/core/plugin/hookspecs.py                    9      0   100%
src/sqlfluff/core/plugin/host.py                         8      0   100%
src/sqlfluff/core/plugin/lib.py                         14      0   100%
src/sqlfluff/core/rules/__init__.py                     13      0   100%
src/sqlfluff/core/rules/analysis/__init__.py             0      0   100%
src/sqlfluff/core/rules/analysis/select.py              71      0   100%
src/sqlfluff/core/rules/analysis/select_crawler.py      69      0   100%
src/sqlfluff/core/rules/base.py                        191      0   100%
src/sqlfluff/core/rules/config_info.py                   6      0   100%
src/sqlfluff/core/rules/doc_decorators.py               25      0   100%
src/sqlfluff/core/rules/loader.py                       15      0   100%
src/sqlfluff/core/string_helpers.py                     14      0   100%
src/sqlfluff/core/templaters/__init__.py                 5      0   100%
src/sqlfluff/core/templaters/base.py                   167      8    95%   53, 109, 133, 196, 226, 287, 291, 331
src/sqlfluff/core/templaters/dbt.py                    156    109    30%   47, 52-55, 60-65, 70-81, 86-89, 95-132, 137-164, 175-191, 198-211, 215, 221-224, 240-282, 285-369
src/sqlfluff/core/templaters/jinja.py                  148      6    96%   59, 90, 136, 199, 262-264
src/sqlfluff/core/templaters/python.py                 343      6    98%   564, 775-787, 878
src/sqlfluff/core/timing.py                             21      0   100%
src/sqlfluff/dialects/__init__.py                        0      0   100%
src/sqlfluff/dialects/ansi_keywords.py                   2      0   100%
src/sqlfluff/dialects/dialect_ansi.py                  478      0   100%
src/sqlfluff/dialects/dialect_bigquery.py              136      0   100%
src/sqlfluff/dialects/dialect_exasol.py                530      0   100%
src/sqlfluff/dialects/dialect_exasol_fs.py              85      0   100%
src/sqlfluff/dialects/dialect_mysql.py                 154      0   100%
src/sqlfluff/dialects/dialect_postgres.py               43      0   100%
src/sqlfluff/dialects/dialect_snowflake.py             120      0   100%
src/sqlfluff/dialects/dialect_teradata.py              104      0   100%
src/sqlfluff/dialects/exasol_keywords.py                 3      0   100%
src/sqlfluff/diff_quality_plugin.py                     22      0   100%
src/sqlfluff/rules/L001.py                              13      0   100%
src/sqlfluff/rules/L002.py                              11      0   100%
src/sqlfluff/rules/L003.py                             201      0   100%
src/sqlfluff/rules/L004.py                              22      0   100%
src/sqlfluff/rules/L005.py                              11      0   100%
src/sqlfluff/rules/L006.py                              68      0   100%
src/sqlfluff/rules/L007.py                              29      0   100%
src/sqlfluff/rules/L008.py                              24      0   100%
src/sqlfluff/rules/L009.py                              19      0   100%
src/sqlfluff/rules/L010.py                              74      0   100%
src/sqlfluff/rules/L011.py                              22      0   100%
src/sqlfluff/rules/L012.py                               3      0   100%
src/sqlfluff/rules/L013.py                              18      0   100%
src/sqlfluff/rules/L014.py                              23      0   100%
src/sqlfluff/rules/L015.py                              28      0   100%
src/sqlfluff/rules/L016.py                             166      0   100%
src/sqlfluff/rules/L017.py                              18      0   100%
src/sqlfluff/rules/L018.py                              49      0   100%
src/sqlfluff/rules/L019.py                              56      0   100%
src/sqlfluff/rules/L020.py                              21      0   100%
src/sqlfluff/rules/L021.py                              16      0   100%
src/sqlfluff/rules/L022.py                              80      0   100%
src/sqlfluff/rules/L023.py                              29      0   100%
src/sqlfluff/rules/L024.py                               9      0   100%
src/sqlfluff/rules/L025.py                              24      0   100%
src/sqlfluff/rules/L026.py                              20      0   100%
src/sqlfluff/rules/L027.py                              12      0   100%
src/sqlfluff/rules/L028.py                              25      0   100%
src/sqlfluff/rules/L029.py                              10      0   100%
src/sqlfluff/rules/L030.py                              11      0   100%
src/sqlfluff/rules/L031.py                              76      0   100%
src/sqlfluff/rules/L032.py                               8      0   100%
src/sqlfluff/rules/L033.py                               8      0   100%
src/sqlfluff/rules/L034.py                              45      0   100%
src/sqlfluff/rules/L035.py                              18      0   100%
src/sqlfluff/rules/L036.py                              84      0   100%
src/sqlfluff/rules/L037.py                              40      0   100%
src/sqlfluff/rules/L038.py                              21      0   100%
src/sqlfluff/rules/L039.py                              27      0   100%
src/sqlfluff/rules/L040.py                               7      0   100%
src/sqlfluff/rules/L041.py                              22      0   100%
src/sqlfluff/rules/L042.py                              20      0   100%
src/sqlfluff/rules/L043.py                              43      0   100%
src/sqlfluff/rules/L044.py                              41      0   100%
src/sqlfluff/rules/L045.py                              21      0   100%
src/sqlfluff/rules/L046.py                              31      0   100%
src/sqlfluff/rules/L047.py                              21      0   100%
src/sqlfluff/rules/L048.py                              12      0   100%
src/sqlfluff/rules/__init__.py                           0      0   100%
src/sqlfluff/testing/__init__.py                         0      0   100%
src/sqlfluff/testing/rules.py                           72      0   100%
----------------------------------------------------------------------------------
TOTAL                                                 8387    260    97%
```

Most of the missing coverage is for exceptions that do not need test coverage. There are a few that ideally we would have coverage for. They have been marked `TODO` for now, but still skipped from coverage as the aim is to get us to 100% coverage given the tests we have (or the easy ones to add) to more easily spot regressions and avoid the coverage alert changes we frequently see now. I couldn't see any easy tests to add for the `TODO`s that I could add to this PR.

### Are there any other side effects of this change that we should be aware of?
Only side effect is some lines that possible should be covered are now accepted as not having coverage. They have been marked with TODO if anyone wants to add coverage at some point.

### Pull Request checklist
- [X] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/parser` (note YML files can be auto generated with `python test/generate_parse_fixture_yml.py` or by running `tox` locally).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

Not applicable for this change.

### CODE REVIEW

**Review by barrywhart — APPROVED** [review]
Looks good to me! If Alan has time to review, that may be good, since he's familiar with the entire breadth of the code. But IIRC, he's already mentioned being on board with these kinds of changes, so I'll leave that up to you whether to go ahead and merge or not. 🙏🏽

**Comment by tunetheweb** [comment]
I say merge. Only a small number of statements that possible could do with better coverage and don’t think they are worth worrying about now to be honest.

Once we’re at 100% it’ll be much easier to gate keep for coverage at the time code is written when it’s fresh in people’s minds.

**Comment by barrywhart** [comment]
Do it! Do it!

**Comment by tunetheweb** [comment]
It will be done - the second my other one is merged - to make sure it doesn’t ruin all the work done here!!

**Pull request merged**
