### PR TITLE
L060: More specific description

### LINKED ISSUE #2415: Rule L060 could give a specific error message
At the moment rule L060 flags something like this:

```
L:  21 | P:   9 | L060 | Use 'COALESCE' instead of 'IFNULL' or 'NVL'.
```

Since we likely know the wrong word, it might be nice to actually flag that instead of both `IFNULL` and `NVL` - like most of the other rules do.

That is it should flag this:

```
L:  21 | P:   9 | L060 | Use 'COALESCE' instead of 'IFNULL'.
```
 Or this:

```
L:  21 | P:   9 | L060 | Use 'COALESCE' instead of 'NVL'.
```

As appropriate.

What do you think @jpy-git ?

### PR DESCRIPTION
**Pull request by jpy-git**
### Brief summary of the change made

Closes #2415. Adds a more specific lint description depending on the detected function.

image

### Are there any other side effects of this change that we should be aware of?
No

### Pull Request checklist
- [X] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by tunetheweb — COMMENTED** [review]
Should we add a test for this?

**Comment by jpy-git** [comment]
> Should we add a test for this?

I think in general we've stuck with just the yml tests for rules, i.e. if I'd have added this as part of the initial PR would we have added the test case?

**Comment by tunetheweb** [comment]
Well I would have :-)

What if this breaks in future and spits out garbage?

See here for examples:

https://github.com/sqlfluff/sqlfluff/blob/0dbc5edbc348d1ec2c9d0975182e0c3d77c5c0e5/test/rules/std_L048_test.py#L14-L16

**Comment by jpy-git** [comment]
Added the test 👍

**Review by tunetheweb — APPROVED** [review]

**Pull request merged**
