### PR TITLE
Mask linting errors around templated sections.

### PR DESCRIPTION
**Pull request by alanmcruickshank**
I think this addresses #713 and relates to the conversation we had with @sqlfluff/sqlfluff-maintainers earlier this week.

This enables masking of linting errors within templated sections using the new source mapping code.

### CODE REVIEW

**Comment by alanmcruickshank** [comment]
@NiallRees - could you take a look at this one?
1. Whether this is kind of what you had in mind?
2. Why the test is failing? It passes on my local machine 🤔

**Comment by NiallRees** [comment]
Could you pr this branch onto the one in my PR? Curious to see if the test I added now passes!

**Comment by NiallRees** [comment]
Merged it into my branch, will see what happens: https://github.com/sqlfluff/sqlfluff/pull/603

**Comment by alanmcruickshank** [comment]
> Merged it into my branch, will see what happens: #603

This won't solve any of the issues in the slicing, or even the autodetection, it's just a straight ignore. Sufficient for the macros use case, but I think we might need to do a little more in the other PR.

**Comment by alanmcruickshank** [comment]
btw @NiallRees - I've fixed the reason that these tests were failing (was a gitignore problem). If you like what I've done here, can you approve and I'll merge it to master, then I can just help with the wrapping in your other PR.

**Review by NiallRees — APPROVED** [review]

**Comment by NiallRees** [comment]
Merged so we don't have to keep updating with master.

**Comment by pwildenhain** [comment]
FYI I have been having some trouble with the templated sections still being linted, I just haven't taken the time to submit but reports 🙊 -- I'll try to submit some reprex's in issue(s) this week

**Pull request merged**
