### PR TITLE
Add config setting to allow customizing macro load order

### LINKED ISSUE #2636: Allow macros macros for templater Jinja
SQLFluf does not parse macro if the macro is present in macro.

For example: 
/models/my_model.sql
```
SELECT
    * -- for example
FROM my_table
```

/macros/get_list.sql
```
{% macro get_list() %}
    {% set query %}
        SELECT
            * -- for the example
        FROM {{ ref('my_model') }}
    {% endset %}
    {% set results = run_query(query) %}
    {% if execute %}
        {% set results_list = results.rows %}
    {% else %}
        {% set results_list = [] %}
    {% endif %}
    {{ return(results_list) }}
{% endmacro %}
```
In this condition, we have the following error message
```
sqlfluff lint models/my_model.sql
```
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/sqlfluff", line 33, in <module>
    sys.exit(load_entry_point('sqlfluff==0.10.0', 'console_scripts', 'sqlfluff')())
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/cli/commands.py", line 518, in lint
    result = lnt.lint_paths(
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/linter/linter.py", line 1035, in lint_paths
    self.lint_path(
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/linter/linter.py", line 987, in lint_path
    for i, linted_file in enumerate(runner.run(fnames, fix), start=1):
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/linter/runner.py", line 101, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/linter/runner.py", line 54, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/linter/runner.py", line 43, in iter_rendered
    yield fname, self.linter.render_file(fname, self.config)
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/linter/linter.py", line 710, in render_file
    return self.render_string(raw_file, fname, config, encoding)
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/linter/linter.py", line 681, in render_string
    templated_file, templater_violations = self.templater.process(
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/templaters/jinja.py", line 319, in process
    env, live_context, make_template = self.template_builder(
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/templaters/jinja.py", line 276, in template_builder
    live_context = self.get_context(fname=fname, config=config, env=env)
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/templaters/jinja.py", line 255, in get_context
    self._extract_macros_from_path(
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/templaters/jinja.py", line 90, in _extract_macros_from_path
    cls._extract_macros_from_path(
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/templaters/jinja.py", line 82, in _extract_macros_from_path
    cls._extract_macros_from_template(template, env=env, ctx=ctx)
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/sqlfluff/core/templaters/jinja.py", line 59, in _extract_macros_from_template
    for k in macro_template.module.__dict__:
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/jinja2/environment.py", line 1472, in module
    return self._get_default_module()
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/jinja2/environment.py", line 1440, in _get_default_module
    self._module = self.make_module()
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/jinja2/environment.py", line 1399, in make_module
    return TemplateModule(self, ctx)
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/jinja2/environment.py", line 1529, in __init__
    body_stream = list(template.root_render_func(context))  # type: ignore
  File "<template>", line 14, in root
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/opt/homebrew/Cellar/sqlfluff/0.10.0/libexec/lib/python3.10/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'ref' is undefined
```
This error is generated because we check first our own macros here [sqlfluff/core/templaters/jinja.py](https://github.com/sqlfluff/sqlfluff/blob/4d526107c32946d87858cd766a99adfdbb056175/src/sqlfluff/core/templaters/jinja.py#L230)

If we update the code
```
            # Get macros from config - useful if we have macros in our macros
            # models -> macros -> macros
            macros_from_config = self._extract_macros_from_config(
                config=config, env=env, ctx=live_context
            )
            live_context.update(macros_from_config)

            # Get macros from libraries - useful if we have macros in our macros
            # models -> macros -> macros
            libraries_from_config = self._extract_libraries_from_config(config=config)
            live_context.update(libraries_from_config)

            macros_path = self._get_macros_path(config)
            if macros_path:
                live_context.update(
                    self._extract_macros_from_path(
                        macros_path, env=env, ctx=live_context
                    )
                )

            # Load config macros, these will take precedence over macros from the path
            live_context.update(macros_from_config)
            live_context.update(libraries_from_config)
```

### PR DESCRIPTION
**Pull request by fbb-oc**
### Brief summary of the change made
fixes #2636 

Before : 
- marcro is loaded inside project repository
- macro is loaded in config file sqlfluff
- macro is loaded in dbt macro repository
After
- macro is loaded in config file sqlfluff
- macro is loaded in dbt macro repository
- marcro is loaded inside project repository
- macro is loaded in config file sqlfluff
- macro is loaded in dbt macro repository

In the case where we load a macro inside a macro, SQLFluff dont retrieve the macro and throw an exception.
With the new order, we load a first time macro from the config and dbt macro directory and avoid the exception.

We conserve the order because we update a second time the list of macro with the original order.

### CODE REVIEW

**Comment by barrywhart** [comment]
The change is causing a test to fail. Perhaps the test has two conflicting definitions of the same macro, and now a different one is being used. Can you take a look at this, @fbb-oc?

**Comment by tunetheweb** [comment]
@fbb-oc is this still being worked on?

**Comment by fbb-oc** [comment]
Hello,

Yes, just no time to work on this. I hope to finish this this week.


Florent Bertrand

Data Engineering Manager
[image: Openclassrooms Logo]

OpenClassrooms - 10 Quai de la Charente - 75019 Paris - France

Suivez-nous sur Twitter <https://twitter.com/openclassrooms>, Facebook
<https://www.facebook.com/openclassrooms>, LinkedIn
<https://www.linkedin.com/school/openclassrooms/mycompany/>


Le dim. 3 avr. 2022 à 18:46, Barry Pollard ***@***.***> a
écrit :

**Review by barrywhart — CHANGES_REQUESTED** [review]
See earlier comment about needing to make it configurable and probably adding tests.

**Comment by fbb-oc** [comment]
> See earlier comment about needing to make it configurable and probably adding tests.

I add a part to configure the order (with by default the existing version).
Is it possible to check if ok ? it would make the IC run

**Comment by barrywhart** [comment]
Please add tests. It would be good to have a test for the scenario described in #2636, where it only works if a different order is configured. The new test could potentially be a new test case for this [existing set of tests](https://github.com/sqlfluff/sqlfluff/blob/main/test/core/templaters/jinja_test.py#L559L609), or something similar.

**Comment by fbb-oc** [comment]
I change the templater from jinja to dbt and it is ok; My PR is not necessary
I close

**Comment by tunetheweb** [comment]
I'm going to close this again. OP had closed it and know @barrywhart thought it might still be useful but  it doesn't seem to be being actively worked on at the mo so is just hanging around creating noise IMHO.

**Pull request closed without merging**
