### PR TITLE
Fix Windows CI check

### PR DESCRIPTION
**Pull request by greg-finley**
### Brief summary of the change made

Looks like Windows CI check is failing on many branches. See if pinning helps. https://github.com/sqlfluff/sqlfluff/actions/runs/3331475162/jobs/5511256473

### Are there any other side effects of this change that we should be aware of?
Eventually we'd get out of date if we pin? 🤷 

### Pull Request checklist
- [ ] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by barrywhart** [comment]
Looks like the same error as before:
```
INTERNALERROR> E               File "D:\a\sqlfluff\sqlfluff\.tox\winpy\lib\site-packages\pytest_sugar.py", line 242, in pytest_sessionstart
INTERNALERROR> E                 self._sessionstarttime = py.std.time.time()
INTERNALERROR> E             AttributeError: module 'py' has no attribute 'std'
```

Want to try removing `pytest-sugar` from `requirements_dev.txt`?

**Review by barrywhart — APPROVED** [review]
If it passes, ship it! 🙂

**Comment by greg-finley** [comment]
I guess this was another solution, but 🤷 : https://github.com/Teemu/pytest-sugar/issues/241

**Comment by barrywhart** [comment]
That explains why it broke! If we pinned all our dev dependencies, we'd avoid some surprises like this.

Pytest-sugar sounds completely useless for CICD builds, but could be slightly nice for local test runs (see description in the link below). I think our fix was fine.

https://pypi.org/project/pytest-sugar/

**Pull request merged**
