### PR TITLE
Add ALTER TASK to Snowflake dialect

### PR DESCRIPTION
**Pull request by matthieucan**
Hello,
This PR brings the `ALTER TASK` statements to the Snowflake grammar. See https://docs.snowflake.com/en/sql-reference/sql/alter-task.html for more details.
This is my first contribution to this repository, if there's something I didn't get right please point out and I'll make the necessary changes!

### CODE REVIEW

**Review by alanmcruickshank — APPROVED** [review]
Nice 👍 . Thanks for the good test coverage.

**Comment by alanmcruickshank** [comment]
@matthieucan - would you mind updating the changelog? I think it's otherwise good to go.

**Comment by matthieucan** [comment]
> @matthieucan - would you mind updating the changelog? I think it's otherwise good to go.

Done! Thanks for the review :)

**Review by Arwiim — APPROVED** [review]

**Comment by matthieucan** [comment]
Hi @alanmcruickshank @Arwiim, anything else I should do to get this PR merged? :)

**Comment by barrywhart** [comment]
@matthieucan: I merged it just now. I think it got overlooked because the initial approval was prior to the CHANGELOG being merged. No policy or anything, we're just busy sometimes. 😛  Thanks for the reminder!

**Comment by barrywhart** [comment]
No worries!

**Pull request merged**
