### PR TITLE
Rule L003 performance: Cache the line number and last newline position

### PR DESCRIPTION
**Pull request by barrywhart**
### Brief summary of the change made
On each new line, L003 is rescanning the **entire** file from the beginning to the current line. This results in O(n^2) performance, i.e. really slow on large files. This small change caches the current line number and segment index (within `raw_stack`). I confirmed using `line_profiler` that this eliminates a lot of processing on a large file.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by barrywhart** [comment]
@OTooleMichael: This builds on your recent L003 changes, if you'd like to review.

**Review by tunetheweb — APPROVED** [review]
LGTM

**Comment by OTooleMichael** [comment]
Interesting, I don't see how the old code wasn't avoiding the loops in the same way? It was certainly what I intended and checked for (but didnt test as I figrured it was internal) - the line number is a good idea :) LGTM

**Comment by barrywhart** [comment]
@OTooleMichael: I only found this because of the profiler. It was showing tons of hits on this line.

Some interesting core linter performance work going on in another open PR...

**Pull request merged**
