### PR TITLE
MySQL: Implement `VALUES` function

### PR DESCRIPTION
**Pull request by hgranthorner**
Implements the `VALUES` function for `INSERT ... ON DUPLICATE KEY UPDATE` "upserts" in MySQL.

### Brief summary of the change made

No related issue (that I could find), but addresses the comment left in sqlfluff.dialects.dialect_ansi.ValuesClauseSegment. Sqlfluff now correctly parses the `VALUES` function in mysql.

### Are there any other side effects of this change that we should be aware of?

None that I could discover through testing.

### Pull Request checklist
- [X] Please confirm you have completed any of the necessary steps below.

Added both "unit" tests and fixture tests.

No additional documentation required (as far as I can tell).

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by hgranthorner** [comment]
I just force pushed linter fixed for a tidier merge. I'll switch back to develop and try your fix instead.

**Comment by tunetheweb** [comment]
OK. Might be cleaner to open a new PR if that works.

I also don't think you need `test/dialects/mysql_test.py`. We try to use fixtures when we can as easier to add new ones. We keep python test code for things that can't be tested for them. But let me know if I'm missing the point of that test and it is needed?

BTW try to avoid force pushing if you can. Makes it difficult to see what's changed since last review so need to re-review everything again 😢

**Comment by hgranthorner** [comment]
Adding the `Ref("ValuesClauseSegment")` to the `SetClauseSegment` ansi grammar still results in a `Found unparsable section:...` error. I maybe should have been more clear in this PR on what exactly it's doing. Essentially we have sql with syntax like:
```sql
insert into foo (bar, bazz) values (1, 2)
on duplicate key bar = values(bar), bazz = values(bazz)
```
But sqlfluff is unable to parse the `values(` section. I'll go ahead and remove the unit test, I'm unfamiliar with tox so it helped me to have a little unit test I could run with pytest.
And will do, no more force pushing.

**Comment by tunetheweb** [comment]
You can either revert all your changes, and add my change instead and just push these changes (without force 😁) and that will update the PR.

Or if easier you can start a new branch and a new PR and then we can close this PR if that all works.

Whichever is easiest for you.

**Comment by tunetheweb** [comment]
BTW we will squash all the commits when we merge to `main` so don't worry about lots of old commits - they will all be squashed into one commit so no one will know :-)

**Pull request closed without merging**
