### PR TITLE
feat: implement CREATE INDEX and DROP INDEX #740

### PR DESCRIPTION
**Pull request by SpokeyWheeler**
I genuinely won't be offended if you bin this, I have no idea what I'm doing! But I hope it's useful.

### CODE REVIEW

**Comment by NiallRees** [comment]
This is great @SpokeyWheeler ! Thank you. We're almost there, just needs some tests. Thankfully it's fairly easy to do, drop your initial failing queries into https://github.com/sqlfluff/sqlfluff/tree/master/test/fixtures/parser/ansi and follow the instructions [here](https://github.com/sqlfluff/sqlfluff/tree/master/test/fixtures/parser) to create the yaml files with the parsing structure.

**Comment by SpokeyWheeler** [comment]
By cracky, I think I've done it! Still only tested with 3.9, mind!

**Review by NiallRees — APPROVED** [review]
10/10!

**Comment by NiallRees** [comment]
Resolves https://github.com/sqlfluff/sqlfluff/issues/740

**Comment by SpokeyWheeler** [comment]
I am unfeasibly chuffed! 👍

**Pull request merged**
