### PR TITLE
Respect leading commas for rule L022

### LINKED ISSUE #351: Conflict between rule L019 and L022 with leading commas
**Problem**
When using leading commas you get conflicting behavior between rule L019 and rule L022. 
The rule L022 seems to state that the CTE is expected to have a blank line **after** the comma but then this make rule L019 fail due to a trailing comma. Alternatively, L019 can succeed but then L022 fails.

**Example**
Fails with rule L022:
```
with cte_a as (
    select * from table_a
)

, cte_b as (
    select * from cte_a
)

select * from cte_b

```

Fails with rule L019
```
with cte_a as (
    select * from table_a
),

cte_b as (
    select * from cte_a
)

select * from cte_b

```

**Expected**
The leading comma should be upheld for CTEs as well, that is the example where L022 fails should succeed.

**Settings**
Version: 0.3.4
Dialect: BigQuery

### LINKED ISSUE #397: L022 fails on cte with leading comma
Using the latest version from `master`

.sqlfluff
```
[sqlfluff:rules]
max_line_length = 115

[sqlfluff:indentation]
indented_joins = True

[sqlfluff:rules:L019]
comma_style = leading
```

test.sql
```sql
with cte_1 as (
    select
        *
    from
        table_1
)

, cte_2 as (
    select
        *
    from
        table_2
)

select * from table_3
```

```
$ sqlfluff lint test.sql
== [test.sql] FAIL
L:   8 | P:   3 | L022 | Blank line expected but not found after CTE definition.
```

If I remove the leading comma config, and make the comma trailing, then it passes

### PR DESCRIPTION
**Pull request by pwildenhain**
Fixes #397 and fixes #351

### CODE REVIEW

**Comment by pwildenhain** [comment]
🤔 Not sure why the coverage when down, since I _did_ add two test cases for the change I made. Does it have something to do with adding `comma_style` to the `default_config.cfg`?

**Comment by pwildenhain** [comment]
Seems like I addressed the code coverage issue, not sue why the CI is still failing :cry:

**Comment by pwildenhain** [comment]
So I _finally_ got the CI to pass 😓 by testing my new lines more explicitly. Not sure which version of the test I like more though. Interested to hear your feedback on how any testing could be improved 🙇‍♂️

**Review by alanmcruickshank — APPROVED** [review]
Looks great to me 👍 .

I initially raised an eyebrow at how you fetch the rules in `test_improper_configs_are_rejected` but it's actually quite an elegant solution.

Well done.

**Pull request merged**
