### PR TITLE
Add sqlfluff.core.rules.std to setup.py

### PR DESCRIPTION
**Pull request by Aeolun**
It seems this prevented installation

### CODE REVIEW

**Comment by NiallRees** [comment]
Thanks @Aeolun I wonder if we can just use find_packages instead of having to specify them?

**Comment by NiallRees** [comment]
I'm hoping this may also fix https://github.com/sqlfluff/sqlfluff/issues/694 which would be great

**Comment by pwildenhain** [comment]
> 
> 
> Thanks @Aeolun I wonder if we can just use find_packages instead of having to specify them?


Do you think we should push this through for now, so that people can install from GitHub? I totally agree though, we should use something like `find_packages` or [`find_namespace_packages`](https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages) to avoid issues like these in the future.

**Comment by barrywhart** [comment]
A quick fix is probably fine for now. +1 for using something like `find_packages()` going forward, though.

There is another approach we might consider. `setup.py` itself is gradually going away in Python. It's being replaced by `setup.cfg`. It's probably a bit less powerful, but it's driven by configuration rather than code. We started using it on our projects a few months back.

Here's an overview by Brett Cannon. He is a core Python committer, so he knows his stuff.
https://snarky.ca/what-the-heck-is-pyproject-toml/

**Comment by NiallRees** [comment]
Agreed both ^ will merge for now

**Review by NiallRees — APPROVED** [review]

**Pull request merged**
