### PR TITLE
Enable parsing of CLONE keyword in bigquery dialect

### PR DESCRIPTION
**Pull request by realLyans**
### Brief summary of the change made
Enable parsing of CLONE keyword in bigquery dialect

### Are there any other side effects of this change that we should be aware of?
No

### Pull Request checklist
- [X] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
- Added appropriate documentation for the change.

### CODE REVIEW

**Comment by WittierDinosaur** [comment]
Hey @realLyans , it looks like your yaml files aren't matching. Can you run `python test/generate_parse_fixture_yml.py` and push again?

**Comment by realLyans** [comment]
> 

Hi @WittierDinosaur I think it is an error that I do not know how to solve... The python file wasn't able to parse CLONE as it recognised as 'unparsable'. I digged a bit and couldn't figure out what happened.

**Comment by realLyans** [comment]
> # [Codecov](https://codecov.io/gh/sqlfluff/sqlfluff/pull/3984?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=sqlfluff) Report
> Base: **100.00**% // Head: **99.99**% // Decreases project coverage by **`-0.00%`** ⚠️
> 
> > Coverage data is based on head [(`5eac0f8`)](https://codecov.io/gh/sqlfluff/sqlfluff/pull/3984?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=sqlfluff) compared to base [(`17a9311`)](https://codecov.io/gh/sqlfluff/sqlfluff/commit/17a9311fb5c9d4b1adad3bb9f3ddd3349cd01f6f?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=sqlfluff).
> > Patch has no changes to coverable lines.
> 
> Additional details and impacted files
> [☔ View full report at Codecov](https://codecov.io/gh/sqlfluff/sqlfluff/pull/3984?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=sqlfluff). 📢 Do you have feedback about the report comment? [Let us know in this issue](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=sqlfluff).

Anything I would be able to do with this? I am not sure what it means...

**Review by greg-finley — APPROVED** [review]

**Comment by greg-finley** [comment]
> > # [Codecov](https://codecov.io/gh/sqlfluff/sqlfluff/pull/3984?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=sqlfluff) Report
> > Base: **100.00**% // Head: **99.99**% // Decreases project coverage by **`-0.00%`** ⚠️
> > > Coverage data is based on head [(`5eac0f8`)](https://codecov.io/gh/sqlfluff/sqlfluff/pull/3984?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=sqlfluff) compared to base [(`17a9311`)](https://codecov.io/gh/sqlfluff/sqlfluff/commit/17a9311fb5c9d4b1adad3bb9f3ddd3349cd01f6f?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=sqlfluff).
> > > Patch has no changes to coverable lines.
> > 
> > 
> > Additional details and impacted files
> > [☔ View full report at Codecov](https://codecov.io/gh/sqlfluff/sqlfluff/pull/3984?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=sqlfluff). 📢 Do you have feedback about the report comment? [Let us know in this issue](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=sqlfluff).
> 
> Anything I would be able to do with this? I am not sure what it means...

It's flaky sometimes. 🤷 

Thanks for your contribution!

**Pull request merged**
