### PR TITLE
Remove fixing loop from test suite.

### PR DESCRIPTION
**Pull request by alanmcruickshank**
This half addresses #499 . 

This removes the custom code from the test suite and uses the `Linter()` fix routines instead. Adding a custom runaway rule is proving harder!

### CODE REVIEW

**Review by pwildenhain — APPROVED** [review]
NIce improvement! I was scratching my head a little at this when I saw it in the test suite

**Comment by alanmcruickshank** [comment]
# Update

Had a brainwave on how we might
a) test the runaway code.
b) allow users to add their own rules if they like.

Would appreciate a review on the approach I've taken.

**Review by pwildenhain — COMMENTED** [review]
User defined rules are so simple that I had to read it a few times to make sure I wasn't missing anything! 

I'm up for user flexibility -- do you have a specific vision for the use case for this? So far the only thing I can come up with is
1. People create rules, but don't feel like sharing them
2. People create rules, but we don't feel like adding them

I think 2 is more likely than 1, and might be reason enough to allow this. People could have their own modules with organization specific lints/fixes that aren't general enough for this package.

**Comment by alanmcruickshank** [comment]
> 2\. People create rules, but we don't feel like adding them

Yes, this one. I can imagine some organisations having rules based on naming conventions or other things more specific which aren't relevant for a general linter.

I don't knew exactly what the user experience would be to actually import a new python based rule at the moment - we might have to save that for later, but this at least allows it to be done via the module.

**Comment by aaronsteers** [comment]
I stumbled on this from #164 but it looks awesome - what's the path where new python files would need to be added in order to be used as custom or "plugin" rules?

**Comment by pwildenhain** [comment]
I think you _should_ just be able to provide your rules to the `Linter` class (see [here](https://github.com/sqlfluff/sqlfluff/pull/514/files#diff-69b882eea6311b0fc2b54a2ad894c9f8a2a4843484931a3a91aa1964951643b7R565) in the diff)

**Comment by stevenarnold** [comment]
> > 2. People create rules, but we don't feel like adding them
> 
> Yes, this one. I can imagine some organisations having rules based on naming conventions or other things more specific which aren't relevant for a general linter.

This is our use case. We have a set of standards that are different in some ways from the standard rules in sqlfluff. We'd like to make custom rules to enforce our standards when someone attempts to push a branch. We want to use our rules because although many of the standard rules in sqlfluff work for us, we have a large code base with styles that match our house rules. In other words, not all the standard rules work for us. Furthermore, the value of sharing these rules may be minimal, because they reflect our corporate standards, not necessarily a common approach that everyone will want to see/use.

**Pull request merged**
