### PR TITLE
L031 include initialisms in from clauses

### LINKED ISSUE #479: Rule for initialisms within FROM clauses.
This is prompted by the excellent work of @piotrgredowski on #473 for #469.

The fishtown sql guide says:

> Avoid table aliases in join conditions (especially initialisms) – it's harder to understand what the table called "c" is compared to "customers".

Which we have implemented a rule for which corrects:

```sql
SELECT u.id, c.first_name, c.last_name, COUNT(o.user_id)
FROM users as u
JOIN customers as c on u.id = c.user_id
JOIN orders as o on u.id = o.user_id
```
to
```sql
SELECT u.id, customers.first_name, customers.last_name, COUNT(orders.user_id)
FROM users as u
JOIN customers on u.id = customers.user_id
JOIN orders on u.id = orders.user_id
```

This is definitely in line with the _letter of the law_. What I'm wondering is whether initialisms in a FROM clause are also part of the same antipattern 🤔 . Should there be an additional rule to avoid initialisms in the `FROM` clause such that the full corrected query is:
```sql
SELECT users.id, customers.first_name, customers.last_name, COUNT(orders.user_id)
FROM users
JOIN customers on users.id = customers.user_id
JOIN orders on users.id = orders.user_id
```

I'm going to ask the fishtown guys what they think, but I'm curious for what other people think.

[I also think that @NiallRees will be amused by this suggestion because he's seen a load of my production sql and knows that this is one of my bad habits]

### PR DESCRIPTION
**Pull request by NiallRees**
Resolves #479

### CODE REVIEW

**Comment by NiallRees** [comment]
Ready to fly

**Review by pwildenhain — COMMENTED** [review]
Thanks for adding this in! I think it's a no brainer 👍 

Can you update both the rule class and `_eval` method docstrings to reflect this change? Want to make sure those stay aligned, since they make their way to the docs website.

**Comment by NiallRees** [comment]
> Thanks for adding this in! I think it's a no brainer 👍
> 
> Can you update both the rule class and `_eval` method docstrings to reflect this change? Want to make sure those stay aligned, since they make their way to the docs website.

well spotted thanks

**Review by pwildenhain — APPROVED** [review]
🙅 🕵️

**Pull request merged**
