### PR TITLE
0.6.5 release

### PR DESCRIPTION
**Pull request by tunetheweb**
We have a number of changes queued up ready for release (see CHANGELOG changes in this PR) so proposing we release 0.6.5.

If any contributors have changes nearly ready to go then happy to hold off for another day or so and add to this (CC: @miketheman , @creste , @WittierDinosaur , @zhongjiajie , @ericmuijs who I know have all been working on things recently). Let me know ASAP if you'd like me to do this.

Might also make it easier for @alanmcruickshank to release #1264 as a pre-release (I think I recall you wanted to do that before including in a full release in 0.7.0 as includes breaking changes?)

### CODE REVIEW

**Comment by zhongjiajie** [comment]
Good news for releasing 0.6.5, and have no PR submit those days.

**Comment by miketheman** [comment]
I'm pushed https://github.com/sqlfluff/sqlfluff/pull/1358 - looking for feedback, and whether this is an acceptable state for a release?

**Review by barrywhart — APPROVED** [review]

**Comment by tunetheweb** [comment]
Cool. Will have a look at #1358 in a bit and add to this if all good.

**Comment by WittierDinosaur** [comment]
@tunetheweb if I'm not too late to the party, I'd like to include #1360 into this release. It's a bugfix PR, which is quite small and simple.

**Comment by tunetheweb** [comment]
OK think this is good to go. Will merge in next hour or so unless I heard any reason not to.

**Comment by zhongjiajie** [comment]
Well done, Barry 👍

**Pull request merged**
