### PR TITLE
Add basic pre-commit config

### PR DESCRIPTION
**Pull request by jpy-git**
### Brief summary of the change made

This PR adds a basic pre-commit config to the project. This allows developers to run the linting/typing checks automatically at commit time. I know I'm not the only one who opens a PR only to realise the CI failed because I forgot to run black, so this is a nice convenience 😄

An important thing to note is that this isn't intended to provide extra checks compared to the CI, just as an easy way to automate these checks locally 👍 

I've also added a section to `CONTRIBUTING.md` to let people know how to get the pre-commit hooks setup.

N.B. for those not familiar with pre-commit, it only runs on staged files so is a quick check.

### Are there any other side effects of this change that we should be aware of?
No, it's optional (but very convenient for devs to start using).

### Pull Request checklist
- [X] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `python test/generate_parse_fixture_yml.py` or by running `tox` locally).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by jpy-git** [comment]
@barrywhart @tunetheweb think this is a sensible add to the project 😄

**Comment by jpy-git** [comment]
Also added a tox pre-commit section to simplify the install 😄

**Review by barrywhart — APPROVED** [review]
Looks great! I have often used pre-commit locally, even for SQLFluff, but it's cool to make it a standard part of the configuration. 💪🏽

I'll delay merging in case someone else wants to review.

**Review by tunetheweb — APPROVED** [review]
LGTM - though must admit I've not used pre-commit before.

Is there any reason NOT to add it to our dev dependencies? Is the main reason to keep it optional? And also avoid CI using this (though rare for that to commit)?

Maybe we merge as is, but in future consider adding to dev dependencies so it's on by default?

**Comment by jpy-git** [comment]
@tunetheweb so because it's in `tox.ini` adding it to `requirements_dev.txt` is redundant + you would still need to run the `pre-commit install` step to set up the hooks.

If you run `tox -e pre-commit -- install` it handles the package install + hook install. You can't install pre-commit hooks by default, the user needs to actively install it. I think the tox method is the cleanest.

The CI doesn't need pre-commit as they're just running the same linting checks, just via different methods.

**Pull request merged**
