### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
### Brief summary of the change made

Found via `codespell -S ./test/fixtures,./.mypy_cache,./.tox -L inout,crate,fo,nd,falsy,get\'s`

### Pull Request checklist

- [ ] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by kianmeng** [comment]
Let me know if you want to add `codespell` hook to `pre-commit` for regression testing.

**Comment by greg-finley** [comment]
I guess. 🤷‍♂️

Though this sort of PR feels kinda spammy.

**Comment by alanmcruickshank** [comment]
> Though this sort of PR feels kinda spammy.

I think it would be if someone was just picking off a couple of spelling issues, but hitting all of these in one PR is helpful 👍 . A lot of these typos are my fault.

Thanks for the contribution @kianmeng . Looks like a couple of the test cases failed, if you can fix them I'm happy to merge this.

**Comment by kianmeng** [comment]
@greg-finley I understand your sentiment. It's a typo PR, and unfortunately, right now is _**that month**_ of the year in GitHub universe. :smile:

@alanmcruickshank Noted, and I've resolved the issue.

```sh
$ tox -e doclinting
Validating...
========
Total files scanned = 17
Total files ignored = 0
Total accumulated errors = 0
Detailed error counts:
    - doc8.checks.CheckCarriageReturn = 0
    - doc8.checks.CheckIndentationNoTab = 0
    - doc8.checks.CheckMaxLineLength = 0
    - doc8.checks.CheckNewlineEndOfFile = 0
    - doc8.checks.CheckTrailingWhitespace = 0
    - doc8.checks.CheckValidity = 0
_______________________________________________ summary ________________________________________________
  doclinting: commands succeeded
  congratulations :)
```

While looking into adding `codespell` hook into `pre-commit`, I've noticed that `pre-commit` environment was not working as intended? Tested against the `main` branch as well.

Running on Python 3.8.13 managed through Pyenv.

```sh
$ tox -e pre-commit -- install
$ tox -e pre-commit
...
fix end of files.........................................................Failed                         
- hook id: end-of-file-fixer                                                                            
- exit code: 1                                                                                          
- files were modified by this hook                                                                      
                                                                                                        
Fixing test/fixtures/linter/autofix/ansi/004_indentation/after.sql                                      
Fixing test/fixtures/dialects/ansi/select_p.sql                                                         
Fixing test/fixtures/dialects/mysql/call_statement_multiple_param.sql
...
im trailing whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing test/fixtures/linter/block_comment_errors_3.sql
...

black....................................................................Passed
mypy.....................................................................Passed
flake8...................................................................Passed
doc8.....................................................................Passed
yamllint.................................................................Passed
ERROR: InvocationError for command /home/foobar/sqlfluff/.tox/pre-commit/bin/pre-commit run --all-files (exited with code 1)
_______________________________________________ summary ________________________________________________
ERROR:   pre-commit: commands failed

```

**Review by alanmcruickshank — APPROVED** [review]
Can you resolve the merge conflicts? If so I think this is ready to go 👍

**Comment by kianmeng** [comment]
> Can you resolve the merge conflicts? If so I think this is ready to go +1

@alanmcruickshank Sorry, just saw this message. Thanks for helping with resolving conflicts and merging.

:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
