### PR TITLE
Allow configuration of processes from config

### LINKED ISSUE #1058: Number of processes configurable in .sqlfluff
Being able to set the number of processes to run with in .sqlfluff might be useful to avoid having to pass it in the CLI every time.

### PR DESCRIPTION
**Pull request by alanmcruickshank**
This an oldie, but I realise it was assigned to me. This resolves #1058.

`processes` config can also be set in the config files now, and I've implemented the negative number logic as per the issue request.

### CODE REVIEW

**Comment by NiallRees** [comment]
What would you think about setting this value to 0 meaning 'use all available CPUs'?

**Comment by tunetheweb** [comment]
> What would you think about setting this value to 0 meaning 'use all available CPUs'?

I’d prefer defaulting to -1 so we don’t freeze machines.

Btw, on a related question is the minimum set to 1 so 1-core machines still actually run 😄

**Comment by alanmcruickshank** [comment]
> What would you think about setting this value to 0 meaning 'use all available CPUs'?

> Btw, on a related question is the minimum set to 1 so 1-core machines still actually run 😄

Good point - that was my intent - but I totally didn't do that on first pass. Both should be done now, also some test cases to make sure.

> I’d prefer defaulting to -1 so we don’t freeze machines.

I'm less sure about defaulting to multi-processing. I reckon for now I'm going to get this merged without changing the default behaviour for existing users. That would be an easy change to make after the fact, but I feel like it also complicates the rest of the test suite too [on top of the behaviour change for users].

**Review by NiallRees — APPROVED** [review]

**Comment by tunetheweb** [comment]
> > I’d prefer defaulting to -1 so we don’t freeze machines.
> 
> I'm less sure about defaulting to multi-processing. I reckon for now I'm going to get this merged without changing the default behaviour for existing users. That would be an easy change to make after the fact, but I feel like it also complicates the rest of the test suite too [on top of the behaviour change for users].

Ah think I misunderstood @NiallRees 's request "What would you think about setting this value to 0 meaning 'use all available CPUs'?" to mean setting this as the default. Didn't realise he was just asking to support `0` with that definition.

So all cool to leave default as is.

**Review by tunetheweb — APPROVED** [review]

**Pull request merged**
