### PR TITLE
Combine L059 and L010

### PR DESCRIPTION
**Pull request by tdstark**
### Brief summary of the change made
Per the discussion in this [PR](https://github.com/sqlfluff/sqlfluff/pull/2227), this PR will consolidate L059 into L010 by adding `data_type_identifier` into L010. A simple change was also required in our ANSI tests as well because INT capitalization was not being changed appropriately.

### Are there any other side effects of this change that we should be aware of?
None

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by tdstark** [comment]
@jpy-git here is the PR that will fix the keyword issue. Let me know if you have any thoughts.

**Review by jpy-git — COMMENTED** [review]
@tdstark looks great, thanks for updating this 😄 

One small tweak is that we added a default config option to `src/sqlfluff/core/default_config.cfg` for L059 in #2227 that I can't see being removed here. Would you be able to remove that too please and then I can approve 👍

**Comment by tdstark** [comment]
> @tdstark looks great, thanks for updating this 😄
> 
> One small tweak is that we added a default config option to `src/sqlfluff/core/default_config.cfg` for L059 in #2227 that I can't see being removed here. Would you be able to remove that too please and then I can approve 👍

Good catch! Removed!

**Review by jpy-git — APPROVED** [review]
@tdstark nice work, LGTM 🚀 ✨

**Pull request merged**
