### PR TITLE
BigQuery: Parse `CREATE TABLE` with trailing comma

### LINKED ISSUE #3011: BigQuery: Trailing comma in columns of `CREATE TABLE` statement is unparsable
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

A BigQuery `CREATE TABLE` statement that has a trailing comma after the last column yields unparsable error. However, it perfectly valid BigQuery SQL.

### Expected Behaviour

SQLFluff can parse this BigQuery specific.

### Observed Behaviour

```
Line 1, Position 1: Found unparsable section: 'CREATE TABLE (
    col1 STRING,
)'
```

### How to reproduce

```sql
CREATE TABLE (
    col1 STRING,
)
```

https://online.sqlfluff.com/fluffed?sql=H4sIAMxkTGIC_3MOcnUMcVUIcXTycVXQ4OVSAILk_BxDheCQIE8_dx1eLk0A3ISaliMAAAA%3D&dialect=bigquery

### Dialect

BigQuery

### Version

0.11.2 -> webversion

### Configuration

default

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by dmohns**
### Brief summary of the change made

Fixes #3011

### Are there any other side effects of this change that we should be aware of?

No.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by tunetheweb — APPROVED** [review]
This looks good to me. Ready to be taken out of draft?

**Comment by dmohns** [comment]
I was tinkering around with L038, but maybe it better to do that in a separate PR anyways.

**Comment by tunetheweb** [comment]
Ah yes forgot about that. Let’s see if we can add to this PR. If not and looks like it’ll miss the release then I’ll merge it but have a day or so.

**Comment by dmohns** [comment]
> Ah yes forgot about that. Let’s see if we can add to this PR. If not and looks like it’ll miss the release then I’ll merge it but have a day or so.

From what I've seen so far, it looks like changing L038 would either changing the abstraction logic a bit (i.e. adding something like `ColumnListSegment`) or quite a bit of conditional logic in L038.

Either way this will probably involve some discussion about proper implementation. Let's do it in two PRs. So we can get the fix in the release for sure.

**Comment by tunetheweb** [comment]
> From what I've seen so far, it looks like changing L038 would either changing the abstraction logic a bit (i.e. adding something like `ColumnListSegment`) or quite a bit of conditional logic in L038.

Yeah had a quick look and tend to agree. OK let's merge this.

**Pull request merged**
