### PR TITLE
Improve handling of BigQuery hyphenated table names

### LINKED ISSUE #3609: L057: Automatically allow hyphenated BigQuery project names
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Hi there,

I'm very new to sqlfluff and just tried to create some initial sample transformations to show to my team.
However, I keep running into issues because our project names contain hyphens (-) and this causes parsing errors. Putting all the project names in `` quotes is not really on option for us.

Example:
```
CREATE OR REPLACE TABLE project-name.dataset_name.table_name
(
    ...
)
PARTITION BY DATE(import_ts);
```

Error:
```
==== parsing violations ====
L:   1 | P:  32 |  PRS | Line 1, Position 32: Found unparsable section:
                       | '-name.dataset_name.table_name\n(\n tena...'
WARNING: Parsing errors found and dialect is set to 'bigquery'. Have you configured your dialect correctly?
```

I'm using version 1.2.0.

If there is no plan to allow these project names, is there any way I can make the parser "skip" specific terms? Then I could just provide a list of our project names in our pyproject.toml.

Best, Anne

### Use case

I would like to fix files that query tables from bigquery projects with names containing "-".

### Dialect

bigquery

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by barrywhart**
### Brief summary of the change made
Makes progress on #3609 

@greg-finley: This is based on the PR you started and closed (#3614). It was a good plan, but it required some improvements to the `iter_raw_references()` function in the BigQuery dialect. 🤞 that this is working now.

### Are there any other side effects of this change that we should be aware of?
The `iter_raw_references()` function is a vital part of the `get_select_statement_info()` function, used by almost every rule that cares about aliases (e.g. L026). I was pretty careful in writing and testing the new implementation, but the code is inherently tricky, now that it needs to handle both simple (non-hyphenated) as well as hyphenated references.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by tunetheweb** [comment]
Gimme a few mins to check if this change causes new alerts for L057 it didn’t below on one of my code based. If it doesn’t then I agree. If it does then think we should do both together as otherwise it’s a bit of a regression due to this change.

**Comment by barrywhart** [comment]
I wouldn't expect previously linted SQL to see new issues, but I've been wrong before. 😉 (Note that we already support non-quoted table references in `SELECT` statements prior to this PR, but not in other places, e.g. `CREATE TABLE`.)

Testing with your BigQuery code would be 💯 , as my only testing is with our automated/CI tests. 🥳

**Comment by tunetheweb** [comment]
Ah I thought it was the other way around! Yes you're right and test proved it.

I also note that I include hypen in my L057 config anyway:

```
[sqlfluff:rules:L057]
## Special characters in identifiers
unquoted_identifiers_policy = all
quoted_identifiers_policy = all
allow_space_in_identifier = False
additional_allowed_characters = "-"
```

Probably should still be the default for BigQuery, but agree we can merge this as is.

**Comment by barrywhart** [comment]
@tunetheweb: Cool! Would you mind approving it? Feel free to go ahead and merge as well, or I can merge it later today.

**Review by tunetheweb — APPROVED** [review]

**Pull request merged**
