### PR TITLE
Enhance error message L010 base on configure

### PR DESCRIPTION
**Pull request by zhongjiajie**
### Brief summary of the change made

closes https://github.com/sqlfluff/sqlfluff/issues/1128 and base on pr https://github.com/sqlfluff/sqlfluff/pull/1173.
Cause @scrambldchannel  seem not work on https://github.com/sqlfluff/sqlfluff/pull/1173 anymore, so I start PR base on it
and set @scrambldchannel as the co-author

Currently Rule L010 error message too generic, we should show configure what we set in the error message

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/parser` (note YML files can be auto generated with `python test/generate_parse_fixture_yml.py` or by running `tox` locally).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.

### CODE REVIEW

**Comment by zhongjiajie** [comment]
Ok, first shot for this pr, base on @scrambldchannel work

**Comment by scrambldchannel** [comment]
Hi @zhongjiajie - sorry, I missed your previous mention. You're right, I got sidetracked so would be really pleased if you picked this up :smile: :+1:

**Review by tunetheweb — APPROVED** [review]

**Comment by tunetheweb** [comment]
Thanks!

**Comment by zhongjiajie** [comment]
Thanks for merging

**Pull request merged**
