### PR TITLE
Issue 878: Adding Snowflake schema object double-dot notation

### PR DESCRIPTION
**Pull request by DavidJohnQuinlan**
Resolves [issue 878](https://github.com/sqlfluff/sqlfluff/issues/878) by adding the option of a sequence of two dots to the `delimiter` argument in the `Delimited` function called in the `ObjectReferenceSegment` class. Also created an additional SQL test query containing the double-dot notation.

### CODE REVIEW

**Review by alanmcruickshank — APPROVED** [review]
I thought someone had already done this, but evidently not!

I wonder if this also works without the `Sequence(Ref("DotSegment"))`, in which case this could be simplified.

Happy to handle that elsewhere however.

**Comment by DavidJohnQuinlan** [comment]
Thanks Alan, I shall investigate further

**Comment by DavidJohnQuinlan** [comment]
Hey Alan, you were right it works without `Sequence(Ref("DotSegment"))`. This change has been added to the PR.

**Comment by dmateusp** [comment]
Somehow the CI never triggered here, I don't think I have the rights to create a new run on CircleCI, maybe an empty commit would fix it @DavidJohnQuinlan ?

**Comment by DavidJohnQuinlan** [comment]
Hey @dmateusp, the empty commit does not appear to have changed things. Is there something that I am missing on my side? These tests should trigger on push right?

**Comment by alanmcruickshank** [comment]
No idea why CI doesn't seem to be triggered here, but I can always _admin-merge_ it. 🔨 

Thanks for putting this together!

**Pull request merged**
