### PR TITLE
Add QUALIFY clause to BigQuery

### LINKED ISSUE #1242: Add Qualify statement to Bigquery
-- If this is a parsing or linting issue, please include a minimal SQL example which reproduces the issue, along with the `sqlfluff parse` output, `sqlfluff lint` output and `sqlfluff fix` output when relevant. Finally, please add any labels that are related to the issue before submitting so that it can be addressed easily! --

## Expected Behaviour
Qualify should be parsed for BigQuery dialect

## Observed Behaviour
```
found unparsable section: '\n qualify row_num = 1'
```

## Version
Include the output of `sqlfluff --version` along with your Python version
```
sqlfluff, version 0.6.2
```
## Configuration
```
Include your SQLFluff configuration here
```

### PR DESCRIPTION
**Pull request by tunetheweb**
Fixes #1242 

Mostly based on #1193

### CODE REVIEW

**Review by barrywhart — APPROVED** [review]
Looks good! Can you resolve the `CHANGELOG.md` conflict? Then we can merge.

**Comment by tunetheweb** [comment]
> Looks good! Can you resolve the `CHANGELOG.md` conflict? Then we can merge.

Done. I wonder if there is a better way here? But can’t think of one - except maintainers resolving these simple CHANGES.md ones and merging of that’s the one issue (by default GitHub opens PRs with “allow maintainers to edit this branch” mode).

**Comment by barrywhart** [comment]
I've wondered about that, too. Also wondered if maintainers can make changes even if the PR is based on someone's personal clone of the repo.

I'm curious what other projects do. One other _possible_ idea would be to generate the change log automatically, either from the PRs or closed issues, something like that. We're definitely figuring this out as we go. 😝

**Comment by tunetheweb** [comment]
> I've wondered about that, too. Also wondered if maintainers can make changes even if the PR is based on someone's personal clone of the repo.

Yes they can as have done that on other projects. Only on that branch the PR is for and only if they've not unticked the "allow edits" box.

> I'm curious what other projects do. One other _possible_ idea would be to generate the change log automatically, either from the PRs or closed issues, something like that. We're definitely figuring this out as we go. 😝

I've used the [release-drafter GitHub Action](https://github.com/marketplace/actions/release-drafter) on other projects. It basically creates a draft Release in GitHub and updates it every time a PR is merged. This draft PR is only visible to maintainers.

Here's the one for my example:

image

You coudl then copy that into the CHANGES.md file at release time? That would avoid the continual merge conflicts. The downside though is non-maintainers can't see what's upcoming, which is useful feature of the current process.

Or we auto add to CHANGES.md on merge? That might be a better way...

Probably should open a separate issue to discuss.

**Comment by barrywhart** [comment]
@tunetheweb: That sounds cool! Definitely worth creating another issue to discuss. I'd like to understand a bit more about how it works, but yes, the CHANGELOG has been useful but also the inherent merge conflicts add "drag" to every PR now.

**Pull request merged**
