### PR TITLE
Exasol multiple local expressions

### LINKED ISSUE #2577: Exasol: `LOCAL` may not working in `WHERE` clause
## Expected Behaviour
Statement must be parsable

## Observed Behaviour
Statement is not parsable when using `LOCAL` keyword in `WHERE` clause when used in `SELECT` context.

## Steps to Reproduce
```sql
SELECT * FROM T
WHERE       (LOCAL.c1, LOCAL.c2)
NOT IN  (SELECT c1,c2 FROM  b)
;
```

## Dialect
Exasol

## Version

0.9.2

### PR DESCRIPTION
**Pull request by tunetheweb**
### Brief summary of the change made

Fixes #2577 

### Are there any other side effects of this change that we should be aware of?
It does change `Expression_D_Grammar` but should only affect Spark3 as the added expression is set to `Nothing()` for other dialects.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by tunetheweb** [comment]
FYI @sti0 - is this the same fix you were going to suggest?

**Review by sti0 — CHANGES_REQUESTED** [review]
Yes, its the same fix.
But could you please add these two test cases to the [Exasol dialect test fixtures](https://github.com/sqlfluff/sqlfluff/blob/main/test/fixtures/dialects/exasol/SelectStatement.sql).

```sql
SELECT * FROM T WHERE (LOCAL.c1, LOCAL.c2) NOT IN  (SELECT c1,c2 FROM  b);
----
SELECT 'ABC' as c1 FROM dual WHERE local.c1 = 'ABC';
```

Thanks.

**Comment by sti0** [comment]
@tunetheweb I wonder if you really mean the Spark dialect? I mentioned Exasol.

**Comment by tunetheweb** [comment]
You’re correct I meant Exasol 😔

Got this confused with another fix I was looking at. Will move the test case and add the other one.

**Comment by tunetheweb** [comment]
Or if you have a branch with that ready to go, then happy to close this and go with yours?

**Comment by sti0** [comment]
I just must push my commit and we are good to go

**Comment by sti0** [comment]
We could go with #2582

**Comment by tunetheweb** [comment]
Let’s do it.

**Pull request closed without merging**
