### PR TITLE
T-SQL: Allow specifying join hints

### LINKED ISSUE #3916: T-SQL: HASH JOIN not supported
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

`sqlfluff` does not recognize (i.e. cannot parse) the T-SQL statement `INNER HASH JOIN`.

### Expected Behaviour

[Join hints](https://learn.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-join?view=sql-server-ver16) should be recognized by `sqlfluff`.

### Observed Behaviour

```
== [test.sql] FAIL                                                                                                                      
L:   3 | P:   1 |  PRS | Line 3, Position 1: Found unparsable section: 'INNER                                                           
                       | HASH JOIN b\n ON a.col = b.col\n'
WARNING: Parsing errors found and dialect is set to 'tsql'. Have you configured your dialect correctly?
All Finished 📜 🎉!
```

### How to reproduce

```sql
SELECT a.*
FROM a
INNER HASH JOIN b
    ON a.col = b.col
```

### Dialect

`tsql`

### Version

- sqlfluff, version 1.3.1
- Installed via homebrew

### Configuration

```
[sqlfluff]
dialect = tsql
exclude_rules = L011,L012,L013,L031,L034,L044
large_file_skip_byte_limit = 0

[sqlfluff:indentation]
indented_ctes = true
indented_joins = false

[sqlfluff:rules]
comma_style = trailing
group_by_and_order_by_style = explicit
max_line_length = 99
tab_space_size = 4

[sqlfluff:rules:L010]
capitalisation_policy = upper
```

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by borchero**
### Brief summary of the change made

This PR fixes #3916.

### Are there any other side effects of this change that we should be aware of?

n/a

### Pull Request checklist

- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by alanmcruickshank — APPROVED** [review]
Nice 👍

**Comment by alanmcruickshank** [comment]
Ummmm.... I don't know why the tests are failing here. I'm going to re run them in a bit to see if it's a github issue.

**Comment by borchero** [comment]
Thanks for your review @alanmcruickshank! The failing tests seem like a transient GH Actions error, I'll merge as soon as they passed.

**Comment by borchero** [comment]
Ah I can't, I guess someone else has to rerun them 😅

**Pull request merged**
