### PR TITLE
Rule globs

### LINKED ISSUE #1445: fix CLI - exclude rules by pattern
_Note: This is for general enhancements to the project. Please use the Bug report template instead to raise parsing/linting/syntax issues for existing supported dialects_

Hi there,
I setup a custom rules plugin and it works as expected with `lint`. But if I try to run `fix` (both with pre-commit), sqlfluff stuck in a loop (maybe tries to fix the custom rule). 

It would be nice if we could exclude rules by pattern or maybe by plugin or exclude all custom rules.

E.g.

```
sqlfluff fix --exclude-rules=MYPKG_*
# or
sqlfluff fix --exclude-rules-package=MYPKG
# or
sqlfluff fix --exclude-custom-rules
```

BR
Timo

### PR DESCRIPTION
**Pull request by jpy-git**
### Brief summary of the change made

Fixes #1445. This PR provides the mechanism for rules to be included/excluded by globs in either the config files or via the CLI.
image

As well as resolving the linked issue, the big benefit of this will be to allow users to more easily bulk disable groups of rules 
via the rule prefix, as I discussed in #1812. This is essentially what is happening in the #1445 as well just for plugins. Personally think this is a very elegant solution. Also this use case is what motivates the use of globs rather than regex as the expected use is simply `--rules "Core_*"` or `--exclude-rules "Some_Plugin_*"` (or whatever prefixes we decide on), so keeps things nice and simple.

### Are there any other side effects of this change that we should be aware of?
No

### Pull Request checklist
- [X] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `python test/generate_parse_fixture_yml.py` or by running `tox` locally).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by tunetheweb — COMMENTED** [review]
I've a few questions:
1. Does this allow `exclude_rules = L001, L05*` and if so should we add a test?
2. Should we update our documentation for this?
3. Should we take this as an opportunity to move to the more inclusive "allowlist/denylist" syntax? At least for the code touched here?

**Comment by jpy-git** [comment]
1. Yes it does, will add that unit test in!
2. Sounds like a plan. I think it makes sense to address this as part of what we discussed in #1938. So let's make it a separate PR and address both at the same time.
3. Agree that would be a nice change 😄 Let me assess how much much the terms are used and then can replace them all at once (may be worth separate PR if there are loads)

An additional question I'm wondering myself is if this glob stuff also applies to inline comments. I think it does but let's resolve #1985 first and then I'll investigate 👍

**Review by barrywhart — APPROVED** [review]

**Comment by barrywhart** [comment]
Looks like a dbt test failed in one of the builds?

**Comment by jpy-git** [comment]
@barrywhart it didn't fail, the GHA runner lost internet connection so the install download failed. Should work fine once re-run 👍

**Comment by jpy-git** [comment]
@tunetheweb Follow up on your questions
- 1. I've added the extra unit test
- 2. will be separate pr
- 3. I've had a look and will make a separate PR for this otherwise the diffs will look a mess 👍 
- 4. These globs don't apply to inline comments at the moment because the inline comment code has no interaction with the rule set and just checks if one of the supplied rules matches an error raised. Will make a follow up PR to extend this 👍 

LGTM 🚀

**Review by tunetheweb — APPROVED** [review]

**Pull request merged**
