### PR TITLE
New rule L072: Prefer using DATABASE instead of using SCHEMA

### LINKED ISSUE #4312: New Rule: Prefer CREATE/ALTER/DROP DATABASE than CREATE/ALTER/DROP SCHEMA
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

In MySQL, Hive and SparkSQL, `CREATE/ALTER/DROP SCHEMA` are equivalent to `CREATE/ALTER/DROP DATABASE`.
I'd like to add a rule to prefer using `CREATE/ALTER/DROP DATABASE` on these dialects.

https://dev.mysql.com/doc/refman/8.0/en/create-database.html
https://cwiki.apache.org/confluence/display/hive/languagemanual+ddl#LanguageManualDDL-Create/Drop/Alter/UseDatabase
https://spark.apache.org/docs/latest/sql-ref-syntax-ddl-create-database.html

### Use case

_No response_

### Dialect

mysql, hive, sparksql

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by yoichi**
### Brief summary of the change made

fixes #4312 

### Are there any other side effects of this change that we should be aware of?
No

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by greg-finley** [comment]
Hmmm, do enough people have this same preference that it justifies a rule? Are there guides online suggesting that `DATABASE` is better?

**Comment by pdebelak** [comment]
I can see value in consistency, but I haven't heard a suggestion about which one is better (I feel like for mysql, at least, I'd prefer schema since they act more like schemas than separate databases). I think it would make more sense to have it like [rule L067](https://docs.sqlfluff.com/en/stable/rules.html#sqlfluff.rules.Rule_L067) where the rule is about consistency and you specify which one you want.

**Comment by yoichi** [comment]
> Hmmm, do enough people have this same preference that it justifies a rule? Are there guides online suggesting that `DATABASE` is better?

Thank you for your feedback. I haven't seen any documentation that mentions this rule.
There is a behavior of MySQL that SHOW CREATE SCHEMA returns CREATE DATABASE instead of CREATE SCHEMA.

```
mysql> show create database world;
+----------+-------------------------------------------------------------------+
| Database | Create Database                                                   |
+----------+-------------------------------------------------------------------+
| world    | CREATE DATABASE `world` /*!40100 DEFAULT CHARACTER SET utf8mb4 */ |
+----------+-------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> show create schema world;
+----------+-------------------------------------------------------------------+
| Database | Create Database                                                   |
+----------+-------------------------------------------------------------------+
| world    | CREATE DATABASE `world` /*!40100 DEFAULT CHARACTER SET utf8mb4 */ |
+----------+-------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by yoichi** [comment]
> I can see value in consistency, but I haven't heard a suggestion about which one is better (I feel like for mysql, at least, I'd prefer schema since they act more like schemas than separate databases). I think it would make more sense to have it like [rule L067](https://docs.sqlfluff.com/en/stable/rules.html#sqlfluff.rules.Rule_L067) where the rule is about consistency and you specify which one you want.

Thank you for your suggestion to add a configuration item. I think it's a good idea to make the rule that we should avoid mixing like L067, rather than recommending a particular one.

**Comment by tunetheweb** [comment]
See this comment: https://github.com/sqlfluff/sqlfluff/issues/4312#issuecomment-1436070608

**Pull request closed without merging**
