### PR TITLE
Remove unused deps in tox test docbuild

### PR DESCRIPTION
**Pull request by zhongjiajie**
### Brief summary of the change made

ATT, remove unused deps in tox job

### CODE REVIEW

**Comment by zhongjiajie** [comment]
As the result show on [CI result][1], we don't need reinstall dependent `requirements.txt` and `requirements_dev.txt` in job `docbuild` could in already install in `[testenv]`

So I think we could remove code in https://github.com/sqlfluff/sqlfluff/pull/1406/files#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449L89-L90

[1]: https://github.com/sqlfluff/sqlfluff/pull/1406/checks?check_run_id=3605563486

**Comment by zhongjiajie** [comment]
Ref PR https://github.com/sqlfluff/sqlfluff/pull/1393

**Comment by tunetheweb** [comment]
The results show that requirements.txt and requirements_dev.txt are not run. Thats why I added them. It would have been nice if it was possible for the job to inherit the original dependencies and add to it.

However, I do agree it looks like they are not actually needed though (which surprises me as the docs requirements.txt is so light!). I wonder if that's intentionally independent or by luck and the assumption will be that developers will have the parents requirements.txt and requirements_dev.txt installed?

Then again we have the check so if this ever changes, we can easily either fix the dependencies or add these lines back in. So will merge.

**Review by tunetheweb — APPROVED** [review]

**Comment by zhongjiajie** [comment]
> The results show that requirements.txt and requirements_dev.txt are not run. 

I found out after you said, my initial think job `docbuild` had parent dependent 
https://github.com/sqlfluff/sqlfluff/blob/845c8eb3bb8d5c31a90c0d9c626c59834b92040e/tox.ini#L9-L21
So it only need to add `docs/requirements.txt` for addition
https://github.com/sqlfluff/sqlfluff/blob/845c8eb3bb8d5c31a90c0d9c626c59834b92040e/tox.ini#L87-L89

but after you said and I checkout the CI logs, and doc build just install dependent `docs/requirements.txt` and work fine
https://github.com/sqlfluff/sqlfluff/pull/1406/checks?check_run_id=3605563486#step:5:8
I make me surprised too.

**Pull request merged**
