### PR TITLE
gitignore add .DS_Store

### PR DESCRIPTION
**Pull request by zhongjiajie**
Add `.DS_Store` to git ignore which will auto generate in macOS

### CODE REVIEW

**Comment by zhongjiajie** [comment]
PTAL @alanmcruickshank @pwildenhain  thx

**Review by pwildenhain — APPROVED** [review]
Thanks for the reminder 🎗️

**Comment by NiallRees** [comment]
@zhongjiajie you're best off creating a global gitignore as this file isn't unique to the SQLFluff project. https://sebastiandedeyne.com/setting-up-a-global-gitignore-file/

**Comment by zhongjiajie** [comment]
@NiallRees  So, should I close this PR and add file to global config?

**Comment by NiallRees** [comment]
> @NiallRees So, should I close this PR and add file to global config?

I'll merge it now but just to save you the trouble in future 🙂

**Pull request closed without merging**
