### PR TITLE
Avoid using aliases in join coditions

### PR DESCRIPTION
**Pull request by piotrgredowski**
This is just a WIP PR for https://github.com/sqlfluff/sqlfluff/issues/469
Just wanted to ask if it is good approach to solve presented problem :)
There is a lot to improve - especially docstrings, SQL file name etc. But yeah. It's just a start :)

### CODE REVIEW

**Comment by alanmcruickshank** [comment]
Hi @piotrgredowski , thanks for getting involved.

A few tips on your approach:
- I think given you're overriding `_lint_references_and_aliases` and `_eval`, I don't think you need to inherit from Rule_L025 and you can just inherit from `BaseCrawler` and have a nice clean rule to work with.
- Rather than `list(seg.recursive_crawl('identifier'))`, I wonder if you can leverage the `AliasExpressionSegment` and look for an element of type `alias_expression` explicitly to avoid just assuming the identifiers will come in the right order. Although I'm not sure I can think of a scenario where they wouldn't at the moment.
- Consider how you might implement a `fix` solution for this rule too. You can probably get some inspiration from the other rules which already exist but feel free to ask for tips here if you need!

**Comment by piotrgredowski** [comment]
This is very dirty version, returning many LintResults - it (and many other things) will be refactored and fixed later. :)
I've implemented a fix too. But I couldn't find any test case for LintFixes. Am I blind? Can you show me some example? :)

**Comment by piotrgredowski** [comment]
I've added support for [self-joins](https://github.com/sqlfluff/sqlfluff/issues/469#issuecomment-705228821) too.

**Comment by NiallRees** [comment]
Hey @piotrgredowski this is really cool, nice job with the fix implementation too. I'm going to approve but defer to @alanmcruickshank to merge as he had a few questions above (which I'm 99% sure you've addressed).

**Review by NiallRees — APPROVED** [review]
Thank you!

**Review by alanmcruickshank — APPROVED** [review]
Thanks for this @piotrgredowski ! Very neat PR, good work on the fix, excellent test coverage. 👍 

I've got a broader question about whether we should also have a rule against initialisms in aliases for tables in a `FROM` clause. I think that's a vagueness in the fishtown style guide rather than a problem with the work you've done though. I'll raise a separate issue for it.

**Pull request merged**
