### PR TITLE
Warning for parsing errors extended to all dialects

### LINKED ISSUE #3402: Update warning for parsing errors found on the ansi dialect
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

In the past specifying a dialect was **optional**. If unspecified, the dialect defaulted to `ansi`. Because of this there is a warning presented when sqlfluff runs in parse mode and the dialect is set to ansi and parsing errors are encountered.

`WARNING: Parsing errors found and dialect is set to 'ansi'. Have you configured your dialect?`

Currently, specifying a dialect is **mandatory**. Therefore this warning is perhaps not needed... and certainly not needed in its current form.

I opened this issue to document the idea and solicit feedback. 
1. The simplest improvement to make the message more appropriate is to just change it to this:

`WARNING: Parsing errors found and dialect is set to 'ansi'. Is 'ansi' the correct dialect?`

2. On the other hand, we know that the user explicitly set the dialect to `ansi`. So why bother asking if it was intentional? We don't ask if you meant postgres or tsql. There's an argument to simply remove the warning altogether.

3. Finally, we could potentially differentiate between `--dialect ansi` passed on the command line vs the dialect being picked up from a `.sqlfluff` config file. Perhaps the warning should be displayed only the in the case where the dialect was picked up implicitly from the config file.

### Use case

_No response_

### Dialect

ansi

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by mdahlman**
### Brief summary of the change made

fixes #3402

### Are there any other side effects of this change that we should be aware of?
Note: This is my first PR for commands.py or formatters.py.
Per discussion in the issue, I removed the check on the dialect being `ansi` so that it displays for any dialect. I updated the dialect_warning methods to accept a dialect.

It was easier than expected.
This doesn't make me think, "Wow, that was easy."
Rather, it makes me think, "Uh oh... is a guy in a hockey mask about to jump out and get me?"

I did not see how to add a coverage test. This is quite different from an update to a dialect.
Additions and corrections will be welcome.

### Pull Request checklist
- [ ] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by tunetheweb — CHANGES_REQUESTED** [review]
The change itself looks good but think it would be good to add a test case if possible.

Could you look at test/cli to see if it’s easy enough to add one?

**Comment by mdahlman** [comment]
Yes! In fact, I was going to mention this explicitly. 
I didn't see where to create a test. Looking now, I suppose it would be in `commands_test.py`.
But I didn't see this discussed in the Wiki, so I as hesitant to create a new test.
Do you think `test__cli__command_dialect` would be a reasonably close test to use as a model?

I will investigate, but any guidance will be welcome.

**Comment by mdahlman** [comment]
Here's a test case. Feedback requested.

**Review by barrywhart — APPROVED** [review]
Looks good to me!

I will hold off merging to give @tunetheweb time to re-review it if he wants.

**Comment by mdahlman** [comment]
I'll see your additional test and raise you a variation.
From the initial enhancement request I had been thinking of differentiating between explicitly specifying the dialect and implicitly specifying it. I did not give different warnings for the two situations, but now I included separate tests for the two situations. I like this better.

For the `# pragma: no cover`s, I removed only one, because it seems that that's the only one being tested. Did you have more than just the 1 in mind?

**Review by tunetheweb — APPROVED** [review]

**Pull request merged**
