### PR TITLE
Follow noqa in block comments

### LINKED ISSUE #4891: -- noqa ignored in multiline comment
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I have a very long URL inside a multiline comment.
I don't want to trigger a rule failure, so I tried putting `-- noqa: LT05` at the end of the line.
But because we are already inside a multiline comment, the `noqa` declaration was ignored.

### Expected Behaviour

There should be a way to specify `noqa` for comment lines. (See also #4881 which would be a better solution in this particular case.)

### Observed Behaviour

`sqlfluff lint` outputs the following failure even when `-- noqa: LT05` is appended to the long comment line:

    L:   2 | P:   1 | LT05 | Line is too long (106 > 88).

### How to reproduce

Run `sqlfluff lint` on the following SQL file:

``` sql
/*
* https://example.com/1111111111111111111111111111111111111111111111111111111111111111111111 -- noqa: LT05
*/
```

### Dialect

tsql

### Version

sqlfluff, version 2.1.0
Python 3.10.10

### Configuration

``` cfg
[sqlfluff]
dialect = tsql
max_line_length = 88

# ST06 reorders columns, which seems presumptuous
exclude_rules = ST06

[sqlfluff:indentation]
allow_implicit_indents = True

[sqlfluff:rules:references.special_chars]
allow_space_in_identifier = True
additional_allowed_characters = ['-/()?,']
```

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by daviewales**
### Brief summary of the change made

Fixes #4891.

### Are there any other side effects of this change that we should be aware of?

None intended...

### Pull Request checklist
- [ ] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by daviewales** [comment]
I've made a test file:

``` sql
/* This file tests ignoring rules based on noqa directives found
in block comments.*/

/*
A line which is much much much too long, because the enter key on my keyboard is broken, but I don't want a lint error. -- noqa: LT05
A line which is much much much too long, because the enter key on my keyboard is broken, and I do want a lint error!
*/

/* A single-line block comment which is too long, and also ignored because I like long lines -- noqa: LT05 */
/* Another single-line block comment which is also ignored. I'm too lazy to specify which rule to ignore though. -- noqa */
/* A single-line block comment which is too long, and we want a warning so we can fix it! */

/*
A single line block comment which takes up three lines, because pixels are cheap, and so are bytes. -- noqa
*/

/*
A single line block comment which takes up three lines, but we want a warning this time please!
*/

SELECT
    a.a + a.b AS good,

    -- A noqa by itself in a block comment is followed
    /* noqa: disable=all */
    a.a-a.b AS bad_1,
    /* noqa: enable=all */

    -- A noqa in a block comment preceded by a single line comment
    -- marker (--) is followed
    /* -- noqa: disable=all */
    a.a*a.b AS bad_2,
    /* -- noqa: enable=all */

    -- If the noqa is accompanied by preceding text in a block
    -- comment it must be preceded by a single-line comment marker, and
    -- it must be the last part of the line.
    /* Ignore warnings for a bit! -- noqa: disable=all */
    a.a*a.b AS bad_3,
    /* noqa: enable=all */

    -- A noqa will NOT be followed if it follows preceding text, and is
    -- not immediately preceded by a single-line comment marker (--).
    -- (We should get a warning here!)
    /* This won't work: noqa: disable=all */
    a.a*a.b AS bad_4,
    /* noqa: enable=all */

    -- A noqa will NOT be followed if it is not the last part of the line.
    -- (We should get a warning here!)
    /* -- noqa: disable=all This is not a valid noqa declaration */
    a.a*a.b AS bad_5
    /* noqa: enable=all */

FROM tbl AS a
```

This produces the expected output:

```
== [test/fixtures/linter/operator_errors_ignore_in_multiline_comment.sql] FAIL
L:   6 | P:   1 | LT05 | Line is too long (116 > 80).
                       | [layout.long_lines]
L:  11 | P:   1 | LT05 | Line is too long (92 > 80).
                       | [layout.long_lines]
L:  18 | P:   1 | LT05 | Line is too long (95 > 80).
                       | [layout.long_lines]
L:  46 | P:   8 | LT01 | Expected single whitespace between naked identifier and
                       | binary operator '*'. [layout.spacing]
L:  46 | P:   9 | LT01 | Expected single whitespace between binary operator '*'
                       | and naked identifier. [layout.spacing]
L:  52 | P:   8 | LT01 | Expected single whitespace between naked identifier and
                       | binary operator '*'. [layout.spacing]
L:  52 | P:   9 | LT01 | Expected single whitespace between binary operator '*'
                       | and naked identifier. [layout.spacing]
All Finished 📜 🎉!
```

What's the best way to turn this into a test?

**Comment by alanmcruickshank** [comment]
> What's the best way to turn this into a test?

Best way to make a it into a "yaml test" (or make it into multiple smaller ones). Take a look at `/test/fixtures/rules/std_rule_cases/LT05.yml` and you'll get the idea. In particular you'll see that for each test case in there that you can configure the `max_line_length` so you may be able to make the test cases more compact, while still testing the same functionality. There are also examples of `violations_after_fix` (and there's also just `violations`, which is asserted before any fixes) in that file which might help you add some extra specificity to the tests.

**Comment by daviewales** [comment]
Thanks @alanmcruickshank. I'm wondering if the failures on 3.8 are due to [removeprefix](https://docs.python.org/3/library/stdtypes.html#str.removeprefix) and [removesuffix](https://docs.python.org/3/library/stdtypes.html#str.removesuffix) being introduced in 3.9. Do we need to include function definitions instead of these methods to maintain compatibility with Python 3.7 and 3.8? Presumably we can use similar logic to [PEP 616](https://peps.python.org/pep-0616/).
I [tried to find the CPython source](https://github.com/search?q=repo%3Apython%2Fcpython+%22def+removesuffix%22&type=code), but I'm not convinced that I found it.

Also, I had an issue when trying to create yaml tests for this.

I created a file: `test/fixtures/rules/std_rule_cases/noqa.yml`:

``` yml
rule: noqa

test_block_comment_single_line_noqa:
  # Ignore long line in block comment
  pass_str: "/* A very long single-line block comment which is ignored --noqa: LT05 */\n"
  configs:
    core:
      max_line_length: 30

test_fail_block_comment_single_line_noqa:
  # Don't ignore long line in block comment
  fail_str: "/* A very long single-line block comment which is not ignored */\n"
  configs:
    core:
      max_line_length: 30
```

The following command runs these tests:

```
tox -e py310 -- test/rules/yaml_test_cases_test.py -k noqa
```

However, the test with the `fail_str` case appears to make the test itself fail:

```
collected 1448 items / 1444 deselected / 4 selected

test/rules/yaml_test_cases_test.py::test__rule_test_case[LT02_test_pass_trailing_inline_noqa] PASSED [ 25%]
test/rules/yaml_test_cases_test.py::test__rule_test_case[LT05_test_fail_do_not_fix_noqa] PASSED [ 50%]
test/rules/yaml_test_cases_test.py::test__rule_test_case[noqa_test_block_comment_single_line_noqa] PASSED [ 75%]
test/rules/yaml_test_cases_test.py::test__rule_test_case[noqa_test_fail_block_comment_single_line_noqa] FAILED [100%]

================================ FAILURES ================================
__ test__rule_test_case[noqa_test_fail_block_comment_single_line_noqa] ___
No noqa failures found in query which should fail.
-------------------------- Captured stdout call --------------------------
# Asserting Rule Fail in SQL
Errors Found:
Parsed File:
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    block_comment:                                            '/* A very long single-line block comment which is not ignored */'
[L:  1, P: 65]      |    newline:                                                  '\n'
[L:  2, P:  1]      |    [META] end_of_file:

--------------------------- Captured log call ----------------------------
INFO     sqlfluff.linter:linter.py:688 TEMPLATING RAW [jinja] (<string input>)
INFO     sqlfluff.linter:linter.py:160 LEXING RAW (<string input>)
INFO     sqlfluff.linter:linter.py:168 Lexed tokens: ['/* A very long single-line block comment which is not ignored */', '\n', '']
INFO     sqlfluff.linter:linter.py:325 PARSING (<string input>)
INFO     sqlfluff.linter:linter.py:244
###
#
# Parsed Tree:
#
###
INFO     sqlfluff.linter:linter.py:245
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    block_comment:                                            '/* A very long single-line block comment which is not ignored */'
[L:  1, P: 65]      |    newline:                                                  '\n'
[L:  2, P:  1]      |    [META] end_of_file:

WARNING  sqlfluff.rules:base.py:1503 Tried to allowlist unknown rule references: ['noqa']
INFO     sqlfluff.linter:linter.py:586 LINTING (<string input>)
INFO     sqlfluff.linter:linter.py:418

Entering linter phase main, loop 1/10

INFO     sqlfluff.linter:linter.py:530 Fix loop complete for main phase. Stability achieved after 0/10 loops.
INFO     sqlfluff.linter:linter.py:418

Entering linter phase post, loop 1/10

INFO     sqlfluff.linter:linter.py:530 Fix loop complete for post phase. Stability achieved after 0/10 loops.
INFO     sqlfluff.linter:linter.py:566
###
#
# Fixed Tree:
#
###
INFO     sqlfluff.linter:linter.py:567
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    block_comment:                                            '/* A very long single-line block comment which is not ignored */'
[L:  1, P: 65]      |    newline:                                                  '\n'
[L:  2, P:  1]      |    [META] end_of_file:
======================== short test summary info =========================
FAILED test/rules/yaml_test_cases_test.py::test__rule_test_case[noqa_test_fail_block_comment_single_line_noqa] - Failed: No noqa failures found in query which should fail.
============== 1 failed, 3 passed, 1444 deselected in 3.79s ==============
```

What am I missing here?

**Comment by alanmcruickshank** [comment]
> What am I missing here?

The problem is at the top of the file you described with `rule: noqa`. I'll add those two cases for you and then you can take it from here. 👍

**Comment by daviewales** [comment]
Thank you. I've added some more tests, and this one is failing:

```
    /* noqa: disable=all */
    -- A noqa by itself in a block comment is followed
    /* noqa: enable=all */
```

I'll have a look to see why.

**Comment by daviewales** [comment]
Reverting 453db821c5418547fdf7f2f98765d8751f242352 makes the new tests pass, but I'm not sure why.

**Comment by daviewales** [comment]
I think it's ready for review. Thanks for your help @alanmcruickshank!

**Review by alanmcruickshank — APPROVED** [review]
Nice 👍 . Thanks for putting this together.

**Pull request merged**
