### PR TITLE
Adopt black code style

### LINKED ISSUE #481: Adopt black coding style
Especially as this project continues to attract new contributors, I think as unified coding style will be helpful.

I've quite enjoyed `black` for the most part, and there is a `flake8` plugin for `black` https://pypi.org/project/flake8-black/
And there is also a `pytest` plugin for black https://pypi.org/project/pytest-black/

Whichever coding style you prefer, I would be up for implementing it. Since it will touch pretty much the *entire* codebase, I would recommend saving it till the _end_ of a release

### PR DESCRIPTION
**Pull request by pwildenhain**
~Related to~ Closes #481 

While there are a **ton** of diffs, I'm noticing some patterns:
1. Many changes related to preferring double quotes over single quotes
2. Many changes related to indenting long lines
3. Many diffs in the `dialects` package alone

There are also a few linting CI failures, the `flake8-black` plugin mentions that there are a few `flake8` rules you would want to disable when using alongside `black`

What do you think @alanmcruickshank? Do you think `black` is an improvement? 
If so, do you think we should go for it now, or wait?
If not, do you have other suggestions for code formatters? I feel like a code linting/formatting library should have something like this 😁 😉

### CODE REVIEW

**Comment by alanmcruickshank** [comment]
HA! Yeah.... I take your point on lots of diffs!

I've skimmed through the suggested changes, and on the whole it looks pretty reasonable.

>I feel like a code linting/formatting library should have something like this 😁 😉

...well exactly.

Given the scale of this we should plan when to merge, but it's going to be painful whenever we do it, so we're just going to have to lean into that.

> There are also a few linting CI failures, the flake8-black plugin mentions that there are a few flake8 rules you would want to disable when using alongside black

What are the conflicts? I think they're the things we should hash out now and then the rest is just a case of timing.

... oh and we should totally make sure we've got a markdown badge for this if we're going to the effort of doing it... 🤷 

```markdown
[![Code style: black](https://img.shields.io/badge/code%20style-black-000000.svg)](https://github.com/psf/black)
```

**Comment by pwildenhain** [comment]
> What are the conflicts?

This is the recommended configuration settings for using `flake8-black`
```cfg
[flake8]
# Recommend matching the black line length (default 88),
# rather than using the flake8 default of 79:
max-line-length = 88
extend-ignore =
    # See https://github.com/PyCQA/pycodestyle/issues/373
    E203,
```
`E203` is the reason the linting CI is failing now (spaces before semi-colons)

And you know I want the fancy badge 📛 ✨ 😎  

>we should plan when to merge, but it's going to be painful whenever we do it

If you want, I can quickly add the plugin, with configuration, and the new badge. Or we can close this for now, and come back to this later.

For what it's worth, black only took 2 seconds to run, which was awesome ⚡

**Comment by alanmcruickshank** [comment]
Let's do it. You only live once 🤘

**Comment by pwildenhain** [comment]
We're good to go! Pinging 🔔 the other maintainers so they're aware of this change

**Comment by nolanbconaway** [comment]
yes! great call @pwildenhain !

**Comment by NiallRees** [comment]
🎉

**Review by alanmcruickshank — CHANGES_REQUESTED** [review]
One nit on the badge. Otherwise I've skimmed though all of the changes and I think they're going to be quite useful. If nothing else it's reminded me how far this project has come!

**Comment by pwildenhain** [comment]
🤷‍♂️ No idea why code coverage suffered, but I believe this is good to go 🚢

**Review by alanmcruickshank — APPROVED** [review]
Good to go - Merging now 👍

**Pull request merged**
