### PR TITLE
Roll back PR #2610

### LINKED ISSUE #2669: L052 breaking bug: comments not handled properly
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

In certain scenarios, applying L052 will remove line breaks and comment uncommented code.  Take for example the following code:
```
SELECT 1
from #l2

--Main
SELECT 2;
```

### Expected Behaviour

L052 fixes the code to the following:
```
SELECT 1
from #l2;

--Main
SELECT 2;
```

### Observed Behaviour

L052 changes the code to the following:
```
SELECT 1
from #l2;

--Main;SELECT 2;
```

### How to reproduce

Run fix on the above code for TSQL dialect and rule L052.

### Dialect

TSQL

### Version

latest main

### Configuration
```
[sqlfluff]
dialect = tsql
rules = L001,L002,L005,L006,L008,L009,L052

[sqlfluff:rules]
max_line_length = 140
comma_style = leading
single_table_references = qualified
unquoted_identifiers_policy = all

[sqlfluff:rules:L010]  # Keywords
capitalisation_policy = upper

[sqlfluff:rules:L040]  # Null & Boolean Literals
capitalisation_policy = upper

[sqlfluff:rules:L042]
# By default, allow subqueries in from clauses, but not join clauses.
forbid_subquery_in = both

[sqlfluff:rules:L052]
require_final_semicolon = True
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by barrywhart**
### Brief summary of the change made
Fixes #2669 
(Rolls back #2610. I reopened the original issue it was intended to address, #2588.)

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by tunetheweb — APPROVED** [review]

**Comment by tunetheweb** [comment]
Looks like we've lost some coverage @barrywhart . Can you look into that before merging if that stays the same after the latest commit?

**Comment by barrywhart** [comment]
The original PR had changes to a third file, `src/sqlfluff/core/rules/base.py`. I initially left those changes in place, thinking they may be useful in the future, but now I removed them. Hopefully that was the only uncovered code.

**Comment by barrywhart** [comment]
@tunetheweb: I'll be AFK for a few hours. If the build passes, can you please merge this? I seem to be stuck in a loop of update, wait, update, wait... 😛

**Comment by tunetheweb** [comment]
Will do. Looks like it's reaching 100% now so just need to get in quickly before something else is merged! :-)

**Pull request merged**
