### PR TITLE
Update documentation with new dialects

### PR DESCRIPTION
**Pull request by mchen-codaio**
### Brief summary of the change made

Add new dialects from https://github.com/sqlfluff/sqlfluff/pull/5979 into documentation. Companion to https://github.com/sqlfluff/sqlfluff/issues/5964
### Pull Request checklist

I don't think I need to test anything for documentation?

- [ ] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by alanmcruickshank** [comment]
@mchen-codaio - Welcome to the project! Looks like there are a couple of linting fails here. I think you've got some trailing whitespace at the end of one line and the indentation of the second looks off.

Also, if you're up for a little scope creep, I saw [this comment](https://github.com/sqlfluff/sqlfluff/issues/5964#issuecomment-2192409972) in the original issue, which asks whether we can include Trino in this list too. I've confirmed that Trino supports `UNION DISTINCT` in their docs here: https://trino.io/docs/current/sql/select.html

Do you need any help getting this PR ready for review?

**Comment by mchen-codaio** [comment]
@alanmcruickshank thanks for the tip! I tried to fix the whitespace. Assuming this one goes well then I can make a follow-up PR to add Trino. 

Personally I would love to see this in Snowflake as with [this comment](https://github.com/sqlfluff/sqlfluff/issues/5964#issuecomment-2185093577). UNION DISTINCT is not in their [official documentation](https://docs.snowflake.com/en/sql-reference/operators-query#union-all) but it works and it's helpful. I found a bug in some other code where a UNION should have been UNION ALL - adding the word would make it more explicit.

**Comment by alanmcruickshank** [comment]
> @alanmcruickshank thanks for the tip! I tried to fix the whitespace. Assuming this one goes well then I can make a follow-up PR to add Trino. 
> 
> Personally I would love to see this in Snowflake as with [this comment](https://github.com/sqlfluff/sqlfluff/issues/5964#issuecomment-2185093577). UNION DISTINCT is not in their [official documentation](https://docs.snowflake.com/en/sql-reference/operators-query#union-all) but it works and it's helpful. I found a bug in some other code where a UNION should have been UNION ALL - adding the word would make it more explicit.

Agreed, if you could add snowflake too that would be excellent. 👍

**Review by alanmcruickshank — APPROVED** [review]
LGTM! 👍

**Pull request merged**
