### PR TITLE
Postgres: Add `ALTER TYPE` support

### LINKED ISSUE #3216: Postgres: ALTER TYPE throws a "Found unparsable section" error.
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

This code:
```sql
ALTER TYPE ats RENAME TO ats__;
```
Generates this error:

```
L:   1 | P:   1 |  PRS | Line 1, Position 1: Found unparsable section: 'ALTER
                       | TYPE ats RENAME TO ats__'
```

### Expected Behaviour

It's valid PostgreSQL syntax so it should work: https://www.postgresql.org/docs/current/sql-altertype.html

### Observed Behaviour

See what happened section.

### How to reproduce

example.sql:
```
ALTER TYPE ats RENAME TO ats__;

```

```
sqlfluff lint --dialect postgres example.sql
```

### Dialect

Postgres

### Version

0.13.0

### Configuration

None.

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by greg-finley**
### Brief summary of the change made
Adds the most common things for `ALTER TYPE`. It's probably enough to close [the issue](https://github.com/sqlfluff/sqlfluff/issues/3216). I can add the remaining things when I get a chance.

Closes #3216

### Are there any other side effects of this change that we should be aware of?
I put it under `dialect_ansi` to match where `CreateTypeStatementSegment` is. It's also fine if we want to move it to `dialect_postgres`.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by tunetheweb — COMMENTED** [review]
I wonder should be moved to the Postgres dialect.

I've had a look around and very few dialects support custom types (so think we should move the `CreateTypeSegment` to Postgres too btw, and only Postgres seems to support `ALTER TYPE`.

Snowflake also removes the `CreateTypeStatementSegment` so similarly we should remove `AlterTypeStatementSegment` if we're not moving this to Postgres, but think we should move it.

WDYT?

**Comment by greg-finley-bond** [comment]
Yeah, I'll move both. 👍

**Comment by greg-finley** [comment]
Yeah, I'll move both 👍

**Review by tunetheweb — APPROVED** [review]

**Comment by 6e2f61** [comment]
As redshift dialect is derivative of postgresql should this also be added there?

**Pull request merged**
