### PR TITLE
Draft conda release action

### LINKED ISSUE #815: Please create conda package!
Please create conda package in conda-forge channel.

### PR DESCRIPTION
**Pull request by alanmcruickshank**
This (hopefully) resolves #815.

I don't know a lot about publishing to Anaconda, but from piecing together what I've found in a few sources, I think this might work. It's set up as a GitHub action to run on release just like the pypi release flow.

If anyone has any experience with this kind of thing - or knows any projects which do it - I'd love a second eye over this. Perhaps @nolanbconaway ?

### CODE REVIEW

**Review by nolanbconaway — APPROVED** [review]
Gh action looks good! Cannot speak to the conda metadata. Did you try a dry run manually?

**Comment by alanmcruickshank** [comment]
> Did you try a dry run manually?

How do you do a dry run of a github action? Do you just try running the underlying commands one by one or is there something smarter you can do?

**Comment by nolanbconaway** [comment]
> > Did you try a dry run manually?
> 
> How do you do a dry run of a github action? Do you just try running the underlying commands one by one or is there something smarter you can do?

Lol nope, nothing smarter :(

Usually i dig into the action code to see what they're calling and run that myself

**Comment by alanmcruickshank** [comment]
I'm going to abandon this for now. It's got too far behind and didn't work

**Pull request closed without merging**
