### PR TITLE
Add Support for Databricks `CREATE FUNCTION` Syntax in SparkSQL Parser

### PR DESCRIPTION
**Pull request by mitchellvanrijkom**
### Brief summary of the change made
This PR introduces support for the Databricks-specific `CREATE FUNCTION` syntax within the SparkSQL parser, addressing the current limitation where only standard SparkSQL dialect for creating functions is supported. The need for this enhancement arises from the differences in syntax between the standard SparkSQL `CREATE FUNCTION` command and the Databricks variant, which can lead to parsing errors when working with Databricks SQL scripts.

More documenantation can be found [here](https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-ddl-create-sql-function.html).

### Are there any other side effects of this change that we should be aware of?
No. This PR only affects the parsing of `CREATE FUNCTION` implementation for Databricks SQL variant.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by WittierDinosaur** [comment]
Why are you adding this to the sparksql dialect, and not the databricks dialect?

**Comment by mitchellvanrijkom** [comment]
Thank you for bringing this up. Since the SparkSQL dialect already includes Databricks-specific features like `CreateWidgetStatementSegment` and `ApplyChangesIntoStatementSegment`, it seemed consistent to also implement Databricks' `CREATE FUNCTION` functionality within the SparkSQL dialect.

**Comment by WittierDinosaur** [comment]
I think my concern here is that, while yes we do have databricks extensions in the sparksql dialect (though this is actually for legacy reasons), things like `CREATE FUNCTION` are core sql statements, not dialect specific extensions. I'm worried here that you may be overwriting spark's syntax with databricks, making breaking changes for spark users that arent databricks users

**Comment by mitchellvanrijkom** [comment]
I will update the code so that the `CREATE FUNCTION` is available in the Databricks dialect, as I understand it can impact Spark dialect users.

**Comment by phant0mw0lf** [comment]
@mitchellvanrijkom thanks for implementing this. does this also works for RETURNS TABLE? e.g.

```sql
CREATE OR REPLACE FUNCTION test_function (param BIGINT DEFAULT 0)
RETURNS TABLE
RETURN
SELECT 1 AS Test;

SELECT * FROM test_function()
```

**Comment by mitchellvanrijkom** [comment]
@phant0mw0lf This implementation is only focused on SQL scalar functions.

**Review by WittierDinosaur — APPROVED** [review]
LGTM

**Comment by WittierDinosaur** [comment]
@mitchellvanrijkom why did you close this? I was ready to merge?

**Comment by mitchellvanrijkom** [comment]
@WittierDinosaur my mistake. I thought I had to close it myself.

**Pull request merged**
