### PR TITLE
add hive dialect

### PR DESCRIPTION
**Pull request by satish-ravi**
This is for #417. Started adding a dialect for Hive based on https://cwiki.apache.org/confluence/display/Hive/LanguageManual. This currently supports a few DDL statements and imports other statements from ANSI dialect.

I based this on other dialects, but I wasn't sure exactly when to use `match_grammar` vs `parse_grammar`. Would appreciate some feedback on this before I continue adding other statements. Thanks!

### CODE REVIEW

**Comment by barrywhart** [comment]
TBH, I'm not sure about the distinction between `match_grammar` and `parse_grammar`. I usually use `match_grammar`. I think the distinction comes up _occasionally_ when the grammar may be a little ambiguous. In that case, I think `match_grammar` specifies what SQLFluff uses to "recognize" the code, while `parse_grammar` is used for creating the parse tree.

Here's an example of that from `dialect_ansi.py`. Note that the `match_grammar` tells when to **stop** recognizing the segment but lacks detail about the specific contents; `parse_grammar` provides that. I think 95% of the time, you will **only** use `match_grammar`.

```
@ansi_dialect.segment()
class PartitionClauseSegment(BaseSegment):
    """A `PARTITION BY` for window functions."""

    type = "partitionby_clause"
    match_grammar = StartsWith(
        "PARTITION",
        terminator=OneOf("ORDER", "ROWS"),
        enforce_whitespace_preceeding_terminator=True,
    )
    parse_grammar = Sequence(
        "PARTITION",
        "BY",
        Indent,
        # Brackets are optional in a partition by statement
        OptionallyBracketed(Delimited(Ref("ExpressionSegment"))),
        Dedent,
    )
```

@alanmcruickshank, @NiallRees, @dmateusp: Is my explanation reasonable here?

**Comment by NiallRees** [comment]
> TBH, I'm not sure about the distinction between `match_grammar` and `parse_grammar`. I usually use `match_grammar`. I think the distinction comes up _occasionally_ when the grammar may be a little ambiguous. In that case, I think `match_grammar` specifies what SQLFluff uses to "recognize" the code, while `parse_grammar` is used for creating the parse tree.
> 
> Here's an example of that from `dialect_ansi.py`. Note that the `match_grammar` tells when to **stop** recognizing the segment but lacks detail about the specific contents; `parse_grammar` provides that. I think 95% of the time, you will **only** use `match_grammar`.
> 
> ```
> @ansi_dialect.segment()
> class PartitionClauseSegment(BaseSegment):
>     """A `PARTITION BY` for window functions."""
> 
>     type = "partitionby_clause"
>     match_grammar = StartsWith(
>         "PARTITION",
>         terminator=OneOf("ORDER", "ROWS"),
>         enforce_whitespace_preceeding_terminator=True,
>     )
>     parse_grammar = Sequence(
>         "PARTITION",
>         "BY",
>         Indent,
>         # Brackets are optional in a partition by statement
>         OptionallyBracketed(Delimited(Ref("ExpressionSegment"))),
>         Dedent,
>     )
> ```
> 
> @alanmcruickshank, @NiallRees, @dmateusp: Is my explanation reasonable here?

As far as I understand, yes! I've been meaning to do some work on the architecture section of the docs for a good while. I think your explanation
> match_grammar specifies what SQLFluff uses to "recognize" the code, while parse_grammar is used for creating the parse tree.
summarises it very nicely.  https://github.com/sqlfluff/sqlfluff/issues/621

**Comment by satish-ravi** [comment]
Thanks @barrywhart and @NiallRees.

**Comment by NiallRees** [comment]
Hey @satish-ravi how are you doing? If you're still working on this that's great - otherwise would love to get what you've done so far merged as it's infinitely better than the existing Hive support.

**Comment by satish-ravi** [comment]
Hey @NiallRees, I finally got back to this. I've rebased with latest master and pushed some updates. I plan to work on some of the DML statements later this week, but merging this sounds good. I don't think I'll be to get to all statements any time soon. I can make separate PRs as I add support for more statements.

**Comment by NiallRees** [comment]
> Hey @NiallRees, I finally got back to this. I've rebased with latest master and pushed some updates. I plan to work on some of the DML statements in the coming weeks, but merging this sounds good. I can make separate PRs as I add support for more statements.

I think it might be good to add some parser test cases to the existing dialect support you've added, what do you think?

**Comment by barrywhart** [comment]
Definitely tests. For testing dialect parsing, the typical way is to just create a suite of SQL files with corresponding YML files. Have you seen these tests for the other dialects?

**Comment by satish-ravi** [comment]
@NiallRees @barrywhart I've added tests for the statements the dialect currently supports.

**Review by NiallRees — APPROVED** [review]

**Comment by R7L208** [comment]
I'm setting up CI for a spark3 SQL project and started working on a spark3 dialect a few days ago. SQLFluff is great, and I am very excited about the interest in HQL and Spark dialects :) 

Spark generally maintains a native and `Hive` based format for commands. Since the Spark project is moving towards ANSI compliance overall, I think the best option would be to inherit from the ANSI dialect then use `get_segments` to retrieve the needed Hive format commands and common syntax that isn't shared with ANSI (i.e. partitioning).  In my opinion, basing spark off of the hive dialect would cause more work in the future as these continue to diverge.

If there's sufficient interest in a separate dialect for Spark2 then this should be based on Hive.

**Pull request merged**
