### PR TITLE
L060: Use COALESCE instead of IFNULL or NVL.

### LINKED ISSUE #2392: New Rule: Use COALESCE over IFNULL or NVL
From Brooklyn Data co. style guide: https://github.com/brooklyn-data/co/blob/main/sql_style_guide.md#use-coalesce-instead-of-ifnull-or-nvl
```
Use coalesce instead of ifnull or nvl.
- coalesce is universally supported, whereas Redshift doesn't support ifnull and BigQuery doesn't support nvl.
- coalesce is more flexible and accepts an arbitrary number of arguments.
```

Should be pretty simple to implement

### PR DESCRIPTION
**Pull request by jpy-git**
### Brief summary of the change made

Closes #2392. Adds a new rule to require the use of `COALESCE` over `IFNULL` or `NVL`. See linked issue for source + motivation. 

### Are there any other side effects of this change that we should be aware of?
No

### Pull Request checklist
- [X] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by jpers36** [comment]
In TSQL, COALESCE and ISNULL (TSQL's version of it) perform slightly differently, [specifically around datatyping](https://www.mssqltips.com/sqlservertip/2689/deciding-between-coalesce-and-isnull-in-sql-server/), such that they can't be swapped one for the other 100% of the time. TSQL won't be affected by this change at the moment since ISNULL isn't checked, but are there any similar concerns in the dialects that this change will impact?

**Review by sti0 — APPROVED** [review]
Great rule. LGFM. 🎉

**Review by barrywhart — APPROVED** [review]

**Comment by jpy-git** [comment]
> In TSQL, COALESCE and ISNULL (TSQL's version of it) perform slightly differently, [specifically around datatyping](https://www.mssqltips.com/sqlservertip/2689/deciding-between-coalesce-and-isnull-in-sql-server/), such that they can't be swapped one for the other 100% of the time. TSQL won't be affected by this change at the moment since ISNULL isn't checked, but are there any similar concerns in the dialects that this change will impact?

@jpers36 so while I agree there can be small performance differences between these similar functions, I think that sort of misses the spirit of a rule like this which is intended for code consistency and portability which is often more valued in Data Analytics/Science contexts than these small performance differences. I think users concerned about you can always just turn on or off depending on preference.

I didn't consider `ISNULL` since it wasn't in the Brooklyn Data co. guide but based off the definition/motivation we should probably include it in this rule as well.

**Comment by jpers36** [comment]
> @jpers36 so while I agree there can be small performance differences between these similar functions, I think that sort of misses the spirit of a rule like this which is intended for code consistency and portability which is often more valued in Data Analytics/Science contexts than these small performance differences. I think users concerned about you can always just turn on or off depending on preference.

To be clear, my concerns are not performance-related, at least not in terms of speed. Switching ISNULL to COALESCE will break code at times.

**Comment by jpy-git** [comment]
> To be clear, my concerns are not performance-related, at least not in terms of speed. Switching ISNULL to COALESCE will break code at times.

@jpers36 ah gotcha thanks for clarifying! That would likely explain why it isn't included in the original style guide then 😄 

Will merge as is then 👍

**Comment by barrywhart** [comment]
@jpy-git: I'm trying to follow the discussion above. From your final comment:
>@jpers36 ah gotcha thanks for clarifying! That would likely explain why it isn't included in the original style guide then 😄
>Will merge as is then 👍

I thought you were going to either exclude this rule for T-SQL or for `ISNULL`, but it looks like we didn't. Did I misunderstand something? Thanks!

**Comment by jpy-git** [comment]
@barrywhart `ISNULL` was never included in this PR? This rule (inline with the Brooklyn Data co style guide) changes `IFNULL` & `NVL`.

**Comment by barrywhart** [comment]
Oh, got it! `IFNULL` vs `ISNULL` -- got confused by the similarity. 

🎉 💯

**Comment by jpy-git** [comment]
> `IFNULL` vs `ISNULL` -- got confused by the similarity.

Classic confusing SQL naming haha 😅

**Pull request merged**
