### PR TITLE
Add validation and documentation for all sqlfluff default configs

### LINKED ISSUE #3: Feature request: some pre-set options for SQL style guides
Hi @alanmcruickshank,

Thanks a ton again for taking the time to build `sqlfluff` -- I believe it has the potential to be the [linter that is sorely missing](https://www.reddit.com/r/SQL/comments/8wnysv/is_it_accurate_to_say_that_uniform_code_style_and/)!

I am not sure what are your future plans, but if I may, I'd suggest trying to add rules from a few guidelines -- here are the ones I am familiar with:

- http://docs-origin.telemetry.mozilla.org/concepts/sql_style.html
- https://www.sqlstyle.guide/

If you would be open to exploring this direction, I would be happy to put together a few rules as well -- from looking at the code it seems fairly straightforward.

Thanks again!

### PR DESCRIPTION
**Pull request by pwildenhain**
Closes #3

### CODE REVIEW

**Review by alanmcruickshank — CHANGES_REQUESTED** [review]
I think linking to the default config is part of the solution, but we should also point people toward the `Rules Reference` page somehow because that it where they'll see all the configuration options for different rules, not all of which are in the default config.

If people are going to want to set up their own rules config then they'll need to use both resources.

**Comment by pwildenhain** [comment]
> ... where they'll see all the configuration options for different rules, not all of which are in the default config.

Should they be in the default config? The ones I found were:
* [allow_scalar](https://docs.sqlfluff.com/en/latest/rules.html#sqlfluff.rules.std.Rule_L013)
* [single_table_references](https://docs.sqlfluff.com/en/latest/rules.html#sqlfluff.rules.std.Rule_L028)
* [only_aliases](https://docs.sqlfluff.com/en/latest/rules.html#sqlfluff.rules.std.Rule_L029)
* [capitalisation_policy (L014)](https://docs.sqlfluff.com/en/latest/rules.html#sqlfluff.rules.std.Rule_L014)
* [capitalisation_policy (L030)](https://docs.sqlfluff.com/en/latest/rules.html#sqlfluff.rules.std.Rule_L030)

I'm happy to add them 😁 

I agree we should still link to the rules reference, so they can read the documentation on these options 👌

**Comment by alanmcruickshank** [comment]
>Should they be in the default config?

Good question. 🤔 

I assumed *not* because then we're setting defaults in two places. There are defaults on the rule itself (the default kwargs) and then also defaults in the `default_config.ini` file. This feels like potentially confusing duplication.... *but* it's also true that the `default_config.ini` file is also much more accessible that trawling through the rules config.

What do you think?

**Comment by pwildenhain** [comment]
I agree that it's tedious and potentially buggy 🐛 to have defaults in two places. 

My vote is for only having defaults in the `default_config.ini` and no defaults on the rules themselves, since they should just pick them up from the `default_config.ini` right?

**Comment by alanmcruickshank** [comment]
@pwildenhain - does that mean that if there is no default specified for a config value in the `default_config.ini` then there should be an error raised on load? I could get on board with that if so.

We'd need a little bit of machinery within the rules section to make sure that it's not a massive overhead to set things up but it could be quite neat.

I've just reviewed all the `__init__` methods on each of the rules, and the only thing they're doing is setting up config values and validating those inputs. Which is leading me to a crazy idea:
- No rule should define an `__init__` function itself.
- Each rule defines an [optional] list of keyword names (see example below), which specifies which config options are available.
- Each rule (or maybe the `RuleSet` centrally) [optionally] defines a set of `validators`, to say what the acceptable values are for any given config setting.
- The `BaseCrawler` class `__init__` method reads the `config_keywords` list and a) validates that they are never null [which catches the case that they aren't defined in `default_config.ini`. If no, raises error saying that config values are missing from default config - _aimed at developers_  b) validates the given value against the `validators` [if one is available for the given config value] to make sure only acceptable values are provided. If found, raises an error saying that an invalid config value has been set - _aimed at users_.
- For bonus points I'm hoping that the `config_keywords` attribute will automatically appear in the docs too so that we don't have to specifically update them too!

@pwildenhain does this a) sound like a good idea b) sounds like something you could put together, or would you need a hand?

**Comment by pwildenhain** [comment]
I'll give it a go, and let you know if I get stuck 👍

**Comment by pwildenhain** [comment]
> Each rule (or maybe the RuleSet centrally) [optionally] defines a set of validators, to say what the acceptable values are for any given config setting.

I _think_ I've got an ok solution for this. However... 🙄 

>The BaseCrawler class __init__ method ............... b) validates the given value against the validators [if one is available for the given config value] to make sure only acceptable values are provided.

I wasn't sure how to implement this type of validation 🤔 from `BaseCrawler.__init__`. If the `validators` live in `RuleSet`, how can I access them within `BaseCrawler.__init__`? It seemed that if they were going to live in `RuleSet`, then they could be validated during `RuleSet.get_rulelist()`.
 
I also upgraded 💪 the existing "improper" config test to test _all_ configs 🎉 

As for:
>Each rule defines an [optional] list of keyword names

and

> The BaseCrawler class __init__ method reads the config_keywords list and a) validates that they are never null [which catches the case that they aren't defined in default_config.ini. If no, raises error saying that config values are missing from default config

I have a some code that I think will work, but wanted to run it by you
```python
class BaseCrawler:
    """The base class for a crawler, of which all rules are derived from."""

    _works_on_unparsable = True

    def __init__(self, code, description, **kwargs):
        self.description = description
        self.code = code
        # Any unused kwargs will just be ignored from here.

        # We also define a custom logger here, which also includes the code
        # of the rule in the logging.
        self.logger = RuleLoggingAdapter(rules_logger, {'code': code})
        # Validate that declared configuration options exist
        try:
            for keyword in self.config_keywords:
                if keyword not in kwargs.keys():
                    raise ValueError(
                        (
                            "Unrecognized config '{0}' for Rule {1}. If this "
                            "is a new option, please add it to "
                            "`default_config.ini`"
                        ).format(keyword, code)
                    )
        except AttributeError:
            self.logger.info("No config_keywords defined for {0}".format(code))
```

This checks any `config_keywords` against the config options passed through in `kwargs` and complains if it doesn't find it in there -- prompting the developer to either fix it or add the new option to `default_config.ini`.

What do you think about this?

**Review by alanmcruickshank — CHANGES_REQUESTED** [review]
This *approach* looks spot on. Really nice. I haven't actually tried to run your changes, but I think the idea is sound. In particular you make a really good point about not being able to do this in `BaseCrawler.__init__`, your approach is better.

The things I'd love to do from here are:
- Incorporate your code snippet from the conversation about `config_keywords`.
- Remove all the existing rule `__init__` functions (and check the tests still pass 🤞 ).
- I'd love to have some test cases which also validate the _failure_ modes that we've designed. Are the right error messages raised in the right places if people misuse this (because they definitely will). This would complement the tests you've already got for the happy path.
- See what the docs look like. Because all the rule definitions are generated by autodoc (here)[https://github.com/sqlfluff/sqlfluff/blob/master/docs/source/rules.rst#specific-rules], my hope is that as long as `config_keywords` is a public method, that it should automatically end up being rendered in the docs. If not, my hope is that playing with the settings for autodoc should get it to.

**Comment by pwildenhain** [comment]
Incorporated the `BaseCrawler` changes to:
1. Dynamically the configs to `BaseCrawler` so they can be used *as is* in the existing rules
2. Validate that the `config_keywords` represent an actual config value (and raise a `ValueError` if not)


Still need to:
1. Add tests for `config_keywords` validation (tested locally and it worked 👍 )
2. Figure out how to incorporate `config_keywords` in the docs 🤔 
    - How to add `config_keywords` to autodoc
    - Where to store `config_keywords` definitions so they can all be accessed from one place (maybe get them from the existing `RuleSet.validators`?)

**Comment by alanmcruickshank** [comment]
> 2\. Figure out how to incorporate `config_keywords` in the docs 🤔

For this, try adding `config_keywords` into one or two rules, go to the docs and use the makefile or `Make.bat` to build the docs locally and see if it has been included. If it has, great 🙌 , if not, let me know and I can have a think too.

Worst case, we just make sure they're listed in the rule doctring by hand. 🤷 [it would just be nice if we can get it to work automatically]

**Comment by pwildenhain** [comment]
This one really morphed on us! Thanks so much for your guidance. Looking forward to your feedback on my solution for config validation and auto-documentation

**Review by alanmcruickshank — CHANGES_REQUESTED** [review]
Ok, this is looking awesome. I really like what you've done with the documentation hack - very nice, and I hadn't thought about doing anything like that!

Two points I would love to change:
- At the moment I think the role of the `rules.config` file is a bit mixed. It's partly defining machinery and also partly defining some properties of the standard rule set. I think the definitions of the validators should be in `rules.std`, but that the rest of the code should stay where it is. That way we can separate the configuration from the logic which processes it.
- I think the way that the config is loaded in `rules.config` also leaves us open to issues, especially if people start importing `sqlfluff` as a module rather than as a cli tool. Rather than importing `ConfigLoader` directly, I think we should somehow get the rules config to work off a `FluffConfig` which should be passed to it when someone calls `rules.get_ruleset()` (which is the current standard entry point). I wonder if the same pattern used in the dialects (`dialects.__init__()`) to do `dialect.expand()` *after* we've fetched it could work (except that `rule_set.validate` (or whatever we call it) would need to have a `FluffConfig` passed to it.

If we can solve those two then I think we're good to go!

**Comment by pwildenhain** [comment]
Thanks for the feedback 🙌 
A few follow up questions:
>It's partly defining machinery and also partly defining some properties of the standard rule set. I think the definitions of the validators should be in `rules.std`, but that the rest of the code should stay where it is

Ah yea, I see what you mean. We def should keep the config separate from the process, though I think I'm struggling to see how to best do that.

Right now `document_configuration` uses every key of the `_CONFIG_INFO_DICT` (validation, definition, default) in order to auto-generate the documentation. 🤔 We could possibly add the validators _after_ importing `CONFIG_INFO_DICT` into `rules.std` but I think that creates a weird dependency where `document_configuration` is expecting a dict key, which doesn't appear until a separate module.

I think if you want the validators to live separately in `rules.std` then that's likely where `document_configuration` should live as well. And at that point, it doesn't seem useful to keep `rules.config` around. What do you think about that? Or am I missing something here?

>  I wonder if the same pattern used in the dialects (`dialects.__init__`) to do `dialect.expand()` after we've fetched it could work (except that `rule_set.validate` (or whatever we call it) would need to have a `FluffConfig` passed to it.

I _think_ I see what you're getting at here. Currently there is a `RuleSet._validate_config_options` method (added in d021239551382c0a839955a8a842e1cb90f28320 of this PR), and that gets called in `RuleSet.get_rulelist()` (and currently works off a `FluffConfig` passed to it). Are you suggesting that we would _delay_ the config validation until the rules are fetched in `rules.get_ruleset` (similar to dialects.expand())? Rather than validating within `RuleSet.get_rulelist()`? This could also solve the issue of where the `document_configuration` would live, as it would just be a part of `RulesSet`.

Quick non-sequitur:
Did you invent `RuleSet`, imagining that this would be a way people could implement multiple sql styles? Like, you define your `RuleSet` and then that gets used in linting? If so, I wonder if that's been superseded by the configs available in `.sqlfluff`. If not though, I'm interested in understanding more about this design decision

**Comment by pwildenhain** [comment]
Thank you for the detailed explanation 🙇‍♂️ 

I will try moving the logic to live under `RuleSet` and see how that pans out. It does seem like a cleaner implementation 🛀

**Comment by pwildenhain** [comment]
You were totally right 🤝 this is so much cleaner 🤩

**Review by alanmcruickshank — APPROVED** [review]
Nice 👍

**Pull request merged**
