### PR TITLE
Fix issue where "--nocolor" is ignored

### LINKED ISSUE #3532: "--nocolor" option is not honored
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

` sqlfluff lint --verbose --nocolor --dialect ansi --disable_progress_bar queries.sql --write-output result.txt `
 
content on result.txt file has ansi chars:
```
 ==== sqlfluff ====
[30m[1msqlfluff[0m:                1.0.0 [30m[1mpython[0m:                  3.9.7
....
```
` sqlfluff lint --verbose --nocolor --dialect ansi --disable_progress_bar queries.sql >result2.txt`

content onresult2.txt hasn't any ansi chars:
 ```
==== sqlfluff ====
sqlfluff:                1.0.0 python:                  3.9.7
....
```
but worse....
` sqlfluff lint --verbose --dialect ansi --disable_progress_bar queries.sql`
returns plain output to console
 ```
==== sqlfluff ====
sqlfluff:                1.0.0 python:                  3.9.7
....
```

### Expected Behaviour

1) Both syntax "--write-output result.txt" and "> result.txt" should return the same content

2) the "--nocolor" option  should be always honored

### Observed Behaviour

(see above)

### How to reproduce

```
$ sqlfluff lint --verbose --nocolor --dialect ansi --disable_progress_bar queries.sql --write-output result.txt 
$ cat result.txt 
$ sqlfluff lint --verbose --nocolor --dialect ansi --disable_progress_bar queries.sql >result2.txt
$ cat result2.txt 
```

### Dialect

ansi

### Version

1.0.0

### Configuration

No user config file

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by barrywhart**
### Brief summary of the change made
Fixes #3532

When I began investigating this issue, I found **tons** of standalone functions doing color output without any checking whether color output was possible or desired. Rather than update these functions to take additional parameter(s), I moved them to become methods on the `OutputStreamFormatter` class, whose constructor now determines whether color output is enabled.

This required moving a lot of code around, but I believe this was the best way to try and squash all the color-related bugs now and to avoid future ones.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Review by tunetheweb — APPROVED** [review]
A lot of change here so difficult to review completely. But could't spot anything wrong.

**Comment by barrywhart** [comment]
Thanks! There are very few actual additions or changes, just moving things around.

Overnight, I thought of a couple things I want to look at:
* Add a specific test for the user's issue
* Look at some related code re: output format that we may be able to combine or eliminate

**Comment by barrywhart** [comment]
@tunetheweb: I added a new test, `test/cli/commands_test.py::test__cli__command_lint_nocolor`, to check specifically for the user's issue. This general test structure (plus possibly adding more cases someday) will help ensure colors don't sneak into the output.

**Comment by tunetheweb** [comment]
SGTM!

**Pull request merged**
