### PR TITLE
Fix ignored implicit indent for `CASE .. WHEN` statements

### PR DESCRIPTION
**Pull request by borchero**
### Brief summary of the change made

This should resolve https://github.com/sqlfluff/sqlfluff/issues/4559#issuecomment-1477811414.

### Are there any other side effects of this change that we should be aware of?

Different formatting of `CASE .. WHEN` expression when `allow_implicit_indents = true`.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by borchero** [comment]
Resolves #4590.

**Comment by alanmcruickshank** [comment]
I think this also fixes #4579 .

@borchero - I don't know if I'm entirely on board with this layout, but I'm up for exploring it. See comment here: https://github.com/sqlfluff/sqlfluff/issues/4579#issuecomment-1480235760.

Of the indents you propose, I think I have different views:

## Implicit indent between `CASE` and `WHEN` in `CASE WHEN`

Adding the implicit indent in the situation where there isn't an expression between `CASE` and `WHEN`:

```sql
-- That would allow this...
SELECT
    CASE WHEN a THEN b
        WHEN c THEN d
        ELSE e
    END AS f
FROM foo;
-- ...which I think is ok.
-- It _also_ allows this though (which I think is kind of gross):
SELECT
    CASE WHEN a
            THEN b
        WHEN c THEN d
        ELSE e
    END AS f
FROM foo;
```

## Implicit indent between `CASE` and `WHEN` in `CASE <expression> WHEN`

Similarly to the above, but even more convoluted.

```sql
-- That would allow this...
SELECT
    CASE x + y WHEN a THEN b
        WHEN c THEN d
        ELSE e
    END AS f
FROM foo;
-- ...which I'm not sure is great and _also_ allows this (which is worse):
SELECT
    CASE x + y WHEN a
            THEN b
        WHEN c THEN d
        ELSE e
    END AS f
FROM foo;
```

## Implicit indent just before `THEN` in `CASE`

This one I think is fairly uncontroversial...

```sql
-- That would allow this...
SELECT
    CASE
        WHEN a THEN
            b
            + c
        WHEN c THEN d
        ELSE e
    END AS f
FROM foo;
```

...however, I do wonder if this one is more about configuring whether the default is for indents after `THEN` or before `THEN` in clauses like this.

@borchero - would you be able to add a wider range of test cases to flesh out what you're suggesting?

**Comment by fredriv** [comment]
I tried out this PR on my examples from https://github.com/sqlfluff/sqlfluff/issues/4589, and while it now no longer requires a line break it still complains about the indentation, e.g. it wants to change from

```
select
    a,
    case
        when a = 1 then
            case
                when b then 'bar'
            end

        when a = 2 then case
            when b then 'bar'
        end
    end as c

from my_table
```

to
```
select
    a,
    case
        when a = 1 then
                case
                    when b then 'bar'
                end

        when a = 2 then case
                    when b then 'bar'
                end
    end as c

from my_table
```

So it seems like it wants an extra level or two of indentation in the nested case / when statements?

**Comment by alanmcruickshank** [comment]
Yeah, I wondered if this might happen @fredriv. I think it's what I meant when I said:
> ...however, I do wonder if this one is more about configuring whether the default is for indents after THEN or before THEN in clauses like this.

I think a better solution to your specific problem would be to optionally allow a configuration which moves the normal `Indent` (not an implicit one), from _before_ the `THEN` to _after_ the `THEN`. We could implement that very similarly to the switches [described here](https://docs.sqlfluff.com/en/stable/layout.html#configuring-indent-locations) in the docs.

**Comment by fredriv** [comment]
Added another more concrete example from our codebase to the other PR though: https://github.com/sqlfluff/sqlfluff/issues/4589#issuecomment-1480340967

I tried playing around a bit with the `WhenClauseSegment` of `dialect_ansi.py`, and by replacing
```
        Indent,
        "THEN",
        ImplicitIndent,
        Ref("ExpressionSegment"),
        Dedent,
        Dedent,
```
with
```
        "THEN",
        Indent,
        Ref("ExpressionSegment"),
        Dedent,
```

I got it to accept
```
select
    a,
    case
        when product_type = 'Product' then
            case
                when measured_weight > 0 then measured_weight
                else quantity * item_weight
            end
        else 0
    end as product_weight

from my_table;
```

Is that what you meant @alanmcruickshank (just making it configurable, of course)?

**Comment by fredriv** [comment]
The existing `ImplicitIndent` after `THEN` works if I move `then` to the line after, but then it requires extra indentation for the `case` body - any way to avoid that? 🤔 
```
select
    a,
    case
        when product_type = 'Product'
            then case
                    when measured_weight > 0 then measured_weight
                    else quantity * item_weight
                end
        else 0
    end as product_weight

from my_table;
```

**Comment by alanmcruickshank** [comment]
> Is that what you meant @alanmcruickshank (just making it configurable, of course)?

You've got the effect of what I'm suggesting yes, but not necessarily the implementation.

The default is:

```python
    match_grammar: Matchable = Sequence(
        "WHEN",
        Sequence(
            ImplicitIndent,
            Ref("ExpressionSegment"),
            Dedent,
        ),
        Indent,
        "THEN",
        ImplicitIndent,
        Ref("ExpressionSegment"),
        Dedent,
        Dedent,
    )
```

I think you're wanting an indentation more like:

```python
    match_grammar: Matchable = Sequence(
        "WHEN",
        Sequence(
            ImplicitIndent,
            Ref("ExpressionSegment"),
            Dedent,
        ),
        # No indent here
        "THEN",
        ImplicitIndent,
        Ref("ExpressionSegment"),
        Dedent,
        # No dedent here
    )
```

The functionality we have at the moment for switching indents like this is the `Conditional` grammar, as demonstrated in the `WithCompoundStatementSegment`:

```python
class WithCompoundStatementSegment(BaseSegment):
    """A `SELECT` statement preceded by a selection of `WITH` clauses.

    `WITH tab (col1,col2) AS (SELECT a,b FROM x)`
    """

    type = "with_compound_statement"
    # match grammar
    match_grammar: Matchable = Sequence(
        "WITH",
        Ref.keyword("RECURSIVE", optional=True),
        Conditional(Indent, indented_ctes=True),
        Delimited(
            Ref("CTEDefinitionSegment"),
            terminator=Ref.keyword("SELECT"),
        ),
        Conditional(Dedent, indented_ctes=True),
        OneOf(
            Ref("NonWithSelectableGrammar"),
            Ref("NonWithNonSelectableGrammar"),
        ),
    )
```

You can see that theres an `Indent` - `Dedent` pair which is only enabled if `indented_ctes` is `True` (and `indented_ctes` is assumed to be a configuration value in the `indentation` section).

I wonder if the solution here is making the `Indent` and `Dedent` that I mentioned above, conditional on some configuration value. I don't think that value should be set by default, because it's not the typical style that most style guides follow - but I'm very happy for it to be a configurable option for projects that prefer that style of formatting.

**Comment by fredriv** [comment]
Sounds good! I could have a go at creating a PR if you want @alanmcruickshank? 🙂

**Comment by alanmcruickshank** [comment]
> Sounds good! I could have a go at creating a PR if you want @alanmcruickshank? 🙂 

I would love that! ♥️ Always keen for new contributers.

**Pull request closed without merging**
